### PR TITLE
[FEAT] Add Custom Avatars

### LINKED ISSUE #814: [IDEA][ART] Custom Avatars in Town Hall
# Custom Avatars
Hey guys, so currently we only have the `farmer` and `goblin` avatars in the Town Hall:
Sample:

https://user-images.githubusercontent.com/18549210/167164855-95bbcd14-fc57-4aa1-a792-9a6fa9b94fb9.mov

### Note:
- Preferred sizes: `14x18` or `14x16` or `18x16`
- Follow the art guidelines

### PR DESCRIPTION
**Pull request by tiffanydys**
# Description
- added custom avatars from #814 

Fixes #814

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
`yarn dev`

https://user-images.githubusercontent.com/18549210/167315783-2352afef-9be1-45f3-b539-f2c82461b954.mov

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Ant-Redstone — CHANGES_REQUESTED** [review]
You removed me (Ant) completely, I got a duplicate of me with wrong Farm ID (mine is 39 not 9), u forgot to put the "ant" avatar, but avatar got added everywhere else

**Comment by adamhannigan** [comment]
@Ant-Redstone Good to see you in the Github repo 👋

**Comment by tiffanydys** [comment]
Hey guys, currently away atm but I'll be editing @Ant-Redstone 's when i get back 🤗

**Comment by Rofrtd** [comment]
> Hey guys, currently away atm but I'll be editing @Ant-Redstone 's when i get back 🤗

I feel like @spencerdezartsmith and I could be there too? 😂

**Comment by tiffanydys** [comment]
> > Hey guys, currently away atm but I'll be editing @Ant-Redstone 's when i get back 🤗
> 
> 
> 
> I feel like @spencerdezartsmith and I could be there too? 😂 

Definitely! You can add your details in the attached Github Issue I will get to them later today ☺️

**Comment by InuBakaBo** [comment]
There is also a duplicate of AKCH1N

**Comment by tiffanydys** [comment]
> There is also a duplicate of AKCH1N

You can see it here that the duplicates have already been removed 😄

**Comment by tiffanydys** [comment]
> You removed me (Ant) completely, I got a duplicate of me with wrong Farm ID (mine is 39 not 9), u forgot to put the "ant" avatar, but avatar got added everywhere else

Hello there @Ant-Redstone I made sure your `farmId` is indeed `39` - only edited the `man` avatar
Screen Shot 2022-05-09 at 2 55 39 PM

what you're seeing here on github displays different lines (there are skipped lines of codes that don't have much change on them)
Screen Shot 2022-05-09 at 2 54 39 PM

**Comment by Pranav-yadav** [comment]
Nice Improvements !

As, this feat is not merged and being review,
There are few points that I would like to put forward, to make sure this the purpose of *Town Hall* remains professional, ..

1. Add different role for Team (Adam, Romy and Spencer) as *Team* / *Core Team* / *Core Dev*
    Or
   Completely _Remove_ the core team members from Town Hall as the purpose of this is to show *Community Contributors* and 
   let interested players help them.. There's difference between *Core Team* and *Contributors*. And, hence the contributor badges must also be burned if any added to the Core Team farms 
   PS: I would suggest latter, No hard feelings, ❤️ team

2. *Coder* & *Artist* roles are tooooooooooo generic, we should add separate roles as
     - *Certified Coder* - those with "Certified Coder" role on SFL Discord. (Ask me, it's difficult to get this, and should be)
     - *Coder* - newbie coder 😉 (given manually)
     - *Certified Artist* - those with "Certified Artist" role on SFL Discord. 
     - *Artist* - newbie artist (given manually)
     
3. As per [2], separate the contributor level badges for all those, as well the their **`Levels`** in home, and the `%` of boosts provided.

4. Remove Admins (Woody, ChickenCX , other if exists), the same reason stated under [1].
    PS: No hard feelings, ❤️ admins

5. Take care of proper `%` of boosts provided for contributor levels, like Contributor Level 1 and 2
6. As, mentioned earlier if any wrong (in above context) badges are minted and sent to farms with wrong roles (like team or any other roles) they **must** be burned.. (Irrespective of Team Supply 👀 )

PS: ATM this was posted, Contributors Include: Certified Coders, Coders, Certified Artists, Artists, Moderators, Ambassadors. 👍 

@adamhannigan @spencerdezartsmith @Rofrtd you should discuss on this and specify the `standards`.. 👍

**Comment by Pranav-yadav** [comment]
Posting as proposal... That would be better...

**Comment by alvinphoebeartemis** [comment]
Hi boss @tiffanydys, good day, 🤗 requesting to change my farm ID from `2965` to `2956`. Thank you.

**Comment by adamhannigan** [comment]
Closing for inactivity. For a range of copyright and art consistency reasons, unfortunately we can't explore the route of having custom avatars for everyone. To keep it easier to maintain, there will be a shorter list of available avatars to choose from ❤️

**Pull request closed without merging**
