### PR TITLE
[FIX] Multiple UI Adjustment

### PR DESCRIPTION
**Pull request by hujikol**
# Description

Work on progress, multiple updates on UI

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

will update the UI here

| Number | Before | After |
| ------------- | ------------- | ------------- |
| 1 |  |  |
| 2 |  |  |
| 3 |  |  |
| 4 |  | |
| 5 |   |  |
| 6 |  |  |
| 7 |  |  |
| 8 |  |  |
| 9 | image | image |
| 10 | image | image |
| 11 | image | image |
| 12 |  |  |
| 13 | Before |  |
| 14 |  |  |
| 15 | image | image |
| 16 | image | image |
| 17 | image | image |
| 18 | image | image |
| 19 | image | image |
| 20 | image | image |
| 21 | image | image |
| 22 | image | image |
| 23 | image | image |
| 24 | image | image |
| 25 | image | image |
| 26 | image | image |
| 27 | image | image |
# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by spencerdezartsmith — COMMENTED** [review]
Great job!  Love the attention to detail. There are a couple other things that I would love to get into this PR too.

Padding on this to too big and text is too small:
Screen Shot 2022-11-28 at 11 13 23 am

The bottom of the `y` is getting cut off in tabs. 

Screen Shot 2022-11-28 at 11 12 39 am

Do you think you could get these fixes in also?

Also just a heads up for next time... mobile is super important so its really helpful to attach screenshots of how the changes look on small mobile screens as thats usually where issues arise.

**Comment by spencerdezartsmith** [comment]
Actually we can fix the other issues in another ticket. I will get this in for now.

**Review by spencerdezartsmith — APPROVED** [review]
🚀

**Comment by hujikol** [comment]
> Padding on this to too big and text is too small:
> image

this one is getting adjusted on #1761 
<br/>

> The bottom of the y is getting cut off in tabs.
> image

@spencerdezartsmith 
should we add the bottom `y`? because on my inspection it looks clean enough, 
and I think it happens because that trader tab has an `overflow-hidden` class, should we stick with it? because it's quite inconsistent in other tabs... some others don't use it. 

I could include this fix in my next PR.

Mobile:
image

Desktop:
image

**Pull request merged**
