### PR TITLE
[FIX] Add missing bait to wharf

### PR DESCRIPTION
**Pull request by brian-man**

### CODE REVIEW

**Comment by adamhannigan** [comment]
Thanks @brian-man. This will need some API additions.

What is the main use case for storing the bait that was used?

**Comment by brian-man** [comment]
> Thanks @brian-man. This will need some API additions.
> 
> What is the main use case for storing the bait that was used?

Same reason to include the chum info:
(1) display in the UI for better UX
(2) support experimentation

For the latter, motivated people will remember / write-down anyway so this just reinforces that experimentation is intentionally a goal and part of the design of the fishing feature.

**Comment by adamhannigan** [comment]
@brian-man Good point - I've added this to our backend tasks 👍

**Comment by brian-man** [comment]
> @brian-man Good point - I've added this to our backend tasks 👍

@adamhannigan 
How's the timing for this looking?

**Pull request merged**
