### PR TITLE
[WIP] Move 3rd Party Assets

### PR DESCRIPTION
**Pull request by LittleEins**
# Description

This PR moves 3rd party assets(modified/not-modified) in the private repository and relink them to the game.

Fixes #issue

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Polysemouse** [comment]
How should we add new assets to the game moving forward if this PR is implemented?

**Comment by LittleEins** [comment]
> How should we add new assets to the game moving forward if this PR is implemented?

If they are not third party assets it should be fine.
If they are third party(modified/not-modified), we will need to upload them ourselves.

**Review by adamhannigan — CHANGES_REQUESTED** [review]
Awesome work @LittleEins Your attention to detail is impressive!

I found a few small areas of the game with missing images we will want to patch up:

1. The grey background is missing n the "New Delivery" label that appears on the Codex button
2. The SFL icon is missing on the "SFL" label in the Delivery section of the codex
3. My island background was missing (Basic Island - 6 expansions)
4. The SFL icon was missing the Codex Delivery Details Reward section (should show the SFL icon left of the "Reward" text.
5. When I go to an NPC in the plaza to deliver, the chest icon is missing left of "Reward" and the Coin/SFL icon does not appear on the yellow label

Screenshot 2024-07-30 at 8 09 48 AM
Screenshot 2024-07-30 at 8 09 59 AM
Screenshot 2024-07-30 at 8 12 30 AM
Screenshot 2024-07-30 at 8 14 03 AM
Screenshot 2024-07-30 at 8 17 25 AM
Screenshot 2024-07-30 at 8 17 49 AM

**Review by adamhannigan — APPROVED** [review]
LGTM ✅

**Pull request merged**
