### PR TITLE
[FIX] Goblin bank deposit description

### LINKED ISSUE #1206: [CHANGE] Goblin Bank Deposit Description
## How the Feature is Currently Working

Currently, we have a new function for the 'Refresh' button that is to minimize the 'Sync on Chain' method, when depositing items we can now only just do the 'Refresh' button and not have to sync. 

## How the Feature Should Be Changed
So for that reason, there is no need to sync on-chain whenever we deposit an SFL token or item we just simply press the 'Refresh' button. Need to update the description of **point number 6 (for tokens)** and **point number 4 (for items)** in the Goblin Bank for Depositing items or SFL tokens.

### SFL Tokens
**Before**
6. Once the transaction has been completed successfully, open the menu inside Sunflower Land and click "Sync on Chain"

**After**
6. Once the transaction has been completed successfully,  open the menu inside Sunflower Land and click "Refresh" inside the setting.

### SFL Items
**Before**
4. Once the transaction has been completed successfully, open the menu inside Sunflower Land and click "Sync on Chain"

**After**
4. Once the transaction has been completed successfully,  open the menu inside Sunflower Land and click "Refresh" inside the setting.

### PR DESCRIPTION
**Pull request by hujikol**
# Description

Fixes #1206 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# UI Screenshoot
### After

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE], or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by veenhdek** [comment]
Great clarification of process, a couple things:
1. I think it would be clearer to either say [ …click “Settings” -> “Refresh” ] or [ …select “Refresh” under “Settings” ]
2. I believe it read simpler without the “been” thus still saying “Once the transaction has completed”
3. Would recommend to keep punctuation consistent so either we have a period at the end of each step or none of them (currently just your proposed additions to 6 and 4 have a period.
4. Suggestion: in token step 1, add a “the”before [ …“Assets” tab…]

**Comment by hujikol** [comment]
thank you for the review, working on it..

**Review by 0xsunflowerstudios — APPROVED** [review]
Good eye! We definitely missed this. Thanks for the contribution ❤️ 

Great feedback as well @veenhdek 🚀

**Review by adamhannigan — APPROVED** [review]
🏆

**Pull request merged**
