### PR TITLE
[FEAT] Add crops skills images

### PR DESCRIPTION
**Pull request by vitt0**
# Description

I added some images to replace the current placeholder images in the crops skills

Images made by Vitt0c#9483 and Ventin#5150

Before: 
old
After:
new2

Before: 
old2
After:
new1

Small preview:
cultivator
golden_flowers
green_thumb_LE
master_farmer
happy_crop

## Type of change

Please delete options that are not relevant.
- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [X] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [X] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Polysemouse** [comment]
Finally some new icons to distinguish betseen some new skills and legacy skills

**Review by vitt0 — COMMENTED** [review]
I removed the "extra pixels" in this Happy crop and Master farmer

**Comment by Polysemouse** [comment]
@vitt0 try running your images in https://tinypng.com/, it will drasitally reduce the image sizes

**Comment by vitt0** [comment]
> @vitt0 try running your images in https://tinypng.com/, it will drasitally reduce the image sizes

Done, 37% smaller 😄

**Review by adamhannigan — APPROVED** [review]
Nice idea @vitt0 

Thanks for contribution ❤️ This will become available for players automatically when we deploy our next release (ETA 1-2 Days) 👏

**Pull request merged**
