### PR TITLE
[FIX] Wrap farm address in bank

### LINKED ISSUE #351: [BUG] Mobile Copy Button
Reported from Discord, users are having issues with the copy button on mobile.

BUG: Copy shortcut is not showing

DEVICE USED: iPhone

BROWSER USED: Metamask browser

**Includes**

- Wrap text and button on new line
- Make the text selectable normally (without the button). A lot of users like to manually copy and paste to avoid and dodgy scripts that could get run in JS to replace a blockchain address

IMG_0840

### PR DESCRIPTION
**Pull request by kolebjak**
# Description

- Long address is wrapped on both mobile and desktop
- Address is user selectable 

Fixes #351 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Manual testing

sf-351-mobile

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tiffanydys** [comment]
great job 👍
been looking for a solution for this for a while now 😁

**Review by Rofrtd — COMMENTED** [review]
Your best work mate! Welcome to SFL.

**Review by Rofrtd — APPROVED** [review]

**Comment by spencerdezartsmith** [comment]
Welcome friend! I do wonder if we need the full address. I think it would be better to offer the truncated address which is a crypto standard? We have this function already to be able to do this:

```
export const shortAddress = (address: string): string => {
  return `${address.slice(0, 5)}...${address.slice(-4)}`;
};
```

Screen Shot 2022-03-13 at 9 15 19 pm

**Comment by adamhannigan** [comment]
@spencerdezartsmith In this case since it is an address they will be copying I think we should show the entire address. This will help a user double check that an address is correct. 

I always do this when copying addresses using a button just in case some dodgy clipboard code has hijacked the code.

Since it is not their personal metamask address I don't think we need to address the same privacy concerns

**Review by adamhannigan — APPROVED** [review]
Always good to see a familiar face! Welcome to Sunflower Land @kolebjak 🤗 🚀

**Pull request merged**
