### PR TITLE
[FEAT] Adding item remenants on crafting

### PR DESCRIPTION
**Pull request by hujikol**
# Description

Following issue #1214 and community discussion #1218 

This change is to improve the quality of farmers' life when they want to craft some items.
In addition, an update to the quest crafting/ minting modal is not conducted as it will ruin the mysteriousness feel of the quest.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

image

- [x] Local test. 

Known Contributor ToDo's

- [x] Testnet testing. 
- [x] Further Goblin Village UI Inspection

# UI Changes

## Demo
https://user-images.githubusercontent.com/12151051/178996560-ffa20778-c341-4334-8820-569de4a59f77.mp4

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE], or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by j923sneaks** [comment]
Hi there! Just tried on Testnet. Let me know if you need updated evidences 😄 I have not tested all due to lack of items tho

image

image

image

**Comment by veenhdek** [comment]
merged your branch into one of mine and tested the testnet as well, (good work as well @j923sneaks)

Checked the tailor 

Screen Shot 2022-07-15 at 1 52 14 PM

I tried to figure out how to give myself wood to test the change to white but i think because i'm farm linked now I would have to earn it the old fashioned way haha.

Looks good overall, I would take it to a full pull request - "request review" now @hujikol so the core team can check it out!

**Comment by Demonbane18** [comment]
well played guys

**Review by adamhannigan — CHANGES_REQUESTED** [review]
Awesome idea! This will definitely help players when saving up to craft items.

We will need to limit the decimal places of the resources to prevent some long running text. I would suggest limiting it to 1 decimal place.

We also have the extreme case of items that require 1000-10000 resources. I played around on a Pixel 5 layout and found it overflows a little. Do you have any ideas how we can present this text so it doesn't overflow?


Screen Shot 2022-07-19 at 10 32 32 am

Screen Shot 2022-07-19 at 10 31 40 am

**Comment by adamhannigan** [comment]
@hujikol For language consistency, I feel we should use the whole numbers. We wouldn't want a non native speaker of a given language misinterpreting the prices 😅 

I'm not sure what would look good here, breaking onto a new line won't be amazing but since it is only for a couple of cases it could work

**Comment by adamhannigan** [comment]
@hujikol Number 1 looks nicer 🤗 

The extra react hook adds a bit of overhead for a UI purpose. Is it possible to achieve a same effect using multiple `<span>` elements that wrap onto new lines?

E.g. `<span>99000</span><span>/</span></span>10000</span>`

**Comment by hujikol** [comment]
Got them in proper flex and span now 😄 

<image src="https://user-images.githubusercontent.com/12151051/180129342-faa26f83-0e12-439d-892b-1daae0acac6e.png" width="360" >

> sorry for the complexity I added in the first place, still learning this react thing 😅 .

## Testing Result
<image src="https://user-images.githubusercontent.com/12151051/180130032-5462ed0f-6978-436e-ae8f-b01315b52b8f.png" width="480" >

**Review by adamhannigan — CHANGES_REQUESTED** [review]
Screen Shot 2022-07-21 at 2 35 33 pm

Running on testnet I get some strange behaviour at the kitchen. I have got 800 pumpkins but it isn't showing the required amount

**Comment by hujikol** [comment]
I'm sorry, it was my mistake, there wasn't any return statement before, should be good now.

**Review by adamhannigan — APPROVED** [review]
Outstanding work! Apologies for the delay on the review.

This is a huge UX improvement, this change will help so many people 🤗

**Comment by Q4FOIL** [comment]
❤️

**Pull request merged**
