### PR TITLE
[CHORE] Enable withdraw of merch and few other wearables.

### PR DESCRIPTION
**Pull request by AzaroQL**
# Description

Enable withdraw of deco wearables:

- Merch wearables (merch store is closed)
- Unicorn horn (event was finished a while ago)
- Companion Cap (it was given out during YGG event stream)
- Ugly Christmas Sweater (it was given out to user wallets, not farms)

Requires BE changes.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Manual test + yarn test

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by adamhannigan** [comment]
Good spot 👍 @AzaroQL 

On the merch items, just waiting to see the plan from Harry's side and whether these will be distributed again.

The `Companion Cap` is the free Discord gift - I think you meant the `Parsnip Horns` 👌

**Comment by AzaroQL** [comment]
Updated Companion Cap to be unwithdrawable.

PS: In my case its really hard to find needed wearable in the list when I want to equip it. Having option to withdraw or stash undesired items would be great.

**Comment by adamhannigan** [comment]
Agreed @AzaroQL There are a few initiatives to redesign the equipping flow. @spencerdezartsmith has a few ideas around this 👍 

It will be helpful especially when clothing multiple Bumpkins

**Review by adamhannigan — APPROVED** [review]
LGTM ✅ 

An update from our side: Unfortunately there were some issues with the merchandise provider and we are still in the process of refunds for people who did not receive the merch 😢 

Until we can rectify the situation, we will keep the merch non with-drawable 👍

**Pull request merged**
