### PR TITLE
[FEAT] add Egg Collected activity

### PR DESCRIPTION
**Pull request by Rofrtd**
# Description

This PR adds the Collected Egg activity to the action

Fixes #issue

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by adamhannigan — APPROVED** [review]
LGTM

**Comment by therocco** [comment]
@Rofrtd @adamhannigan There might possibly be a bug in this code. If the user has a multiplier from having any of the chicken boost multipliers the analytics only get counted as 1 egg collected. For instance I have a 2.3 multiplier on my eggs collected on my farm. Since this feature launched it says I collected 90 eggs but in reality I collected 207 eggs.

**Comment by brian-man** [comment]
> @Rofrtd @adamhannigan There might possibly be a bug in this code. If the user has a multiplier from having any of the chicken boost multipliers the analytics only get counted as 1 egg collected. For instance I have a 2.3 multiplier on my eggs collected on my farm. Since this feature launched it says I collected 90 eggs but in reality I collected 207 eggs.

The boosts you are talking about affect yields.

All references to "harvests" in the game refer to collecting from nodes -- the collection (click), not the product.

It's by design to only count 1 for each harvest, ignoring your yield boosts.

**Comment by therocco** [comment]
@brian-man got it. Thank you for the explination! :raised_hands:

**Pull request merged**
