### PR TITLE
[FEAT] Reset Bumpkin Skill Points

### PR DESCRIPTION
**Pull request by DeMouraZ**
# Description

Feature for players to reset their bumpkin skills points. 

Although there is still a long road ahead for this feature to be implemented on the roadmap, I wanted to start with the first version.

The first version because of the comments I've read, multiple users have a different approach to this.

Some of them are:
- Have a time between resets.
- Increase the payment for every reset, for example start with 100 SFL and increase 100 SFL each time (just an example).
- Reset Skills by Skill Tree , instead of my version that reset them all at once.

All have the same goal, that players won't abuse from the reseting the bumpkin skill points.

Having the changes above or not, some UI/UX could be changed as well, for example Reset Skill button being on the top right of the modal could be a better fit.

https://user-images.githubusercontent.com/108200178/213952409-9e5d4245-13fb-42c1-80a8-6edb7126a693.mp4

About my code, I will just say that I'm ready to take in the comments and please do!

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested manually

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by adamhannigan** [comment]
Love the initiative @DeMouraZ 👏 

There is a significant amount of backend and smart contract work that we will need to do for burning skills + business logic involved.

As per our roadmap, we've got a few other key bugs and features that are being worked on before we can implement the skill reset logic

We will use this PR as a foundation for the UI changes, but won't be able to merge this in until the architecture & API work will be performed. 

This is just to give you a heads up that the PR will remain stagnant until the team can implement these backend changes.

**Comment by xSubZero** [comment]
That looks very good, congratulations on the development and code!

NICE!!

**Comment by adamhannigan** [comment]
@DeMouraZ  I noticed that the skills do not reset when the button is pressed.

Is the purpose of this PR to implement the functionality or to provide a suggestion for how the UI flow could work?

**Comment by DeMouraZ** [comment]
Thanks for your input @adamhannigan , it's supposed to reset the skills.
I'm might have done something on the last commit that broke it. Working on it to make sure it will reset skills.

**Comment by DeMouraZ** [comment]
Can you please try again @adamhannigan , sorry for inconvenience should have been working.

**Comment by varrt** [comment]
I think the good idea was be reset skills points by drink potion, not just click on button in some modal.

**Comment by DeMouraZ** [comment]
Liked your suggestion @varrt , like I said , that is the first version of something that can be changed to better suite UI/UX aspects of the game.

**Comment by adamhannigan** [comment]
@DeMouraZ Gotcha, it's now working 👍 

When it comes to the game design balance, have you though about specific numbers for:

1. Cooldown between skill resets?
2. How much SFL players should burn?

We would be interested your thoughts on what these recommended values should be 🙏

**Comment by DeMouraZ** [comment]
For all the discussions I've seen this reset skill points feature left people very divided. 

From one side people who though and picked the right strategy may feel that this shouldn't happen, the others would like an opportunity to rethink their strategy. IMO the fair needs to be something in the middle, so...

       1. The cooldown should be around 3 months, this feature can't be abused. Also gives time for the team to develop new skills or upgrade old ones, clearly changing the strategy for some. 
       2. They should burn alot from their mistakes 😆 something between 100 to 300 SFL should be fair.
       
I know, because I though of it myself , that with this feature you can change your strategy completely and gain a lot from it. For example, I don't have the last two skills of Cooking, if this feature was somehow cheap or easy I would get Curer skill just to feed my bumpkin with deli goods, gain those 15% plus from it and reset my skill points.

So there are players that made the mistake of choosing a skill or that skill wouldn't perform like they though because there are no percentages available to the players previously which is understandable from them to want the feature but there is strategies like the one stated above that should be notice aswell.

Glad it worked @adamhannigan 👌

**Comment by diasfigor** [comment]
Very good. Thank you for this modification. It will help a lot if we change our strategy in the game. **SunFlower Forever!!**

**Comment by spencerdezartsmith** [comment]
Thank you so much for this submission. This piece will require a lot of backend work. We are going to close this PR but will definitely refer back to it for inspiration once we get to this piece of work.

**Pull request closed without merging**
