### PR TITLE
[FEAT] Crafting Timer

### PR DESCRIPTION
**Pull request by adamhannigan**
# Description

This PR includes a crafting timer progress bar and also shows the time it will take to craft. The aim of this is to give them more visibility over how much time (and how much time exactly left) for the item to be crafted.

Screen Shot 2022-05-07 at 2 35 30 pm
Screen Shot 2022-05-07 at 2 35 22 pm

## Type of change

- [X] New feature (non-breaking change which adds functionality)
# Checklist:

- [X] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [X] Screenshot if it includes any UI changes
- [X] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by spencerdezartsmith** [comment]
Looks great. Would you be able to add `mb-2` the where its says `3 days`. So it adds equal space between 3 days and the progress bar?

Screen Shot 2022-05-07 at 3 16 24 pm

**Comment by Pranav-yadav** [comment]
Also, by any chance can we make the Progress bar *a little bit* wider (in length)..

**Comment by adamhannigan** [comment]
Screen Shot 2022-05-08 at 10 09 06 am

@spencerdezartsmith @Pranav-yadav Thanks for the feedback.

The Progress Bar component is used in quite a few in-game locations and hence the standard padding is quite condensed. @spencerdezartsmith I've taken the approach of changing the text above instead to map closely to the bar. Let me know what you think 🤗 

Unfortunately when the progress bar is wider it looks heavily distorted due to the pixellated effect. I agree it would look better, but we will need to design some custom progress bars + CSS for these cases. For the scope of this PR I have not taken on this task.

**Comment by adamhannigan** [comment]
Closing PR was git history issue

**Pull request closed without merging**
