### PR TITLE
[FIX] EGG HOARDING LIMIT FROM 60 TO 100

### PR DESCRIPTION
**Pull request by mGranTY**
# Description

As the title suggest, this PR changed the Hoarder limit from 60 to 100 to match the blockchain sessions values

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by TheDcol** [comment]
Is it possible to increase hoard limit by the amount of hen houses you have installed on land?

Just thinking what will happen when we have 4 hen houses.. someone with all boosts will gather 144 eggs every 34 hours

Right now it's 72 eggs every 34 hours with 2 hen houses

**Comment by Polysemouse** [comment]
Another suggestion is to modify the backend to return the sync limit, so they can be dynamic and don't have to be set on the frontend

**Comment by mGranTY** [comment]
> Another suggestion is to modify the backend to return the sync limit, so they can be dynamic and don't have to be set on the frontend

@Polysemouse we can fetch the limits directly from the blockchain and put them inside the ProcessEvent function. If we want a Dynamic limit we would need to remove the limits from the blockchain and set them on the backend or change the way blockchain limits work inside the session contract.

**Comment by Polysemouse** [comment]
@mGranTY I think the limit on the blockchain is still needed in case someone found a bug and mints billions of iron pickaxes in 1 transaction.  Perhaps the dynamic limit can be implemented in the backend and the blockchain limit serves only as the humanly possible limit

**Comment by Polysemouse** [comment]
@mGranTY personally I think we should at least double the egg limit (to 120) temporary as we have double the number of hen houses

**Comment by mGranTY** [comment]
> @mGranTY personally I think we should at least double the egg limit (to 120) temporary as we have double the number of hen houses

@Polysemouse i agree with you, this PR is just to make the numbers match, if a core devs appear here, please change the limit to 120 😂

**Review by spencerdezartsmith — APPROVED** [review]
💯

**Pull request merged**
