### PR TITLE
[FEAT] Abstract Settings ⚙️ 🔉 🔇 

### LINKED ISSUE #547: In Game Sounds
Can we please enable the ability from the menu to mute in game sound effects and in game music independently. Also to have a volume control for both sources so users can determine the levels they prefer.

### PR DESCRIPTION
**Pull request by Pranav-yadav**
# Description
## Abstract Settings ⚙️ 🔉 🔇 🚀 
Currently refreshing the browser resets the SFX ON-OFF and Music Playing-Paused states 😔. Using this feature your choice ON/OFF is **Stored in the browser's local storage** 😊 

So, when you login into the game next time `you DO NOT have to turn it ON/OFF again` 😄 

In short, your setting's (ON/OFF) persist even after the browser refresh. 😇 

### Includes
- [x] Persistent Storage for volume Settings, includes below prop's;
  - [x] `isBgMusicPaused`
  - [x] `isSfxMuted`
- [x] `audioPlayer` refactor for **Background Music Pause / Play**  *(stores in `localStorage`)*
- [x] Toggle button to (mute/unmute) **SFX ON / OFF**

**PS:** *No new deps are added* 😎

Closes #547

### Removes
- Removed the temporary *(non-persistent)* mute/unmute button from `audioPlayer`

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
## Screenshots
- Kept only SFX toggle button inside Settings and,
image
image

- Store `isBgMusicPaused` state in localStorage through `audioPlayer`
image
image

and, passing
- `yarn test`
- `yarn tsc`
- `yarn format`

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Pranav-yadav** [comment]
*Ignore* the the number of commits, those are because of extra over powered volume controls *to be used in future*. 🚀 

Ready for review 😄

**Comment by JCtapuk** [comment]
option stores in localStorage or I have to constantly turn it off every time I enter the game!

**Comment by Pranav-yadav** [comment]
> option stores in localStorage or I have to constantly turn it off every time I enter the game!

Obviously it stores settings in your Browser's Local Storage. You don't have to turn it OFF/ON every time you login into game. 😄

**Comment by Pranav-yadav** [comment]
@Rofrtd will look into the re-rendering issue.

About, completely disabling the Audio player - as you suggested let's only store the pause state in localstorage.. 👍

**Comment by Pranav-yadav** [comment]
@Rofrtd ready for review..
- fixed re-render issue
- reverted completely disable music player
- switched two different key-value pairs for SFX and music-paused states in localStorage

**Comment by Pranav-yadav** [comment]
@Rofrtd I guess you missed the above comment. 🙂

**Comment by Pranav-yadav** [comment]
@Rofrtd have u reviewed?

@adamhannigan

**Comment by Rofrtd** [comment]
Hi @Pranav-yadav what is the purpose for this over powered implementation?
What is the "future use" you think we'll have?

As at the moment is basically doing the same thing as before and adding the paused/playing persistence to localStorage.

**Comment by Pranav-yadav** [comment]
Hey @Rofrtd  !
Looks like finally you got a time 😉 to review.. Jk

The fact is, this implementations are reviewed by all three of you.. Over the period of time...
And, the common factor was to keep it simple and abstract...


The OP controls were implemented to provide (future use-case) players more controls over the  SFX (separate Actions  + modals opening)...


I know there is no need of these controls right now.. I'll revert all of those OP controls 🙂..


As the game progresses we'll see what is the the feedback of players and if they want these controls we'll add afterwards.. 👍


Side Note: The OP controls `does NOT contain Logic Bombs`  😂😅.. (obvio. it's not their purpose)

Now, I'll have to resolve all the conflicts 😏

**Comment by Pranav-yadav** [comment]
@Rofrtd Done mate !
- reverted OP controls.. 

Do review and merge..
PS: Might be the last PR of this month as I'll be NA cause of exams..

**Comment by adamhannigan** [comment]
@Pranav-yadav Love the initiative mate 👏 

For now we are focussing our attention on a few of the upcoming game features and are putting a hold on large UI features getting added. This is to prevent application bloat and less items the team will need to maintain. The aim is to try free up as much time over the next 2-3 months so we can launch some amazing features 🤗

**Pull request closed without merging**
