### PR TITLE
[FIX] Seed Timer Seconds Unit

### PR DESCRIPTION
**Pull request by j923sneaks**
# Description

This PR fixes the bugs found in testnet: >1min crops show 1min to 0 sec intervals for the whole duration; Timers in Seed modal are all 0sec.

https://user-images.githubusercontent.com/89294757/159820174-27188475-72af-498b-af1b-f962b55d3e85.mp4

modal-before

Fixes #issue

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Manual testing using `INITIAL_FARM`

Seed modal

modal-after

Progress bars (Cauli, Potato, Sunflower)

progress-bar-after

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tiffanydys** [comment]
Hey nice catch. Thanks for the fix! 😄

**Comment by na66ime** [comment]
Hey, imo it's better to show type in hh:mm:ss format 
For Sunflowers it will be sth like this 00:00:59 and starts decreasing 
For other crops such as Cauliflowers will be 08:00:00 then 07:59:59 and keeps decreasing...

**Comment by j923sneaks** [comment]
hi @na66ime this PR only serves as hotfix to the current code. The timer us reused in other things like in the modal, resources, etc so we might need to test them further if the hh:mm:ss should be followed.

**Review by adamhannigan — APPROVED** [review]
Good catch. I was just planting on testnet and noticed this 😅

**Pull request merged**
