### PR TITLE
[FEAT] Wallet `v1` UI 👛 💰 💱 

### PR DESCRIPTION
**Pull request by Pranav-yadav**
# Description
# Wallet
- when player clicks on Balance Panel shown at the right uppermost part of the hud the Wallet modal opens :)

## Includes UI aspects of;
- [x] Add Send Functionality - In-game SFL Tokens Transfers
- [x] Add Buy Functionality - Buy SFL Tokens
- [x] Add Swap Functionality - Swap SFL tokens w/ other ERC-20

Feat ❤️ 

## Sneak Peek 👀 
<details><summary>Screenshots</summary>

</details>

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update 😉 

# How Has This Been Tested?

- Manually
- `yarn test`
- `yarn tsc`

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Pranav-yadav** [comment]
UI Manual Edge Case Test
| Desktop | Mobile |
| - | - |
|image|image|

**Comment by Pranav-yadav** [comment]
@adamhannigan can we give the visual taste of the In-game Wallet to farmers 😄   ?

**Comment by Pranav-yadav** [comment]
@spencerdezartsmith these are initial v1 UI implementations for Wallet feature, do review...

**Comment by adamhannigan** [comment]
@Pranav-yadav Great initiative but we need to put large features like this on park until we can fit it into our roadmap. 

There are a few intricacies we need to design first around the depositing/withdrawing

**Comment by Pranav-yadav** [comment]
> @Pranav-yadav Great initiative but we need to put large features like this on park until we can fit it into our roadmap. 
> 
> There are a few intricacies we need to design first around the depositing/withdrawing

We could've just commented all tabs except the **Balance tab** for now... 😅

No worries 👍

**Pull request closed without merging**
