### PR TITLE
[FIX] for typo

### PR DESCRIPTION
**Pull request by brian-man**

### CODE REVIEW

**Review by eliasSFL — CHANGES_REQUESTED** [review]
Please edit `dictionary.json`, `en.json` should not be touched

**Comment by brian-man** [comment]
> Please edit `dictionary.json`, `en.json` should not be touched

En.json has the typo but dictionary.json has it correct. How do we fix this?
@eliasSFL

**Comment by eliasSFL** [comment]
> > Please edit `dictionary.json`, `en.json` should not be touched
> 
> En.json has the typo but dictionary.json has it correct. How do we fix this?
> @eliasSFL 

@brian-man in this case we can close this PR, one of your other PRs will trigger the translate script to run and it will detect the typo. Besides the en.json is not what the game's text is running on, it's dictionary.json

**Comment by eliasSFL** [comment]
> En.json has the typo but dictionary.json has it correct. How do we fix this?

@brian-man I just checked, the typo is also present in dictionary.json

**Comment by brian-man** [comment]
> > En.json has the typo but dictionary.json has it correct. How do we fix this?
> 
> @brian-man I just checked, the typo is also present in dictionary.json

Weird.  Will recheck.

**Review by adamhannigan — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
