### PR TITLE
[FIX] Expand Barn click and hover to include the building

### PR DESCRIPTION
**Pull request by brian-man**
# Description

Unlike other buildings, the Barn click and hover areas include only the sign but not the building.

The change separates the barn art from the background art and updates the page construction to expand the click and hover areas for the barn. This includes repairing the hole in the background art from removing the barn, which allows for repositioning or resizing the barn if that is desirable in the future.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Locally verified that the art looks pretty close to the original.  The positioning of the sign is slightly different, but I got it as close as I could.

Confirmed on local that the click and hover work for the full building (and the sign as before).

This image shows the hover effect for the barn:
image

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by adamhannigan — COMMENTED** [review]
Looks good to me 😄 

Do we also need the `barn.gif` though?

**Comment by brian-man** [comment]
> Do we also need the `barn.gif` though?

@adamhannigan 
As I was testing, I noticed some sibling art in that directory had both so I created both. I've validated locally that both the gif and png barn renders correctly.  Which do you prefer?  I'm happy to remove the unused one.

**Comment by Rofrtd** [comment]
> ng art i

Nice one, let's keep the png please!

**Comment by brian-man** [comment]
@adamhannigan @Rofrtd
Reverted the GIF commit.

**Comment by Rofrtd** [comment]
> @adamhannigan @Rofrtd Reverted the GIF commit.

Great work, thanks for your contribution. LGTM

**Review by Rofrtd — APPROVED** [review]

**Pull request merged**
