### PR TITLE
[FIX] Flag Supply in Opensea Metadata

### PR DESCRIPTION
**Pull request by tiffanydys**
# Description
Fixes nft supply in Opensea metadata of the following flags:
- Brazilian Flag (`1,000` -> `5,000`)
- Chinese Flag (`1,000` -> `5,000`)
- Indonesian Flag (`1,000` -> `5,000`)
- Philippine Flag (`1,000` -> `5,000`)
- Urkainian Flag (`1,000` -> `5,000`)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
- Can only be tested in Opensea after deployment

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by spencerdezartsmith — APPROVED** [review]
🤩

**Comment by Rofrtd** [comment]
Hi @tiffanydys, thanks for this fix.

@c-py and I just checked the supplies for those flags on the contract and all of them have a 5k supply instead of 4k.
Is it possible to update this PR to match the contract supply?

**Comment by tiffanydys** [comment]
> Hi @tiffanydys, thanks for this fix.
> 
> 
> 
> @c-py and I just checked the supplies for those flags on the contract and all of them have a 5k supply instead of 4k.
> 
> Is it possible to update this PR to match the contract supply?
> 
> 
> 
> 

Oops, sorry. Yeah I'll be pushing the updates for this in a few mins. Thanks! 🙏

**Comment by tiffanydys** [comment]
Hi @Rofrtd and @c-py done! 😄

**Review by Rofrtd — APPROVED** [review]
Awesome work @tiffanydys. 
LGTM 🚀

**Pull request merged**
