### PR TITLE
Wealthy Frog

### PR DESCRIPTION
**Pull request by PANICJD**

### CODE REVIEW

**Comment by PANICJD** [comment]
I created an NFT, this is wealthy frog.

WealthyFrog

Max supply: 20
Price: 200 SFF

Utility: Your plants can be infected with bugs and when harvested you only got the price, example: you waste 0.01 SFF to obtain 0.02 SFF, when harvested if this plant has been infected with bug you only got 0.01 SFF, also this frog performs a harmonious song that can speed all your farm x3.

(The first utility option will become in future, the second is amazing for now)

Description: This beautiful frog will bring you richness making your farm x3 faster.

CONTRACT: https://polygonscan.com/address/0x1e29bae51d5ad0bd5e898bfaaa062be4b612cf58

**Comment by PANICJD** [comment]
PD: I got stucked on this step "Create a new file Farm.sol in Remix IDE and copy the contents fromhttps://github.com/sunflower-farmers/sunflower-farmers/blob/main/src/contracts/Farm.sol
Change to the compiler tab and ensure the compiler version is set to 0.7.6 and click compile"

I got an error and I did not know how to fix it.

**Comment by PANICJD** [comment]
image
 
So beautiful, there will be only 20 pieces of this.

**Comment by PANICJD** [comment]
> > I got an error and I did not know how to fix it.
> 
> Do you have a print?

Yes sir,
image

**Comment by adamhannigan** [comment]
@PANICJD Just a heads up, the documentation is for deploying a standard NFT. If you want to earn the 16% on rewards it needs to use the CommunityCraft.sol method.

We do not yet have mechanisms for this.

**Comment by PANICJD** [comment]
> 

Oh thanks, so what can I do for now?

**Comment by adamhannigan** [comment]
@PANICJD Apologies for the late response, I lot has been happening with V2.

We will release a new guide on how to get your assets in the game.

**Pull request closed without merging**
