### PR TITLE
[FIX] Bud boosts for greenhouse crops

### PR DESCRIPTION
**Pull request by brian-man**
# Description

3 Leaf Clover and Saphiro should be applied to GH crops

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by brian-man** [comment]
I think Saphiro is already being applied on the back-end but 3 Leaf Clover is not.  So back-end needs an update too.

**Comment by eliasSFL** [comment]
> I think Saphiro is already being applied on the back-end but 3 Leaf Clover is not. So back-end needs an update too.

I don't think Saphiro is applied. Cuz if it is Rice and olive should have the same growth time as wheat/radish and kale respectively. But right now it's not the same

**Comment by eliasSFL** [comment]
> I think Saphiro is already being applied on the back-end but 3 Leaf Clover is not. So back-end needs an update too.

@brian-man I don't think Saphiro is applied. Cuz if it is Rice and olive should have the same growth time as wheat/radish and kale respectively. But right now they are not the same

**Review by adamhannigan — APPROVED** [review]
Ooooh great spot! Cheers ❤️

**Pull request merged**
