### PR TITLE
[FEAT] Add Nyon Statue (Decorative Item)

### PR DESCRIPTION
**Pull request by tiffanydys**
# Description
- Added Nyon Statue NFT by the river

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
`yarn test`
Screen Shot 2022-04-12 at 8 02 42 AM
`yarn dev`
Screen Shot 2022-04-12 at 7 35 27 AM
Screen Shot 2022-04-12 at 7 35 34 AM
Screen Shot 2022-04-12 at 7 58 24 AM
Screen Shot 2022-04-12 at 7 57 55 AM

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by adamhannigan** [comment]
@tiffanydys The modal implementation and code looks good 👌 

We need to refine the art a bit more before adding it to the game. It is always subjective, but in this case it feels like it does not match the scheme of the game. A few things I could spot:

- The shading does not follow the same pattern as other objects in the game
- The colours don't seem present in other objects in the game (the gold stands out the most)

**Comment by SrCouve** [comment]
> @tiffanydys The modal implementation and code looks good 👌
> 
> We need to refine the art a bit more before adding it to the game. It is always subjective, but in this case it feels like it does not match the scheme of the game. A few things I could spot:
> 
> * The shading does not follow the same pattern as other objects in the game
> * The colours don't seem present in other objects in the game (the gold stands out the most)
> 
> Ideally we want the art to go through the community proposals - this helps artists curate and pick the best one to add to the game (we have just been a bit busy lately to address this)

I already posted this art as a proposal alone, it was one of the arts that had the most likes and comments on github, the entire color palette was taken directly from other arts in the game itself, I understand that there is a selection process, but I believe it is more personal than communal

image

**Comment by SrCouve** [comment]
changing the palette from golden gold to golden cauliflower:
image
image
image

**Comment by tiffanydys** [comment]
Hi guys, since the art is still ongoing approval I'll close this PR for now. Thanks! 😄

**Pull request closed without merging**
