### PR TITLE
[FEAT] Add Dynamic Bulk Buy Button for Seeds

### PR DESCRIPTION
**Pull request by eliasSFL**
# Description

- Add a Dynamic Bulk Buy Button for Seeds. Amount to bulk buy dynamically changes depending on how close player is to hitting inventory limit
- Modified the Buy 10 Button to a static buy 10 button as the dynamic function is present in the new dynamic buy button as explained above and shown in the screenshots below. This button will disappear when stock<=10 OR difference between inventory amount and inventory limit <=10
- Added a message when bulk buy amount < stock to explain the bulk buy amount

- Bug Fix: Fix behaviour where shop doesn't stop sales at inventory limit, but stop sales when inventory is 1 above inventory limit. For example sunflower seed inventory limit is 1200, but you are able to buy at 1200 but not at 1201. 

## Screenshots
If amount to be bought doesn't go above inventory limit, buys all seeds available
image

If amount to be bought goes above inventory limit, buys only the amount enough to hit inventory limit. Message appears when the amount to be bought is lower than remaining stock
image

When Stock <= 10, Buy 10 Button disappears, bulk buy button adapts to remaining stock left (similar to before except the implementation is different)
image

When difference <= 10, Buy 10 Button disappears, bulk buy button adapts to remaining space to inventory limit
image

Confirmation
image

Mobile View
Screenshot_20240606_191219_Brave

Fixes #issue

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

- Have no seeds in inventory, Bulk Buy button should show all available stock
- Set inventory number such that the difference between inventory amount and inventory limit < remaining stock. Bulk Buy Button should show the difference
- Set remaining stock <= 10. Buy 10 button will disappear and bulk buy button will show the remaining stock
- Set inventory number such that the difference between inventory amount and inventory limit <= to 10. Buy 10 button will disappear and Bulk buy button will show the difference
- If Bulk buy button > 10 it will show a confirmation message. If bulk buy < 10 it will buy that amount without confirmation

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by adamhannigan** [comment]
Nice work @eliasSFL 💪 

Just a few thoughts/questions:

1. Is it necessary to have the Buy All on the tools? We are a click based game and the tapping is quite a natural feel (if only 3-4 times). I feel the tool stocks are quite low where it doesn't become frustrating for players.
2. Do you think we need a confirmation button on Buy all seeds? I wonder if people could accidentlly click a button and buy a lot of seeds 😅

**Comment by eliasSFL** [comment]
> Nice work @eliasSFL 💪
> 
> Just a few thoughts/questions:
> 
> 1. Is it necessary to have the Buy All on the tools? We are a click based game and the tapping is quite a natural feel (if only 3-4 times). I feel the tool stocks are quite low where it doesn't become frustrating for players.
> 2. Do you think we need a confirmation button on Buy all seeds? I wonder if people could accidentally click a button and buy a lot of seeds 😅

@adamhannigan 
1. I was thinking of being consistent with both, but if it's not necessary I can remove it.
2. Yeah maybe that's something I can add in.

**Comment by eliasSFL** [comment]
> Nice work @eliasSFL 💪
> 
> Just a few thoughts/questions:
> 
> 1. Is it necessary to have the Buy All on the tools? We are a click based game and the tapping is quite a natural feel (if only 3-4 times). I feel the tool stocks are quite low where it doesn't become frustrating for players.
> 2. Do you think we need a confirmation button on Buy all seeds? I wonder if people could accidentlly click a button and buy a lot of seeds 😅

@adamhannigan I've made changes based on your comments. You can merge it in once you're okay with it

**Comment by eliasSFL** [comment]
@adamhannigan I've changed the function a little bit to incorporate the inventory limit checks within the functions itself. I also added checks for it as well. Have a look!

**Review by adamhannigan — APPROVED** [review]
Nice work @eliasSFL You have lot of a lot of edge cases and this feels like a smooth solution.

My only concern is around overcomplicating this for new players (i.e. too many buttons).
For now, I've kept the option hidden until they build a Warehouse 👌

**Pull request merged**
