### PR TITLE
[feat] issue #114 show harvestable counter on favicon

### PR DESCRIPTION
**Pull request by avalla**
- added a Context inside Crops component
- added tinycon dependency
- when timer goes to zero increment the counter
- when plant is harvested decrement the counter

### CODE REVIEW

**Comment by avalla** [comment]
Sorry for mess with PRs :(

**Comment by adamhannigan** [comment]
@avalla No judgement here! Git can get confusing sometimes. Is this ready for review?

**Review by adamhannigan — APPROVED** [review]
Looks good to me!

Thanks for contributing. This will help thousands of people I'm sure!

**Comment by avalla** [comment]
I'm just not sure about useCallback, never used before, I suppose that is not very useful in AppIconContext.

BTW there is any other thing that I can do for help?

**Pull request merged**
