### PR TITLE
[FIX] Wheat cake size / Open Sea and other Documentation 

### PR DESCRIPTION
**Pull request by veenhdek**
# Description

Wheat cake was saved in a 12x12 file but off center which caused misalignment in grids.
Current:
Screen Shot 2022-07-28 at 10 02 35 PM

New:
Screen Shot 2022-07-27 at 9 11 57 AM

As the documentation has evolved the links in OS metadata have become stale as i work to update documents I am also updating links to reflect the current or future pages that will be put in.

TODO discovered:
- [ ] remove bonsai from blacksmith items as it is now a salesman item
- [ ] add wicker man to docs after merge (also a salesman item)
     should we add these to Rare/Limited items or the new proposed salesman page, or both?
        if Rare/Limited is it Wicker Man Season 2?
    Link currently references season 2 decor can adjust after we land on the docs modification. 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by adamhannigan** [comment]
@veenhdek Awesome work, Is this ready for review?

**Comment by veenhdek** [comment]
@adamhannigan not quite, should be able to finish the last pieces in about 12 hours (8/2 AM US time). I need to add salesman docs link and clean up the rest of the OS markdowns links. Are we considering Wicker Man season 2 for Rare and Limited items?

**Comment by adamhannigan** [comment]
No worries. @veenhdek That is a good question about which season it falls into. We haven't exactly thought about the Salesman and the seasons. What do you think is best?

**Comment by veenhdek** [comment]
Didn't add it to docs yet but inserted a link for season 2 decor that we can edit later. I could also see us just adding a separate section to Rare and Limited just for salesman items, unsure... I'll propose something to GitBooks tomorrow 😄

**Review by adamhannigan — APPROVED** [review]
Looks good to me! Great addition 👏

**Pull request merged**
