### PR TITLE
[WIP] Testing support for offline farms

### PR DESCRIPTION
**Pull request by brian-man**
# Description

Adds infrastructure for local farm testing.

Changing the `INITIAL_BUMPKIN_LEVEL` to higher than 1 will automatically apply all unlocked expansions and place available stone, iron, and gold nodes.

This infrastructure was used for validation of #3209.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by brian-man** [comment]
For this supporting change:
- Automatically place all available stone, iron, and gold nodes in `INITIAL_RESOURCES` based on `INITIAL_BUMPKIN_LEVEL`.

Here are the 3 most interesting `INITIAL_BUMPKIN_LEVEL` layouts:
image
image
image

**Review by adamhannigan — APPROVED** [review]
LGTM ✅ 

Are the changes to `landData.ts` needed? We are doing a lot of onboarding work at the moment and need the layout to match exactly how new players enter the game. If not needed, I can revert before merging in 👍

**Comment by brian-man** [comment]
> LGTM ✅
> 
> Are the changes to `landData.ts` needed? We are doing a lot of onboarding work at the moment and need the layout to match exactly how new players enter the game. If not needed, I can revert before merging in 👍

#3209 applies the fix.  This PR is now morphing into just the testing infrastructure improvement.

**Review by adamhannigan — APPROVED** [review]
LGTM 👌

**Pull request merged**
