### PR TITLE
[FEAT] Support up to level 40

### PR DESCRIPTION
**Pull request by adamhannigan**
# Description

Add an additional 10 levels for advanced players. There will be 3 players who have already reached the level 40.

On average, it should take a player 2 weeks to go from level 39 to 40.

### CODE REVIEW

**Review by c-py — APPROVED** [review]
LGTM!

**Review by spencerdezartsmith — APPROVED** [review]
🚀

**Comment by veenhdek** [comment]
> LGTM! We will need some more skills soon 😁

🫐🍎🍊

**Comment by doggy1201happy** [comment]
Level 40 has been opened, in order to upgrade quickly, can the cake making time be shortened.

**Comment by DeshFarm** [comment]
Quais niveis que ganha ponto de SKILL?

**Pull request merged**
