### PR TITLE
[FIX] Fixing snow kingdom illegal access.

### PR DESCRIPTION
**Pull request by HBandesh**
# Description

The players were able to access the snow kingdom without having required level. 

Fixes #issue

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by spencerdezartsmith — CHANGES_REQUESTED** [review]
Nice one. I can still actually load the route it just doesn't show me the map if I don't have the correct level.

I think a better UX would be to redirect back to `/land` if I am not allowed. Otherwise I am just stuck there and need to use the browser back button to get back to land.

**Comment by HBandesh** [comment]
> Nice one. I can still actually load the route it just doesn't show me the map if I don't have the correct level.
> 
> I think a better UX would be to redirect back to `/land` if I am not allowed. Otherwise I am just stuck there and need to use the browser back button to get back to land.
> 
> Screen Shot 2022-12-02 at 12 36 01 pm

Actually, this is what currently happens for other islands like treasure island, stone heaver etc. As far as I remember from my conversation with Adam, it is done to give a reflection that they have landed in the middle of nowhere by accessing that URL. But I understand your point that the user is left with no feedback or action.

I tried force redirecting the user back to land but I guess the better UI would be to show the user and modal give a CTA to travel back home. Which is what I have implemented now. This will work on all the gibberish URL's as well.
image

**Comment by spencerdezartsmith** [comment]
> > Nice one. I can still actually load the route it just doesn't show me the map if I don't have the correct level.
> > I think a better UX would be to redirect back to `/land` if I am not allowed. Otherwise I am just stuck there and need to use the browser back button to get back to land.
> > Screen Shot 2022-12-02 at 12 36 01 pm
> 
> Actually, this is what currently happens for other islands like treasure island, stone heaver etc. As far as I remember from my conversation with Adam, it is done to give a reflection that they have landed in the middle of nowhere by accessing that URL. But I understand your point that the user is left with no feedback or action.
> 
> I tried force redirecting the user back to land but I guess the better UI would be to show the user and modal give a CTA to travel back home. Which is what I have implemented now. This will work on all the gibberish URL's as well. image

Yeah this makes sense. Can we change the wording to just say `You have landed in the middle of nowhere!`? Also can we align the modal padding with the standard. Here is an example. I believe there is no padding around the button but everything else has `p-2`. After that we're good to go 🚀  
Screen Shot 2022-12-05 at 2 27 51 pm

**Review by spencerdezartsmith — APPROVED** [review]
Approving for now. Just need to align the styling then you can merge. Awesome job!

**Pull request merged**
