### PR TITLE
[FEAT] Skill Tree lock-unlock

### PR DESCRIPTION
**Pull request by jcads**
# Description

Mute the panel colors of each locked skill. Doing this gives emphasis to unlocked skills and can give players a sense of accomplishment when unlocking a new skill.

Also, I changed the bg-color of the skill level indicator for Gathering. Let me know your thoughts on this one

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

manually

image

image

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Z1kou** [comment]
@jcads I love this idea!  is there  any chance of further upgrading this by reducing the saturation more and or even adding a lock on screen, as a player I don't think dampening the colors is enough to show Something is unavailable!

**Comment by jcads** [comment]
@Z1kou yes we can reduce the saturation more.

I also initially had thought of adding a lock but that would require additional art. Where do you think the best placecment of the lock should be? I was thinking, a) beside the skill name (**Lumberjack 🔒**); b) replace the locked badge with a lock 🤔

**Comment by adamhannigan** [comment]
lock

 @jcads I created this a while ago but never used it. 

Also, I would suggest playing around with opacity instead of colours. Changing HSV values often makes the color palette inconsistent with the game. To make the UI look beautiful I would suggest one of the following:

1. Using opacity
2. Manually specifying a different colour (perhaps you could use the grey Message component)

**Comment by jcads** [comment]
@adamhannigan 

## **Reduced some of the grayscale values**
image

## **Combination of grayscale, opacity, and a bg-color**

image

image

**Comment by Z1kou** [comment]
@jcads  I think the one you have now is cool, also like its placement! saw the two prototype you have and yet i still feel like they are not enough i would like if it was something like this !
bvzvq8bs9pk31

**Comment by spencerdezartsmith** [comment]
> @adamhannigan
> 
> ## A. **Reduced grayscale values**
> image
> 
> ## B. **Combination of grayscale, opacity, and a bg-color**
> image
> 
> image

What about a combination of grayscale and opacity. I like A. but think some reduced opacity might help. I love the little lock <3

**Comment by adamhannigan** [comment]
@jcads  The palettes still look off in these examples. Unfortunately I can't give the exact colors since I'm not an artist myself. I don't think us devs can give much more feedback how to perfect that 😅 

From my view, I would prefer to have an aesthetically pleasing skill tree preview instead of the unlocking functionality that does not match the color scheme in rest of the game.

If the idea is to "give a sense of accomplishment when achieving them" can we just use the lock icon instead of the displaying the skill icon?

I also think the previous modal does a good job of a sense of accomplishment. They choose the skill and then it appears in their bagdes.

By the way, the background colour of the "Gathering" is much better 👏

**Comment by jcads** [comment]
> If the idea is to "give a sense of accomplishment when achieving them" can we just use the lock icon instead of the displaying the skill icon?

image


image

**Review by adamhannigan — APPROVED** [review]
LGTM 🚀 We went through a lot of iterations but the UI is looking great ❤️

**Pull request merged**
