### PR TITLE
[FEAT] Jigger

### PR DESCRIPTION
**Pull request by adamhannigan**
# Description

This PR introduces the Proof of Humanity that our partner Jigger will implement.

They will assist with on chain forensics and provide anyone who disputes the claim with the ability to 'prove humanity' - this is a lightweight KYC that does not need personal information, just a selfie of the face with AI detection.

It is an uncommon case that a user will go through this flow, since real players should not get identified as bots.

Note: Any API botters that are caught in our anti-bot systems will not get the chance to 'prove humanity'.

Screen Shot 2022-08-26 at 3 12 32 pm
Screen Shot 2022-08-25 at 2 06 57 pm
Screen Shot 2022-08-24 at 6 02 55 pm

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Local dev API

### CODE REVIEW

**Comment by chaoren520** [comment]
good

**Comment by Give7** [comment]
i  like！！！！！！！！！！！！！！！！！

**Review by c-py — APPROVED** [review]
LGTM

**Comment by Night-wezgha** [comment]
Awesome feature, Can't wait to get it implemented in game <3

**Comment by shekhirin** [comment]
lgtm, can't wait!

**Comment by Myth727** [comment]
How long does it take to verify before you can go back to playing and how often will this system ask me to do this roughly? Land #26

**Comment by Myth727** [comment]
I'm missing out on my timed collection of resources at the moment,  I enjoy this game very much and like to giveaway stuff randomly at times. Still not able to play tho as I've been waiting almost 2 hours for it to verify my selfie :)

**Comment by Myth727** [comment]
Screenshot_20220830-164051_MetaMask
Screenshot_20220830-164126_MetaMask



Verified but still can't play and have this message on the UI...

**Comment by Myth727** [comment]
Screenshot_20220830-191406_Firefox

Screenshot_20220830-192521_Firefox


I'm sure it's a mistake as I have not done anything wrong  i even handled the transactions all on discord with a few mods. I had the username Creal.nom... not allowed to use discord anymore lol. But I'm sure you guys will figure this out and fix it. Thank you :)

**Pull request merged**
