### PR TITLE
[WIP-FEAT] MoM Event

### PR DESCRIPTION
**Pull request by ShiningMinions**
# Description

This PR contains the community contributions for the MoM event.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Testing TDB

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by adamhannigan** [comment]
@ShiningMinions Nice work. It is a bit hard to see the actual changes here as it looks like it has included other people's commits.

Could you please rebase onto `feat/spaceship` - this will make it easier to review

**Comment by JacobSobolev** [comment]
@adamhannigan I have tried rebasing this several times but ended up with a screwed code.
this was done kind of sloppy I know. 
Every stage of the event is kind of dependent on the other so we ended up committing everything to one branch and coordinating between us on who is working on what.
Also, there are some time differences between some of us. So it ended that there was rotation on the code implementation between us.

anyway, this current branch is based on the `feat/spaceship` and only me, @ShiningMinions and @jcads added code to it.
for some reason, there are some previous commits on it, but the first commit on this branch was "add assets (d521f53)"

but if we do the PR from `feat/rocket-crash` to the `main` is you can see more clearly the commit history.
image

one more thing, I gave you permission to my fork so if you need to run some test or change anything you can
image

**Comment by j923sneaks** [comment]
hello all. maybe you need to sync `feat/spaceship` from `main` branch on a separate PR first so this one will reflect your MoM changes afterwards. Looks like source branch pulled from `main` then trying to push to feature branch

**Comment by adamhannigan** [comment]
@JacobSobolev For consistency we will need to work off this branch on the repo. I will rebase this onto main and see if it helps out. It is likely since `feat/rocket-crash` branched off of main, instead of this.

To follow atomic commits and ensure code quality, we will only be able to review one ticket at a time in a single PR. This is to ensure quality and no bugs or security concerns arise (what usually happens with large PRs).

**Comment by JacobSobolev** [comment]
@adamhannigan 
I tried, but I encounter the same issues
we changed the code of the Rocket.tsx back and back and forth, all of us.
it is hard to confirm exactly the change that needs to be in order to achieve the current working end result.

I think the best possible thing to do right now is to create another branch with just what you require and we will copy-paste it piece by piece. So, I will create a new branch of the `feat/spaceship` with just the crashed rocket and open a PR for than.
once it is down let me know what you want to see next.

**Comment by JacobSobolev** [comment]
create a PR just for the crashed spaceship #986

**Comment by ShiningMinions** [comment]
@adamhannigan @jcads @JacobSobolev I think I got a successful rebased PR here: https://github.com/sunflower-land/sunflower-land/pull/990

I'm going to close this PR in favor of the new one.

I really think we should try to keep this all in one PR so there's much less confusion. I think this new PR should do the trick.

**Pull request closed without merging**
