### PR TITLE
[CHORE] Ocean animation

### PR DESCRIPTION
**Pull request by JasminDreasond**
This update only changes the webp ocean files to ".gif". This gif is an animated version in the ocean to make the water less static.
I did the ocean animation work myself and I have also made the dark_ocean version available.

### CODE REVIEW

**Comment by elias7905** [comment]
Hey @JasminDreasond Do you think it may cause load strain on slower devices?

**Comment by JasminDreasond** [comment]
> Hey @JasminDreasond Do you think it may cause load strain on slower devices?

I tested it only on my computer. So there is no way for me to answer this question. But if necessary, I can try to create some configuration to activate and deactivate the animation. I just need to know how the game settings values are stored.

**Comment by spencerdezartsmith** [comment]
Hey @JasminDreasond this animation looks great. I think we will need to hold off on merging this one for now due to performance issues. We have a task on our radar to do a toggle for all animations but don't have an eta as yet.

**Comment by JasminDreasond** [comment]
> Hey @JasminDreasond this animation looks great. I think we will need to hold off on merging this one for now due to performance issues. We have a task on our radar to do a toggle for all animations but don't have an eta as yet.

No problem. I have all the patience needed to wait if you are interested in using the animation. :)

**Comment by spencerdezartsmith** [comment]
> > Hey @JasminDreasond this animation looks great. I think we will need to hold off on merging this one for now due to performance issues. We have a task on our radar to do a toggle for all animations but don't have an eta as yet.
> 
> No problem. I have all the patience needed to wait if you are interested in using the animation. :)

I will try to start work on this later this week 💯

**Comment by adamhannigan** [comment]
Thanks for the contribution @JasminDreasond ❤️ 

Some great discussion points here @elias7905 @spencerdezartsmith 

It does appear that a large GIF can cause some performance issues. I would suggest looking into using CSS Transform animations - these are optimised for web performance.

You may be able to produce a similar effect by animating the image using the `skew` property. An example here: https://codepen.io/lihong/pen/yWBZzY

**Comment by adamhannigan** [comment]
Closing for inactivity - would love to see this added into the game! ❤️

**Pull request closed without merging**
