### PR TITLE
[FIX] Optimise sprites. Fix z-index on field rows.

### PR DESCRIPTION
**Pull request by AzaroQL**
# Description

Animation sprites now ~80% smaller in size.

Fixed z-index on field rows so animation isn't displayed below crops from row above.

Do not display animation after failed captcha.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Manual test.

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [n/a] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Polysemouse** [comment]
When the player fails to complete a free seed captcha, the animation is played.  However if the player wait and solve the free seed captcha, the animation is not played

https://user-images.githubusercontent.com/107602352/196025686-6a03e758-95c3-4275-9b46-de8437b452a3.mp4

**Comment by AzaroQL** [comment]
> When the player fails to complete a free seed captcha, the animation is played. However if the player wait and solve the free seed captcha, the animation is not played
> 
>  Sunflower.Land.-.Brave.2022-10-16.01-15-51.mp4

Nice catch, gonna take a look at that!

**Comment by Polysemouse** [comment]
Looks good to me, the latest fix fixed the issue where sound is playing after a failed captcha too!

**Comment by adamhannigan** [comment]
Screen Shot 2022-10-17 at 10 15 03 am

@AzaroQL I believe we can scale these images down by 1/3 width and 1/3 height. Zooming in, it looks like 1 square is actually 3px wide.

Is it possible to scale down the width/height dimensions that are being used?

**Comment by AzaroQL** [comment]
> 

Initially we tried to use 1x size, but animation was blurred after zooming. That's why we went 3x size.
In the code we divide size by 3 and multiply by PIXEL_SCALE, so pixel size should be correct.

Here how it looks like with 1x size:
https://user-images.githubusercontent.com/9656961/196090556-2b3b6db2-7a7f-4df9-82f3-54a5fae051b3.mp4

**Comment by Polysemouse** [comment]
@AzaroQL Try adding `imageRendering: "pixelated"` to the `Spritesheet` style for the animation (in `src\features\farming\crops\components\Field.tsx` and `src\features\island\Plots\Plot.tsx`).  That should fix the pixelated issues and you can reduce the pixel scale back to 1x

**Comment by AzaroQL** [comment]
> @AzaroQL Try adding `imageRendering: "pixelated"` to the `Spritesheet` style for the animation (in `src\features\farming\crops\components\Field.tsx` and `src\features\island\Plots\Plot.tsx`). That should fix the pixelated issues and you can reduce the pixel scale back to 1x image

Oh, thank you! That did the trick!
Will create a commit asap.

**Comment by Polysemouse** [comment]
@AzaroQL some interesting observations here, I wonder why would the file sizes increases with a reduced resolution? (I am not familiar with image compression)
image

**Comment by AzaroQL** [comment]
> @AzaroQL some interesting observations here, I wonder why would the file sizes increases with a reduced resolution? (I am not familiar with image compression) image

Also noticed it, I used online tool to resize sprites.

Already asked Oniel to provide original sprites in 1x size, I think those will be smaller.

**Review by spencerdezartsmith — APPROVED** [review]
LGTM 🚀

**Pull request merged**
