### PR TITLE
[FEAT] Add Workbench Craft 10

### PR DESCRIPTION
**Pull request by hujikol**
# Description

- Add the `Craft 10` button to the workbench, Stemming from the discord beta forum [Link](https://discord.com/channels/880987707214544966/1049277172013080596)
- Fix the `Artist Badge` Tools price on the workbench
- Add additional test case for bulk crafting

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

## Running the test suites
image

## UIX Inspection

https://user-images.githubusercontent.com/12151051/206910368-93c6bcd2-33b7-4d2e-9eff-338b7f33b5dd.mp4

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE], or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Polysemouse** [comment]
We can put the craft 1 / craft 10 buttons side by side, like how we did it for seeds

**Comment by hujikol** [comment]
> We can put the craft 1 / craft 10 buttons side by side, like how we did it for seeds

right, was forget about the new styling

**Comment by hujikol** [comment]
Updated Layout:
image

**Comment by hujikol** [comment]
Please tag me if this PR is ready for review, will merge it first.

**Comment by adamhannigan** [comment]
Hey @hujikol Just letting you know this is pending some back-end changes and hence hasn't been merged in yet.

At the moment this backend change isn't #1 priority so may take a little while 🙏

**Comment by hujikol** [comment]
thankyou for updating, feel free to tag me if this PR is ready to be reviewed 👍🏼

**Comment by Polysemouse** [comment]
I am waiting for this to merge in before I work on other UI refactorings so there won't be any crazy merge conflicts 😆

**Comment by adamhannigan** [comment]
@hujikol I am going to close this for inactivity.

Unfortunately this hasn't been able to get on the backend roadmap and looks unlikely over the next few weeks.

If the time becomes available we will reopen this PR. Thanks for the contribution 🤗

**Comment by MrSnorch** [comment]
> @hujikol I am going to close this for inactivity.
> 
> Unfortunately this hasn't been able to get on the backend roadmap and looks unlikely over the next few weeks.
> 
> If the time becomes available we will reopen this PR. Thanks for the contribution 🤗

What about an artist badge?

**Pull request closed without merging**
