### PR TITLE
[FEAT] Deposit Bumpkin

### PR DESCRIPTION
**Pull request by adamhannigan**
# Description

This PR includes the flows to support depositing a Bumpkin into the game.

https://github.com/sunflower-land/sunflower-land/discussions/2591

The main benefits of this include:

- Instant equip items without a transaction
- Perform Wearable Drops in game = no withdrawal fees
- Require in game items to mint clothing

## Workflow

When a player visits the game, they will need to follow the prompts to deposit their Bumpkin onto the farm. When you deposit a Bumpkin, all of the wearables that are currently equipped will also be sent to the farm.

Players can also deposit wearables from the standard deposit flows.

To withdraw, players go to the Bank and either click "Withdraw Wearables" or "Withdraw Bumpkin". When a Bumpkin is withdrawn, the wearables that are equipped will be sent back to the Bumpkin's Wallet.

A player cannot withdraw any wearables that are currently in use by the Bumpkin. They must first dequip the Bumpkin.

## Screenshots

Ignore the shadow NPCs - this is a local issue

Screen Shot 2023-05-31 at 12 56 02 pm
Screen Shot 2023-05-31 at 12 57 59 pm
Screen Shot 2023-05-31 at 12 57 50 pm
Screen Shot 2023-05-31 at 12 57 42 pm
Screen Shot 2023-05-31 at 1 00 11 pm

Screen Shot 2023-05-31 at 1 00 56 pm

## How to test?

Run locally pointing at the API.

Make sure you include these in your `.env`

```
# Contracts (Testnet)
VITE_ACCOUNT_MINTER_CONTRACT=0xEA2EAa3DD7814D9034B2db40274b353B4b27d3AB
VITE_SESSION_CONTRACT=0x10Af5c3D3316b66f2219717C7AB3F900a9E9f706
VITE_GAME_CONTRACT=0x294223b4dBD0635b0E3354DDD3aaa4792efa590B
VITE_WITHDRAWAL_CONTRACT=0x204d1457B743673095Ba253f447aA0f11669ED47
VITE_DEPOSIT_CONTRACT=0x5228045162c5058A6b19CBC6563B16D231f432Fa
```

**Launch Plan 🚀 **

This is a highly anticipated feature, but due to the architecture changes involved we will need thorough testing. We will likely hijack Testnet for a few days to test this feature properly.

This will also require a lot of notice to current players to prepare them for the change.

### CODE REVIEW

**Comment by spencerdezartsmith** [comment]
Did you try any other layouts for the equip page? I think scrolling those cards might not be the best because people can have many items. I think using the boxes could be good. I don't know that we need the item name but we could have it display on the left side under the bumpkin somehow or give a written description on that side of all the items the bumpkin is wearing. The box could have a top-right check on the items that are equipped or the items could be divided into two sections, equipped and not equipped. 🤔 

Also just want to remind about the buttons being outside of the content padding. It hasn't been updated on the `Withdraw` modal yet. Would love to include that here:

Rule of thumb: 

```
<>
  <div className="padding-here">Content</div>
  <Button></Button>
</>
```

<3

**Comment by adamhannigan** [comment]
@spencerdezartsmith Thanks for the feedback.

I started with a grid, but it became difficult to display the name + boost that an item has. The images aren't great since they are high res pixels so the name + boost felt critical to include to give more context to players what the item is.

I'm not sure what the best approach is here UI wise, my plan was to get a functional version in and iterate on top

**Comment by spencerdezartsmith** [comment]
> @spencerdezartsmith Thanks for the feedback.
> 
> I started with a grid, but it became difficult to display the name + boost that an item has. The images aren't great since they are high res pixels so the name + boost felt critical to include to give more context to players what the item is.
> 
> I'm not sure what the best approach is here UI wise, my plan was to get a functional version in and iterate on top.
> 
> I will try my best with the paddings. It may be a little difficult since those components are nested inside of the parent.

No worries. We can iterate on it for sure.

**Review by c-py — DISMISSED** [review]
Fantastic! All functions working well

**Pull request merged**
