### PR TITLE
[FEAT] New bumpkin profile and experience bar

### PR DESCRIPTION
**Pull request by AzaroQL**
# Description

Our take on bumpkin profile and experience bar for Land Expansion.
Art by Oniel.

In a separate PR I'll add progress bar filling animation. 

https://user-images.githubusercontent.com/9656961/201055051-9f2dc153-f720-4743-8616-3c10b10a4bcf.mp4

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manual test, yarn test.

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by hujikol** [comment]
do you think the circle radius is too big for the entire HUD? seems a bit unbalanced with the other HUD sizing..

**Comment by AzaroQL** [comment]
> 

It was done in that size to preserve pixel size of bumpkin. And since its not a regular button it should be ok to be bigger than settings/inventory and other buttons. Im thinking on adding a save button next to the settings in the same row, so it will look better in terms of overall UI

**Comment by spencerdezartsmith** [comment]
I am giving a comment based purely on the UI as I haven't tested functionality. I love the idea... I would like to see it a little smaller. I appreciate that its showing more details but would we be able to see some smaller options if possible? This is very large on mobile screens.

Also, the rest of the HUD elements have a dark/black border around them. Could we maybe add that in here to bring it more in line?

The white background is also pretty jarring. What if it was a light grey gradient? Something to add depth?

One last question is about the shape around the bumpkin. Its not quite correct. See image below.
Screen Shot 2022-11-11 at 9 47 35 am

**Comment by AzaroQL** [comment]
> I am giving a comment based purely on the UI as I haven't tested functionality. I love the idea... I would like to see it a little smaller. I appreciate that its showing more details but would we be able to see some smaller options if possible? This is very large on mobile screens.
> 
> Also, the rest of the HUD elements have a dark/black border around them. Could we maybe add that in here to bring it more in line?
> 
> The white background is also pretty jarring. What if it was a light grey gradient? Something to add depth?
> 
> One last question is about the shape around the bumpkin. Its not quite correct. See image below. Screen Shot 2022-11-11 at 9 47 35 am

Regarding the size I def can scale it down, but bumpkin pixel size wont match to the game pixel size.
I did that for mobile version tho.
image

Regarding bg, border and shape Ill ask Oniel.

**Comment by spencerdezartsmith** [comment]
> > I am giving a comment based purely on the UI as I haven't tested functionality. I love the idea... I would like to see it a little smaller. I appreciate that its showing more details but would we be able to see some smaller options if possible? This is very large on mobile screens.
> > Also, the rest of the HUD elements have a dark/black border around them. Could we maybe add that in here to bring it more in line?
> > The white background is also pretty jarring. What if it was a light grey gradient? Something to add depth?
> > One last question is about the shape around the bumpkin. Its not quite correct. See image below. Screen Shot 2022-11-11 at 9 47 35 am
> 
> Regarding the size I def can scale it down, but bumpkin pixel size wont match to the game pixel size. I did that for mobile version tho. image
> 
> Regarding bg, border and shape Ill ask Oniel.
> 
> PS: To apply mobile size you need to F5 the page, since we use useMobile hook and it initiates on page load.

I think its fine in this instance to have the bumpkin pixel size not match in this instance. I think the scaled down size

**Comment by AzaroQL** [comment]
New desktop size:
image

New mobile size:
image


Regarding bg, I tried to use bumpkin bg and imo it looks fine, will work on it a bit more tho
image
image
image

**Comment by adamhannigan** [comment]
Screen Shot 2022-11-14 at 4 26 59 pm

@AzaroQL Incredible job 👏 

We are happy to get this into testnet now and any iterations can be made on top of that ❤️ 

I made a few small touch ups:'
- Changed the progress bar background colour (the grey was a bit dull for our aesthetic)
- I removed the end bar that went past the level number - it was a little confusing where the experience bar was meant to end
- The white background was a bit too much and I added some opacity. However, the backgrounds that you tried out do like quite nice - I feel we should go that way 👌

**Comment by hujikol** [comment]
Amazing work! 🚀 
Can't wait to see the other iterations.

**Pull request merged**
