### PR TITLE
[FEAT] Splash-screen tips

### PR DESCRIPTION
**Pull request by ShiningMinions**
# Description

Players are not the best when it comes to locating information, whether it's via discord, the whitepaper, or the knowledge-base website. The community has made it extremely clear that they need better communication systems. Therefore, my philosophy is this: Reduce situations where the player needs to seek-out information altogether. Instead, provide information in such a way that they cannot possibly miss it (I hope).

This feature provides players easy to read tips on the splash-screen. Players are able to scroll through these commonly asked questions (in form of "tips"), discover clear answers, and even be given a direct support link to learn more. The goal of this feature is to hopefully greatly reduce the amount of repeat questions asked in discord. I'm hoping this feature helps scale the game tremendously.

Partially Fixes https://github.com/sunflower-land/sunflower-land/issues/702

https://user-images.githubusercontent.com/103600068/166857488-8edb1ff9-6a04-4b8e-97ef-9397ea851d3d.mp4

## How it Works

- Appears on splashScreen when player is able to login (AKA they see "Let's Farm" button).
- The "tips" will autoplay, meaning they will scroll through next tip every 5 secs automatically.
- See screenshot below for when autoplay will stop:

desktop-regular

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## ❗ IMPORTANT NOTES ❗

- Tips are added manually in `public/tips.json` file. It's **highly** recommended we move this to some sort of other data-stream to better streamline the process. The SFL team will need to decide this, but `tips.json` file can be used for now.

# How Has This Been Tested?

Tested visually. See results and other photos:

test-results

desktop-overflow

mobile-regular

mobile-overflow

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Muddshoe** [comment]
Suggestion:

EDIT: 'Halving is the process of making your SFL more scarcer over time. Collect SFL today!' -> 'Halving is the process of making acquiring SFL harder (and more valuable) over time. Collect SFL today!

ADDITIONAL TIPS: 

1. Generally, the faster the crop grows the more lucrative it is. This isn't counting bonuses or syncing though!
2. Don't forget to sync before interacting with the blockchain.
3. Get rid of those pesky Goblins by tempting them with food from the Kitchen.
4. Represent your country by donning a flag from the Tailor!

**Comment by adamhannigan** [comment]
@ShiningMinions Some great ideas to help with gameplay! My only concern here is around the UI/UX of the feature.

Right now it draws too much attention away from the main action - play the game.

To move forward I would consider reaching out to a UI designer in the channel to design how this could aesthetically fit the game and look more like a secondary action.

**Comment by ShiningMinions** [comment]
@adamhannigan Thanks for the feedback. From a UI/UX standpoint, I absolutely see your point. I will attempt to get some more feedback from the players/devs and get you some new screenshots. I just want to stress that from a utility standpoint, I believe there is an extremely huge demand for a feature like this (from the players, from the mods, and from Steve). Some initial thoughts I have for UI/UX improvements are here:

1. Move this new "Tips" components to the bottom-left of the screen (although won't look much different on mobile 🤔).
2. Going off of @Muddshoe 's feedback, perhaps a new "passive" color-scheme/style should be used to take-away some attention.
3. Consider removing the player sprite so it's less distracting and can take up less space.

**Comment by alvinphoebeartemis** [comment]
Hi @ShiningMinions ☺, why not we put a small button here with a label of "i" icon or "Learn More" label, then once clicked, it will pop-up the tutorial modal so that we can optimize the space. Thank you. 🤗

image

**Comment by ShiningMinions** [comment]
> Hi @ShiningMinions relaxed, why not we put a separate small button here with icon "i" or "Learn More" label, then once clicked, it will pop-up the tutorial modal so that we can optimize the space. Thank you. hugs

@alvinphoebeartemis not a bad UI/UX suggestion, my only fear is this: I don't trust the average player to even click this button in the first place. Just from personal experience dealing with average players in #farmers-chat and interpreting their demands, it seems we really need to almost force-show information like this.

**Comment by spencerdezartsmith** [comment]
I love the idea of trying to give people the information that they are missing straight away but I don't think this is the solution we need. Like @adamhannigan said I think it takes away from the initial game play actions which in itself may add confusion. 

A secondary action may work but I am not sure how many people will use it. I think our challenge is to make all of these pain points more intuitive through our game ui/ux. Clearer in game messaging and more intuitive actions. From my experience and even personal behaviours, people tend not to stop and read what is clearly in front of them. They will only try to seek out the information when they hit a roadblock. 

This could potentially live inside the game as a tips section that could be dismissed/opened at any time?

Once we have this launch out of the way we will really be able to audit these things and see where improvements can be made 🙏🏼

**Comment by ShiningMinions** [comment]
@spencerdezartsmith 

### Thoughts:

Here's the problem I'm having. It's EXTREMELY clear to me that the community is demanding features like these. They are simply demanding better in-game communication (look, just a few hours ago, another in-game communication proposal popped-up: https://github.com/sunflower-land/sunflower-land/issues/803#issuecomment-1119032566). I 100% agree that the UI/UX could probably use some work here. HOWEVER, what I think you guys are really missing here is that the SFL community is desperately wanting a short-solution TODAY for stuff like this. Even if it's not the best, and even if it's not what's going to stick around long term, and even if it eventually gets phased out, it's something I feel the community is simply isn't wanting to wait for.🤷

Several hours ago, before you commented, I got feedback from community in #farmers-chat (please see thread: https://discord.com/channels/880987707214544966/880987707692687381/971848090548047872):

**Comment by ShiningMinions** [comment]
FYI another potential UI/UX version of this:
desktop-round-2

**Comment by ShiningMinions** [comment]
I'm going to put this PR into draft mode until I get another UI to present.

**Comment by ShiningMinions** [comment]
@adamhannigan @spencerdezartsmith - With the help of [Baron](https://github.com/baron/) on discord, I have a new UI proposal for this. If accepted, I will create a new commit, update this PR, and take this PR out of draft mode. Thank you! 😊

desktop-round-6

**Comment by adamhannigan** [comment]
@ShiningMinions This still has a few UI/UX issues we need to iron out. We are going to put this on hold for a bit until we can come up with an elegant way to display these tips in the game - and also identify which types of players and when the tips would be displayed

**Pull request closed without merging**
