### PR TITLE
[FEAT] Zoom in/out mobile

### PR DESCRIPTION
**Pull request by pab3507**
# Description

This feature creates a toggle that allows users on mobile to zoom out to 80%. The main motivation for this feature comes from pain points expressed by users on the discord that it can be difficult to navigate the map on the smaller vertical screen. This becomes particularly annoying when trying to find the shovel thief. 

This change has no dependencies but it does modify the CSS for the Bootstrap modal component so that the backdrop fits the screen after zooming out. The default behavior of the backdrop is to resize after zoom but as it is currently used in the application this would not introduce a change.

This feature also needs a new icon for the zoom in/out toggle. I made one myself for prototyping but the community could probably make one better.

# Screenshots
- Default Zoom:
signal-2022-05-18-190822_001
- 80% Zoom:
signal-2022-05-18-190822_002
- Default Zoom on Modal:
signal-2022-05-18-190822_003
- 80% Zoom on Modal:
signal-2022-05-18-190822_004

## Type of change
- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

This has been tested locally on both chrome and the metamask mobile browser with manual user testing. One potential concern is that zooming out could affect touch targets fixed on the grid but I could not find such an instance with the touch targets available on the dev instance

# Checklist:

- [X] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [X] Screenshot if it includes any UI changes
- [X] I have read the contributing guidelines and agree to the T&Cs
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Netherzapdos** [comment]
What do you think about these ones? 

minus
zoom

**Comment by pab3507** [comment]
> What do you think about these ones?
> 
> minus zoom

Think they need to be white to match the other HUD elements like the volume up and down and the hamburger icon

**Comment by Netherzapdos** [comment]
> > What do you think about these ones?
> > minus zoom
> 
> Think they need to be white to match the other HUD elements like the volume up and down and the hamburger icon

How about these ones?

minus 1 plus 1

**Comment by tiffanydys** [comment]
Hello there 😄 good initiative with the zoom in and zoom out features. ✌🏻

Just a couple of questions:
1. I see that you've added the zoom icon on the bottom left corner (I'm assuming you haven't connected your local to testnet), how would it look like with a farm number? Currently when you are in your farm in testnet it has a farm number in the bottom left side.
2. I also see that it only displays one button at a time. How does it work if you want to zoom out/zoom in? Would be nice to include a screen recording of it in your PR.

Thank you for your contribution ❤️

**Comment by pab3507** [comment]
> Hello there 😄 good initiative with the zoom in and zoom out features. ✌🏻
> 
> Just a couple of questions:
> 
> 1. I see that you've added the zoom icon on the bottom left corner (I'm assuming you haven't connected your local to testnet), how would it look like with a farm number? Currently when you are in your farm in testnet it has a farm number in the bottom left side.
> 2. I also see that it only displays one button at a time. How does it work if you want to zoom out/zoom in? Would be nice to include a screen recording of it in your PR.
> 
> Thank you for your contribution ❤️

hey, great catch on 1. I am testing on my local network after running yarn dev. How can I test on testnet. What do you think of having the zoom icon next to the music/volume controls?

For 2). I made it a toggle so that why it only shows one icon at a time. When it is at the default zoom it shows the zoom-out icon. When it is at 0.80 zoom it shows the zoom in icon. I made it a toggle because I didnt want to clutter the mobile screen and because the ui might not look good if someone zooms out too much. Let me know what you think of this approach. I'll try to record my screen showing the functionality as well.

**Comment by tiffanydys** [comment]
> How can I test on testnet.

You would need to ask a testnet role from Adam in code-chat.
He often gives it out to people who help others in reviewing PRs/code debugging.

> What do you think of having the zoom icon next to the music/volume controls?

Would be okay for me I think.

> For 2). I made it a toggle so that why it only shows one icon at a time. When it is at the default zoom it shows the zoom-out icon. When it is at 0.80 zoom it shows the zoom in icon. I made it a toggle because I didnt want to clutter the mobile screen and because the ui might not look good if someone zooms out too much. Let me know what you think of this approach. I'll try to record my screen showing the functionality as well.

For this I think it's not that user friendly if the icon just changes instantly. I'm thinking of disabling the other button when it reached the maxed out zoom-in/out function. What do you think?

**Comment by pab3507** [comment]
Demo of the feature with the suggested changes and new icon.

https://user-images.githubusercontent.com/16363534/169715899-40354d82-7c6e-4182-8dfa-50778b51a769.mp4

bug: zoom resets after some time. I think the game might refresh periodically which resets the zoom level to the default. Might need to find a way of making the zoom level persist.

**Comment by adamhannigan** [comment]
@pab3507 Thanks for the contribution ❤️ 

In this case here we won't be adding this functionality. We are trying to keep the application slim so it is quicker to introduce new features - for now, the functionality of adding zoom in/out does not match the maintenance time of this feature.

**Pull request closed without merging**
