### PR TITLE
[FIX] Shovel: Added announcement and OS data.

### PR DESCRIPTION
**Pull request by AzaroQL**
# Description

Added announcement and OS data.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Manual test

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AzaroQL** [comment]
image

**Comment by veenhdek** [comment]
Authored the markdown files and ran the erc1155 script to build the .json files. Built the OpenSea pngs and added them. @AzaroQL its ready for review (announcement time may need adjustment when core devs actually release it) 

@adamhannigan shovel cleanup as requested

**Comment by AzaroQL** [comment]
I would also add link to the docs as required by issue #1219, but docs are yet to be updated with shovel info.

**Review by adamhannigan — APPROVED** [review]
Great work! We will be going live shortly 🚀

**Pull request merged**
