### PR TITLE
[FEAT] Clouds

### LINKED ISSUE #339: [FEAT] Hide areas of map
Sunflower Land will include an awesome NFT land expansion in the future. Users will need to explore hidden parts of the map and unlock them to gain access to new resource and cool things.

The game will implement a 'Fog of war' approach where areas of the map are hidden by a cloud. From the lake downwards will be hidden by a 'mysterious' cloud.

**Includes**

- Hide bottom half of map with cloud
- Display some 'Coming soon..' NFT land expansion text

**Excludes**

- Fixing map UI issues that will be hidden by the cloud

### PR DESCRIPTION
**Pull request by spencerdezartsmith**
# Description
This PR adds clouds to cover parts of the map.

Fixes #339 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
- Run locally
- The clouds are covering to Southern portion of the map

Screen Shot 2022-03-08 at 8 39 46 pm

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Pranav-yadav** [comment]
Looks great @spencerdezartsmith 🚀 

This feat is can be taken as temporary solution to lock the some part of the map. But, I don't get the point of introducing clouds (i.e., covering some part of map with clouds) because, when the player enters the game these clouds will be covering southern part as you said, and at the same time the player will be harvesting crops from predefined fields on map, now this creates **dilemma of perception** 👀

### My Suggestion:
Why can't we use **dense forest**<sup>[1]</sup> to hide/lock that part of the map <-- this wouldn't create perception dilemma.
And, when the player satisfies/meets the requirements to unlock that part it'll be unlocked<sup>[1]</sup>.

[1] (Programmatically) We can just show multiple trees in that area such that, it looks like a dense forest, when locked. And, while unlocking we can remove these trees (or some of the trees <-- this is future scope<sup>[2]</sup> :D), and make the that part (or some part <-- again future scope<sup>[2]</sup>) to player.

[2] If we decide to implement [1], in future we can even make this unlocking more complex in the sense by requiring multiple unlocks i.e., in one go all the part won't be unlocked we can divide this part in multiple locked regions. <-- this would benefit to  attract and keep the players engaged with the game to compete for this unlocks.

What do u think @spencerdezartsmith & @adamhannigan ?

PS: Sorry Spencer for criticizing, tho I know you wouldn't feel that way 😇

**Review by adamhannigan — COMMENTED** [review]
@spencerdezartsmith I feel like our first focus should be on supporting the normal zoom mode instead of the full zoomed-out version.

It would be good if we could get the pixellated effect (maybe a repeating background pattern) that looks more consistent when zoomed in. On mobile it was a bit strange.

Also, the shadow looks a bit off on the cloud (see attached). I think it is the blurring that does not render well at scale. I would suggest removing the shadow from the `png` and just applying a drop-shadow filter on the image. 

Screen Shot 2022-03-08 at 9 55 36 am

**Comment by spencerdezartsmith** [comment]
> Looks great @spencerdezartsmith 🚀
> 
> This feat is can be taken as temporary solution to lock the some part of the map. But, I don't get the point of introducing clouds (i.e., covering some part of map with clouds) because, when the player enters the game these clouds will be covering southern part as you said, and at the same time the player will be harvesting crops from predefined fields on map, now this creates **dilemma of perception** 👀
> 
> ### My Suggestion:
> Why can't we use **dense forest**[1] to hide/lock that part of the map <-- this wouldn't create perception dilemma. And, when the player satisfies/meets the requirements to unlock that part it'll be unlocked[1].
> 
> [1] (Programmatically) We can just show multiple trees in that area such that, it looks like a dense forest, when locked. And, while unlocking we can remove these trees (or some of the trees <-- this is future scope[2] :D), and make the that part (or some part <-- again future scope[2]) to player.
> 
> [2] If we decide to implement [1], in future we can even make this unlocking more complex in the sense by requiring multiple unlocks i.e., in one go all the part won't be unlocked we can divide this part in multiple locked regions. <-- this would benefit to attract and keep the players engaged with the game to compete for this unlocks.
> 
> Also, I'm sure we can utilize the clouds in a better way in the game e.g., we can use them to dynamically rain after some interval of time (in days/weeks).
> 
> What do u think @spencerdezartsmith & @adamhannigan ?
> 
> PS: Sorry Spencer for criticizing, tho I know you wouldn't feel that way 😇

Hahaha I don't take it personally mate so that's all good. I think we're keen to stick with the clouds in this instance. I have put up an art request so we will see if we can get some more contributions. I didn't make these clouds a community member did. They struggled to keep the pixels to scale. We will see if anyone else can sort it out.

**Comment by Pranav-yadav** [comment]
> Looks great @spencerdezartsmith 🚀
> 
> This feat is can be taken as temporary solution to lock the some part of the map. But, I don't get the point of introducing clouds (i.e., covering some part of map with clouds) because, when the player enters the game these clouds will be covering southern part as you said, and at the same time the player will be harvesting crops from predefined fields on map, now this creates **dilemma of perception** 👀
> 
> ### My Suggestion:
> Why can't we use **dense forest**[1] to hide/lock that part of the map <-- this wouldn't create perception dilemma. And, when the player satisfies/meets the requirements to unlock that part it'll be unlocked[1].
> 
> [1] (Programmatically) We can just show multiple trees in that area such that, it looks like a dense forest, when locked. And, while unlocking we can remove these trees (or some of the trees <-- this is future scope[2] :D), and make the that part (or some part <-- again future scope[2]) to player.
> 
> [2] If we decide to implement [1], in future we can even make this unlocking more complex in the sense by requiring multiple unlocks i.e., in one go all the part won't be unlocked we can divide this part in multiple locked regions. <-- this would benefit to attract and keep the players engaged with the game to compete for this unlocks.
> 
> Also, I'm sure we can utilize the clouds in a better way in the game e.g., we can use them to dynamically rain after some interval of time (in days/weeks).
> 
> What do u think @spencerdezartsmith & @adamhannigan ?
> 
> PS: Sorry Spencer for criticizing, tho I know you wouldn't feel that way 😇

@adamhannigan seems you missed this 👆 one :)

**Pull request closed without merging**
