### PR TITLE
[FEAT] Island Travel Fixes

### PR DESCRIPTION
**Pull request by HBandesh**
# Description

In this PR, I have added the boat and goblin traveler images. I have also removed the "view into scroll" feature for island travel where the viewport scrolls to boat when you move from one land to another. This was done as we found that it was resulting to bad user experience on the mobile.

We have also added piere to the background image of all the levels.

Helios:
image

Goblin Retreat:
image

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by spencerdezartsmith — CHANGES_REQUESTED** [review]
Code looks good.

Just a problem when testing in Snow Kingdom. The boat/pirate load at the wrong coordinates and they also move when resizing the screen.
Oct-21-2022 11-33-44

Also the issue where the lands aren't centered. It would be good to find what is causing that.

**Comment by Polysemouse** [comment]
It would be nice to ensure the pixel size of all assets to appear the same on the map.

Currently the pixels for the boat looks a bit smaller than that of the base map

**Review by spencerdezartsmith — COMMENTED** [review]
Great. The resizing is fixed which is awesome. One issue is the sizing of the boat. The pixel size is much smaller than the pixels in the rest of the game. This will need to change.
Screen Shot 2022-10-25 at 4 11 34 pm

Also I am not sure if these issue are from this branch but would be good to fix here I think. It would be good to centre the islands and also the background div appears to be way bigger than the background image. That could be whats causing that issue. Not sure. Would you mind looking into that?

**Review by adamhannigan — APPROVED** [review]
LGTM

**Pull request merged**
