### PR TITLE
[FEAT] Add Crow Feather to Garbage Collector

### PR DESCRIPTION
**Pull request by elias7905**
# Description
_This PR will be on draft until the end of the season_

Adds Crow Feather to Garbage Collector
image

Fixes #issue

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by elias7905** [comment]
I'll leave this on draft until the end of the season

**Comment by elias7905** [comment]
I'll leave this PR on Draft until the end of the season

**Comment by elias7905** [comment]
Opening this PR for review in lieu of the end of the season

**Review by adamhannigan — APPROVED** [review]
Backend updates done ✅ 

Thanks!

**Pull request merged**
