### PR TITLE
[FIX] Grub Shop Timer on Mobile

### PR DESCRIPTION
**Pull request by hujikol**
# Description

This PR fixes 
- a flex-wrap issue on a mobile device in the grub shop modal
apparently the timer wrapped in the modal (shown in the before image) and rendered on the bottom right
- Moving the timer on grub shop to the top of the modal in desktop view
- Adjust retreat blacksmith coming soon modal to use PanelCloseButton components

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

### Before

image

image

image

### After

image

image

image

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Polysemouse** [comment]
Perhaps we can change the 6d 13h to 6days 13hours to align the style with other time displays with blue borders

**Review by spencerdezartsmith — CHANGES_REQUESTED** [review]
Screen Shot 2022-12-28 at 1 22 34 pm

This looks good! Just one issue. This isn't centre aligning on the horizontal axis correctly due to a bottom margin on the text.  Just need to fix that and then we will be good to go. 

Feel free to tag me when its fixed!

**Comment by hujikol** [comment]
@spencerdezartsmith its ready to be reviewed again sir..

**Review by spencerdezartsmith — APPROVED** [review]
❤️ Love your attention to detail. Thanks!

**Pull request merged**
