### PR TITLE
[FEAT] Add TIckets to Faction Prizes

### PR DESCRIPTION
**Pull request by c-py**
# Description

- Adds tickets to faction prizes
- Tickets start for the first Pharaoh's Treasure week (Aug 5th)

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

localhost

# Checklist:

- [X] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]

### CODE REVIEW

**Review by adamhannigan — APPROVED** [review]
LGTM ✅

**Comment by brian-man** [comment]
I think adding "pay to win" seasonal tickets is a terrible idea.

**Comment by andrelopes2001** [comment]
I don't know who thought this would be a good idea, but maybe check with the community first.

**Comment by adamhannigan** [comment]
Thanks for your feedback @brian-man & @andrelopes2001 

This was the idea we've mentioned with the community on streams the last 4-5 weeks. This is to be brought in with the removal of Crop RNG

**Pull request merged**
