### PR TITLE
[FIX] Inventory amount added to recipes

### PR DESCRIPTION
**Pull request by the-mentalist**
# Description

Added total inventory amount to recipes panel. This is useful for planning other food items.
Currently, it only shows the amount required but it will be useful to see how much quantity is already present in the basket.

e.g.
image

The logic to display ingredients was repeated in multiple components, hence have created a [separate component](https://github.com/sunflower-land/sunflower-land/pull/1948/files#diff-3afb1a75a1ad5b8307a1303a6dc043519540737839c66bb9126336dccc399ff3) and refactored all the following components (let me know if I have missed any)

Firepit
image

Workbench
image

Exotic
image

Decorations
image

Treasure Island
image

EDIT:
`shortenCount` added
e.g. in the below screenshot the stone quantity is 5029
image
image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Ran tests locally

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by hujikol** [comment]
is this change only intended to change the recipes for crafting food only? because I don't see any difference in the workbench or other shop in helios
image
image


also, have you tried some edge cases when the farmer has a lot of resources, it could be a little challenging to know how many of them, or even it will break the UI itself, 
image

I suggest converting thousand into `K` and millions into `M` like in the basket.
image

**Comment by the-mentalist** [comment]
that's a really good point @hujikol 🙇 
will update those too

**Comment by the-mentalist** [comment]
Pending tasks
- [ ] Add common component for rendering ingredients
- [ ] convert thousand into `K` and millions into `M` (like in the basket)

**Comment by hujikol** [comment]
You can use this function in `src/lib/utils/formatNumber.ts` to format the 'K' and 'M'

**Comment by Polysemouse** [comment]
https://github.com/sunflower-land/sunflower-land/pull/2022 got merged in so there's some merge conflicts.

Personally I would prefer sticking to the long format (5000000/2000) instead of the short format (5m/2000) because of consistency.  We are limiting the display to 1 decimal places so unless players have a few hundred million of a resources, the UI still have space to accommodate the text

**Comment by future2back** [comment]
Waiting for it.

**Comment by the-mentalist** [comment]
Looks this is already covered in #2038, hence closing

**Pull request closed without merging**
