### PR TITLE
[FEAT] Add Kingdom Shop Wearables to Faction Shop

### PR DESCRIPTION
**Pull request by LittleEins**
# Description

This PR Adds Kingdom Shop Wearables to Faction Shop. Buff/Boost will be added on another PR.
image
image

Fixes #issue

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
 run `yarn test buyFactionShopitem.test.ts' 
image

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by eliasSFL** [comment]
image

For the Crown, it probably good to mention that you need the helmet to craft it, and disable it when the helm is equipped on any of the bumpkins
Also the styling here can be improved as seen in screenshot above

**Review by eliasSFL — CHANGES_REQUESTED** [review]
image

For the Crown, it probably good to mention that you need the helmet to craft it, and disable it when the helm is equipped on any of the bumpkins
Also the styling here can be improved as seen in screenshot above

**Review by adamhannigan — CHANGES_REQUESTED** [review]
Great work @LittleEins 👏 

I performed the following testing.

1. Connect to local API
2. Crafted each of the 4 items

I can confirm the helmet was burned 🔥 

Similar to @eliasSFL comment, I found that the UI was missing some information about burning the Helmet.

I attempted to mint the crown, while wearing the helmet and an error got thrown in the console.

I would suggest showing that 1 Crown is required and also show an error message "Helmet is equipped" if currently wearing it.

Screenshot 2024-08-14 at 3 42 53 PM
Screenshot 2024-08-14 at 3 38 39 PM

**Comment by eliasSFL** [comment]
Hey @adamhannigan,
@LittleEins and I have worked on the UI for the Crown and here are some screenshots 


image
image
image

**Review by adamhannigan — APPROVED** [review]
Great work team 👏

**Pull request merged**
