### PR TITLE
[FIX] Quarry interactable area

### PR DESCRIPTION
**Pull request by zh-kai**
# Description

I think the interaction area in the quarry is a bit large, and I've tried to make some adjustments to ensure that users don't get interaction in unexpected areas of the quarry

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Click on the edge of the quarry through the interface to see if interaction is generated.

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by zh-kai** [comment]
Before
image

After
image

**Comment by j923sneaks** [comment]
i wonder if cropping the images themselves resolves the issue and not modify code. preview for `stone_empty.png` has extra space.

image

**Comment by zh-kai** [comment]
> i wonder if cropping the images themselves resolves the issue and not modify code. preview for `stone_empty.png` has extra space.
> 
> image

I think it is necessary to keep the extra space on the `stone_empty.png`.
1. The size of `stone_empty.png` and `stone_drop.png` are the same, so that the stones will be overlapped when the animation is played. 
2. `stone_empty.png` located on the lowest level and is not suitable as an interactive element.

So I added a small interactive area.

**Review by adamhannigan — APPROVED** [review]
Good spot and nice fix 🏆 

Thanks for joining the developer community ❤️ We appreciate the help!

**Comment by adamhannigan** [comment]
@zh-kai Just merged in. This triggers an automatic testnet deployment `https://sunflower-land.com/testnet/`

When the next Github release goes live, your code will go live for all the players! 🚀

**Pull request merged**
