### PR TITLE
[Update] Lint and Format Code Base

### PR DESCRIPTION
**Pull request by JoseRFelix**
## Motivation

Have a defined set of rules for formatting and linting. This will make the codebase easier to maintain and understand. 

## Changes

- Add pretty-quick to format files on pre-commit.
- Lint and format all files. 

## To Do

Check rules about accessibility and make update elements considered violations.

### CODE REVIEW

**Comment by Pranav-yadav** [comment]
Whoaa !! review of this PR is going to take lot of time 😅

> **Suggestion:** Generally one shouldn't submit a PR with code linting and formatting to bigger codebases. As it'll take more time of maintainers to review such PR's (due to lot of files are changes and more additions as well as deletions).(**High Risk**)
> Rather, one should create an issue and suggest changes there. So, maintainers can themselves make changes in lint & formatting settings. (**No Risk** at all)

PS: Each open source contribution is appreciated by maintainers 😊

**Comment by jesussource** [comment]
check the dependencies I think something broke

$ yarn start
yarn run v1.22.17
$ react-scripts start

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "eslint": "^6.6.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of eslint was detected higher up in the tree:

  C:\Users\jesus\Desktop\farmers-update-linting-and-formatting\node_modules\eslint (version: 7.32.0)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "eslint" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if C:\Users\Guillermo\Desktop\farmers-update-linting-and-formatting\node_modules\eslint is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls eslint in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed eslint.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by JoseRFelix** [comment]
> Whoaa !! review of this PR is going to take lot of time sweat_smile
> 
> > **Suggestion:** Generally one shouldn't submit a PR with code linting and formatting to bigger codebases. As it'll take more time of maintainers to review such PR's (due to lot of files are changes and more additions as well as deletions).(**High Risk**)
> > Rather, one should create an issue and suggest changes there. So, maintainers can themselves make changes in lint & formatting settings. (**No Risk** at all)
> 
> PS: Each open source contribution is appreciated by maintainers blush

While I'll agree that reviewing a lot of lines can be tedious. These additions are mostly from the lock file and the import sorting. Almost no changes were made to the underlying code itself. On the other hand, if there's a risk of regression then it means the code base needs to have more tests (currently has 0). I guess that opens up a great opportunity to open a new issue.

**Comment by Pranav-yadav** [comment]
> On the other hand, if there's a risk of regression then it means the code base needs to have more tests (currently has 0).

I completely agree. 👍

---

## 🧪 This project needs _Tests_
What do you think, @adamhannigan @spencerdezartsmith @chris-calo @Rofrtd @j923sneaks  **?**

**Comment by Rofrtd** [comment]
> 

Yes, I agree we do need tests!

**Comment by adamhannigan** [comment]
@jesussource This is great work! Apologies for the late response, I've been catching up on a lot of design/admin work.

The team is currently refactoring the Sunflower Land project and will update this repo within a week or so.

The aim will be to introduce these aspects into the code base - We will need to hold off until the new code structure is merged in

**Comment by jesussource** [comment]
hello @adamhannigan  the credits are for @JoseRFelix  I did nothing I just reported a problem, I'm still glad to know that they continue to improve

**Comment by adamhannigan** [comment]
@JoseRFelix The new code structure is now live for Sunflower Land. We are hoping we can get a lot of these awesome improvements in for our code base health!

**Comment by adamhannigan** [comment]
Closing the current state of this PR due to the refactor conflicts.

**Pull request closed without merging**
