### PR TITLE
[FIX] Crafting Modal UI

### PR DESCRIPTION
**Pull request by spencerdezartsmith**
# Description

This PR removes the `Is it ready?` modal from the food buildings and moves the "in progress" UI into the modal so that a player can still peruse the recipes while they're cooking something. 

I have added two other small fixes:

- Show the reward amounts for items when claiming achievements.
- Select the next food in `Feed` modal after eating all of one type.
Screen Shot 2022-11-28 at 8 21 21 pm
Screen Shot 2022-11-28 at 8 28 25 pm
Screen Shot 2022-11-28 at 9 12 20 pm

Fixes #issue

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- Cook something then open the modal.
- Eat food and see the next item selected.
- View achievements rewards

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Polysemouse** [comment]
Should we hide the cook button instead of disabling it when chef is busy?

The font size for In Progress and Recipe could be made the same size.

**Review by c-py — APPROVED** [review]
Tested and working well mate!

**Comment by spencerdezartsmith** [comment]
> Should we hide the cook button instead of disabling it when chef is busy?
> 
> The font size for In Progress and Recipe could be made the same size.

I had the test the same size but didn't think it looked good. I like the smaller size because its almost like a secondary piece of information.

I think leaving the cook button there is fine.

**Comment by Polysemouse** [comment]
@spencerdezartsmith sure thing

**Pull request merged**
