### PR TITLE
[WIP-FEAT] Achievements

### PR DESCRIPTION
**Pull request by TeissierYannis**
# Description

**This feature includes an Achievement system.** 

_You need to complete tasks to earn rewards_

- [ ] Achievement system [70%]
- [X] Harvest Plant Achievement
- [x] Earn Rock/Iron/Gold Achievement
- [ ] Earn wood Achievement
- [ ] Craft Item Achievement
- [ ] Reward system

- [ ] UI (maybe to rework) [80%]
- [ ] Optimization [10%]
- [ ] Achievements redaction [0%]

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

At the moment, this feature is a work in progress.

Some bugs are highly possible.

To test :
- Go to your farm and check if the achievement menu is placed
- Start to earn sunflowers and check if the progress increases.

If the first load throws errors, that's due to the temporary system for the progress. It's stored in local storage and the initialized might not work the first time.

# Preview

Video : https://teissieryannis.com/assets/img/DEMO-Achievement-V1.mp4

preview-achievements-gif

# Checklist:

- [X] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [X] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by brian-man** [comment]
Interesting.

Is there a game benefit to completing the achievement[s]? Or just bragging rights?

**Comment by TeissierYannis** [comment]
> Interesting.
> 
> Is there a game benefit to completing the achievement[s]? Or just bragging rights?

In a first times you'll be able to claim rewards, like resources or maybe xp. Why not limited edition nft like for the Easter bunny, for events etc. 

And, if you comple a full theme of achievement maybe you can have a bonus at the end. At the moment rewards aren't coded, and achievements system is in build. 

Everything is possible

**Comment by TeissierYannis** [comment]
> Interesting.
> 
> Is there a game benefit to completing the achievement[s]? Or just bragging rights?

And why not, some title, like unstoppable farmer idk

**Comment by brian-man** [comment]
> Everything is possible
Sure.  I was curious about what you had in mind. :)  Cheers.

**Comment by Amon-S** [comment]
This could be a very nice introduction to an achievement tree  with more and more items added to the game. I want to have in depth look into this to see what i can do 👍

**Comment by TeissierYannis** [comment]
> This could be a very nice introduction to an achievement tree with more and more items added to the game. I want to have in depth look into this to see what i can do 👍

I hope it will be pleased by everyone !

**Comment by adamhannigan** [comment]
@TeissierYannis This is a huge contribution. Wow!

Achievements is an amazing idea but will require significant API and Smart Contract design from the core team. 

This has given us a really good idea of how to approach this but we can't go adding a key piece of functionality like this at the moment.

**Comment by TeissierYannis** [comment]
> @TeissierYannis This is a huge contribution. Wow!
> 
> Achievements is an amazing idea but will require significant API and Smart Contract design from the core team. 
> 
> This has given us a really good idea of how to approach this but we can't go adding a key piece of functionality like this at the moment.

Okay, no problems, I hope that idea will help you later !

**Pull request closed without merging**
