### PR TITLE
[FEAT] Add Tulip Bulb to Garbo

### PR DESCRIPTION
**Pull request by eliasSFL**
# Description

- Add Tulip Bulbs to Garbo

Fixes #issue

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

# Checklist:

- [ ] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by eliasSFL** [comment]
Backend updates needed to add Tulip Bulbs in Garbo's shop as well as support for appearanceDate

**Comment by eliasSFL** [comment]
Converting to draft while I figure how to write tests for this feature

**Comment by eliasSFL** [comment]
I'll create a separate PR for the appearance Date implementation. For now, we can include Tulip Bulbs to Garbo first.

Backend would need to add Tulip Bulbs as well

**Review by adamhannigan — APPROVED** [review]
Just added to backend ✅

**Pull request merged**
