### PR TITLE
[FIX] Chicken Removal Bug

### PR DESCRIPTION
**Pull request by mGranTY**
# Description

Fix a bug when removing a chicken with the rusty shovel and trying to place it again

Reported here: https://discord.com/channels/880987707214544966/1047172809341808671/1047172809341808671

image

## Type of change

Please delete options that are not relevant.

- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Run local
Place Hen house
Place chickens
Remove a chicken and place it again
# Checklist:

- [X] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [X] I have read the contributing guidelines and agree to the T&Cs
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Rofrtd — APPROVED** [review]
LGTM

**Comment by Myth727** [comment]
Run into this issue myself today, hopefully works smooth after the updates.

**Comment by Myth727** [comment]
Can't place any chickens down now. So hoping this gets fixed soon as I'm longer gathering eggs :(

**Review by Rofrtd — CHANGES_REQUESTED** [review]
Will discuss another solution for this one.

**Review by Rofrtd — APPROVED** [review]

**Pull request merged**
