### PR TITLE
[FEAT] Add entry to community garden from Helios

### PR DESCRIPTION
**Pull request by AzaroQL**
# Description

Added npc to Helios to access community garden.

image
image

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manual test

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by spencerdezartsmith — COMMENTED** [review]
Love the community garden!

Would you be able to add a shadow to this npc the same as the one above?
Screen Shot 2022-12-01 at 11 17 19 am

Also I think the `Back` button is a little out of place. The boat is the main navigation hub in the game. Could we add the boat in and have its options be Home or Helios instead?

**Comment by AzaroQL** [comment]
@spencerdezartsmith Done.

**Comment by spencerdezartsmith** [comment]
I just noticed a couple more small UI issues. 
- On mobile the header goes under the close button. I just merged in a `CloseablePanel` component which you should be able to use here.
- Also there is extra padding on the left side of the button.
- Also the image needs `mb-3` underneath it. 

Screen Shot 2022-12-02 at 12 26 06 pm

It's always helpful to build these things mobile first because if it works on mobile typically it will be fine on desktop. The same can't be said for desktop -> mobile.

**Comment by AzaroQL** [comment]
Fixed

**Review by spencerdezartsmith — APPROVED** [review]
👍🏼

**Pull request merged**
