### PR TITLE
[FEAT] Custom Buying & Selling Input

### PR DESCRIPTION
**Pull request by hujikol**
# Description

This idea brings freedom and avoids too much clicking when we want to sell or buy in the custom amount (Bulk Buy/ Sell).
Feature change #1089 

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Manual testing has been conducted (see demo video), and local development testing has been conducted.

# UI Changes

## Buying
image

## Demo Video
https://user-images.githubusercontent.com/12151051/173825180-499b5100-551b-4b9f-a8b6-3465ea1c35a8.mp4

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE], or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] Code has been refactor.

### CODE REVIEW

**Comment by Demonbane18** [comment]
nice i hope this get approved

**Comment by hujikol** [comment]
Hello @tiffanydys, thank you for the follow-up ^_^, 
and thank you for the PR references, I've been read them and have a summary of my own, 
...
on that 2 PR have so many variations of the UIX, and also I'm aware that the team also considering the simplicity of the current flow, while the already mentioned PR has more complicated UIX (in my opinion).

as mentioned by @adamhannigan 
> The typically workflow right now is plant -> harvest -> sell. For the majority of users, I predict they would click the 'Sell All' button.
> 
> Adding an extra step would add friction to this flow. I would suggest ensuring that the workflow is firstly suited to accommodate the majority of users and how they play. It should be the 5-10% who want to do a custom bulk sell that needs to do an extra step.

So I came up with this new variation of the UIX as I do my own research on it, it's a more simple and intuitive way. A lot of the UIX I'm using are utilizing the current component, and in the way of interaction principle, as I learn it, it should be no longer than 3 steps to achieve the goals. While I also arranged the button in that way so the user usually scans top to bottom.

But I see the team right now is focusing to build the land expansion thing and want to manage all the features easily, but sooner or later it will be useful to be implemented in the in-game marketplace too... but yet I'm open to all opinions.

**Comment by spencerdezartsmith** [comment]
Hey there @hujikol. Thank you so much for your contribution. As @tiffanydys mentioned we have had a few PR's with a similar implementation. We want to stay away from inputs as much as possible. We don't like the UX of them. 

The `0` not removing ect and mobile is also an issue with things overflowing...

Screen Shot 2022-06-17 at 8 56 58 am

Screen Shot 2022-06-17 at 8 56 30 am

I think a better approach here and something we would be more willing to consider is to just add a `Sell 10` button to align with the `Buy 10`. 

Again we're super appreciative of the effort but we will close this one for now. Please feel free to implement the suggestion above.

**Comment by hujikol** [comment]
> I think a better approach here and something we would be more willing to consider is to just add a Sell 10 button to align with the Buy 10.

thankyou for the input, I think it's another solution too but still, we need to encourage the artist to make a better layout to be implemented soon.

I'm also thinking about adding max buy to align it with your suggestion, how about that idea?
so there will be 3 buttons in each section, one, ten, all.

I also keep trying to design a new UI for the mobile version.

**Comment by Polysemouse** [comment]
If this feature is implemented in the future, could we also have a confirmation when buying items?  Sometimes I would try buying an item but I mistakenly bought the wrong one.

It would be nice to have a unified UI/UX for both buying and selling (both having a confirmation).

**Pull request closed without merging**
