### PR TITLE
[ FEAT ] Update bumpkin achievement status when completed

### PR DESCRIPTION
**Pull request by hujikol**
# Description

When achievement is completed, the progress counter still going to count even if it exceeds the requirement, replacing the progress bar and counter "Claimed" description.

Fixes Sunflower Isles Bug Bash ticket 68

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

| Before | After |
| ------------- | ------------- |
| image | image |

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Myth727** [comment]
All honesty people like seeing the progress they make after achieving something. I firmly believe this update is not needed. But this is my opinion. @adamhannigan

**Comment by hujikol** [comment]
for that matter, we could utilize all progress information saved in the bumpkin address to create something similar to RPG game character statistics in the bumpkin profile tab, showing all stats on total farming on each crop, total SFL spending, and many more...

**Comment by Myth727** [comment]
> for that matter, we could utilize all progress information saved in the bumpkin address to create something similar to RPG game character statistics in the bumpkin profile tab, showing all stats on total farming on each crop, total SFL spending, and many more...
> 
> Edit: even for the people like you who like competitive environments, we could also implement a leaderboard that refreshes daily (currently there is a community-created leaderboard by @veenhdek created in Dune )

Appreciate the fast response and agree something in game would be awesome! I look over the Dune stuff now and again but just gotta suggest in game is better for your average customer. RPG style stats I'd very much love to see!

**Review by spencerdezartsmith — APPROVED** [review]
I think this makes more sense then going over the requirement in the progress bar. I like the idea of some sort of RPG stats. 

I am accepting this change for now.

**Pull request merged**
