### PR TITLE
[FEAT] Plaza Moderation Tools

### PR DESCRIPTION
**Pull request by 0xSacul**
# Description

As requested a lot recently, this PR brings some moderation tools for the Plaza.

Current Functionalities are:
- Ability to view the list of connected players, and the server's chat history with date & time
- Actions such as Teleport, Kick and Mute
- Kick: Will simply kick a player from the server, player will see a modal popping up saying "You have been Kicked for ..."
- Mute: This action will prevent a player from using the chat on any server. Moderators can choose the mute time
- Teleport: With a simple button, Moderators can teleport to any players

Currently, the Kick & Mute actions are just placeholder waiting for API changes. But expect Player List, Chat History & Teleport function to already work like expected.

## Some Screenshots of the UI
Screenshot 2023-08-30 at 14 56 28
Screenshot 2023-08-30 at 14 56 42
Screenshot 2023-08-30 at 14 56 49
Screenshot 2023-08-30 at 14 56 55
Screenshot 2023-08-30 at 14 57 03
Screenshot 2023-08-30 at 14 58 29

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Lots of local tests, will include yarn test once PR is ready.

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by 0xSacul** [comment]
## Adding a Search Input for Chat History

Screenshot 2023-08-30 at 16 43 03

**Comment by 0xSacul** [comment]
PR is almost ready, moving from draft to open,

New Features: 
- Search Input in Player List
- Offline Mute (Allow mods to mute a farm id even if player isn't online)

Upcoming: 
- Mod Action Logs per Player, you'll be able to see if a player already got muted/kicked in the past.

PR is safe to test on testnet, everything should work like expected.

**Review by c-py — APPROVED** [review]
🔥 Nice work @0xSacul !

**Review by c-py — APPROVED** [review]
LGTM!

**Pull request merged**
