### PR TITLE
[FEAT] Valentine island

### PR DESCRIPTION
**Pull request by mGranTY**
# Description

ADD VALENTINE ISLAND TO THE GAME

image
image

WAITING FOR MORE ARTIST FEEDBACK!

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Polysemouse** [comment]
I love the overall look and feel of the island!

I would probably remove the checkerbox pattern for the grass and use the new texture from SunnySide pack.  The checkerbox pattern is only needed for the home island because we can place placeables on it.  Thay way the island can look more natural.

**Comment by SteveChickenCX** [comment]
I love it!

Maybe we can throw some heart shaped "fruits" near the bridges water.

**Comment by mGranTY** [comment]
> I love the overall look and feel of the island!
> 
> I would probably remove the checkerbox pattern for the grass and use the new texture from SunnySide pack. The checkerbox pattern is only needed for the home island because we can place placeables on it. Thay way the island can look more natural.

@Polysemouse i will talk with the artists and see what they can do.

**Review by adamhannigan — APPROVED** [review]
Awesome work @mGranTY 👏 

There are some small sizing issues but we can fix them off the main branch 🚀

**Pull request merged**
