### PR TITLE
[FEAT] Skill upgrades toast notifications

### PR DESCRIPTION
**Pull request by jcads**
# Description

Shows a toast notification once skill upgrades are avaialable.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Manually set level and upgrades in `skillUpgradeToast.ts`

https://user-images.githubusercontent.com/50954098/161379048-8d75cbf5-4052-4082-9585-834d3800f628.mp4

https://user-images.githubusercontent.com/50954098/161379054-f50f6593-e823-4c31-92d5-11d37a9d9558.mp4

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jcads** [comment]
**Update:** moved the function call to Game.tsx to show the notification after saving, not just when farming and gathering.

**Comment by adamhannigan** [comment]
@jcads Nice initiative. 

One concern around this is that the logic gets called on every single game re-render instead of just the actions that would cause a skill upgrade.

We want to keep the Game.tsx component as lightweight as possible. Adding more functionality into that component leads to more critical code that needs to be maintained. Given that a user may only ever see this message once every couple weeks I suggest that we take an approach that is not coupled to every re-render.

Consider moving this logic into the `House.tsx` component. On the first render, we can check if a skill upgrade is available and display a call to action on the House (I.e. an exclamation mark). This won't show in real time, but the next time a user enters the game they will see the notification and open the house.

What do you think?

**Comment by jcads** [comment]
@adamhannigan I initially did something like this on every harvest and every mining/chopping but it resulted in more code duplication. 

I think moving the logic to House.tsx is a better approach.

**Comment by jcads** [comment]
image

**Review by adamhannigan — CHANGES_REQUESTED** [review]
Awesome work. I manually tested it and it feels very natural!

It is also very clear to the player what they need to do 🤗 

Apologies for the delay, been extremely busy with launch 😅 I have left just one small suggestion to help improve render performance and reduce some bugs in the future

**Review by adamhannigan — APPROVED** [review]
LGTM 🚀 Apologies on the delay. Awesome work 👏

**Pull request merged**
