### PR TITLE
[CHORE] New way to convert markdown to JSON.

### PR DESCRIPTION
**Pull request by AzaroQL**
# Description

Current way of updating OS data is not consistent, you have to update values in two files, and conversion script requires fixes.

I have created new script and updated markdown file to contain all info needed for OS.
No more manual updates in json files.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manual test.

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [n/a] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AzaroQL** [comment]
TODO:
1. Add logic for flags
2. Clean up
3. Add markdown files for all SFTs(might need help with that, there are 100+ of them)

**Comment by AzaroQL** [comment]
> is the markdown files different from the current markdown file in [_scripts/markdown](https://github.com/sunflower-land/sunflower-land/tree/main/_scripts/markdown) ? if yes, maybe need to update the README.md first to get all documented on how to structurize the markdown files later, and maybe I could help.
> 
> We could also integrate the categorical selection for opensea listing that proposed in this issue #1178

Current markdown files have only description part, so ye, its needed to replace those. 
My PR is still in draft state, Im waiting for core team approval before proceeding with updating all the markdown files.
README updates are already a part of TODOs, those are mandatory before moving PR from draft state.

Thats an awesome point regarding issue #1178. We def can include those changes in this PR.

If you want to help with files migration msg me in coders-chat, Ill give you all the info.

**Review by adamhannigan — COMMENTED** [review]
Great improvement @AzaroQL 

This is a much smoother process 👏 I have ran it locally and it was seamless.

Happy for you to continue on this path 🏆

**Comment by AzaroQL** [comment]
With help of @hujikol we migrated all the markdown files.
Should be ready for review now.

This PR closes #1178.

**Review by adamhannigan — APPROVED** [review]
Great improvement! Awesome work everyone involved 🚀

**Pull request merged**
