### PR TITLE
[FEAT] Add Label in Faction Shop Item Details if player is not in a Faction

### PR DESCRIPTION
**Pull request by eliasSFL**
# Description

image

Fixes #issue

# What needs to be tested by the reviewer?

Please describe how this can be tested.

# Checklist:

- [ ] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by spencerdezartsmith** [comment]
Hey @eliasSFL I think that the wording here is too strong. It almost implies that the player is doing something wrong by not being in a faction. 

Could we maybe just make this label a warning/info which says something like "Faction members only"?

**Comment by eliasSFL** [comment]
> Hey @eliasSFL I think that the wording/label colour here are too strong. It almost implies that the player is doing something wrong by not being in a faction.
> 
> Could we maybe just make this label a warning/info which says something like "Faction members only"?

@spencerdezartsmith 

Something like this?
image

**Comment by spencerdezartsmith** [comment]
> > Hey @eliasSFL I think that the wording/label colour here are too strong. It almost implies that the player is doing something wrong by not being in a faction.
> > Could we maybe just make this label a warning/info which says something like "Faction members only"?
> 
> @spencerdezartsmith
> 
> Something like this? image

Is the full width label something new? It feels overwhelming too me 😅

**Comment by eliasSFL** [comment]
> Is the full width label something new? It feels overwhelming too me 😅
@spencerdezartsmith Hmmm I made it full width to be in line with how the buttons are full width as well. Not too sure if that's the right approach

**Comment by spencerdezartsmith** [comment]
> > Is the full width label something new? It feels overwhelming too me 😅
> > @spencerdezartsmith Hmmm I made it full width to be in line with how the buttons are full width as well. Not too sure if that's the right approach
Screenshot 2024-10-02 at 1 25 34 PM

I think its better to just keep our labels as the size of the text they contain. Can this just be listed along with the exp amount? It could even be default colour and change the text to be "Faction member exclusive" with no exclamation. You can use the mark icon. 

Also as and aside... can we fix the background of the images?

**Comment by eliasSFL** [comment]
> I think its better to just keep our labels as the size of the text they contain. Can this just be listed along with the exp amount? It could even be default colour and change the text to be "Faction member exclusive" with no exclamation. You can use the mark icon.
> 
> Also as an aside... can we fix the background of the images?

@spencerdezartsmith Something like this?
image

I'll figure out the issue with the background after

**Comment by eliasSFL** [comment]
image

Okay figured out the background issue

**Comment by spencerdezartsmith** [comment]
I think it should say `Faction member exclusive` which is more inviting and generates more excitement about joining. No `!`. The spacing between the labels can be reduced by one also.

**Comment by eliasSFL** [comment]
@spencerdezartsmith 
image

**Comment by spencerdezartsmith** [comment]
> @spencerdezartsmith image

The right colour might be blue which indicate "information". What do you think?

**Comment by eliasSFL** [comment]
> The right colour might be blue which indicate "information". What do you think?

Hmm the not-in-correct faction label used danger as well, do you think we match it or we use different questions for it?
image

**Comment by eliasSFL** [comment]
> The right colour might be blue which indicate "information". What do you think?

@spencerdezartsmith 
Hmm the not-in-correct faction label used danger as well, do you think we match it or we use different questions for it?
image

**Comment by spencerdezartsmith** [comment]
> > The right colour might be blue which indicate "information". What do you think?
> 
> Hmm the not-in-correct faction label used danger as well, do you think we match it or we use different questions for it? image

Yeah but only faction members can see this right? Thats a bit different because everyone already is in a faction. 

I am just hesitant on the other one because new players may feel they are doing something wrong by being hit with an error label. Having it be an exclusive thing rather than a wrong thing is better imo.

**Comment by spencerdezartsmith** [comment]
> image
> 
> Okay figured out the background issue

I think just go with this one 😄

**Comment by eliasSFL** [comment]
@spencerdezartsmith Alright I've updated the colours
image

**Review by spencerdezartsmith — APPROVED** [review]
LGTM

**Pull request merged**
