### PR TITLE
[FEAT] Plaza Moderation Tools Update

### PR DESCRIPTION
**Pull request by 0xSacul**
# Description

Hi, been a while,

First version of moderation tools has been up and running for a while too now and feels kinda outdated, let's fix that 👀 

Changes:
- Reworked UI for Players & Chat History tabs
- Mobile Compatibility
- Added a new Player tab with advanced informations about the selected player
- Tools now include an offline unmute
- Clicking on a username/farmId in Chat History opens the Mute modal

Some screenshots of the new UI (can still change):

Screenshot 2024-04-16 at 17 12 14
Screenshot 2024-04-16 at 17 12 24
Screenshot 2024-04-16 at 17 12 05

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

yarn lint ✅ 
image

yarn tsc ✅ 
image

yarn test ✅ 
image

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings (for now lol)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by 0xSacul** [comment]
**Not final, can still change**

No more table, better looking players list (and mobile friendly lol) 
👀 
Screenshot 2024-04-15 at 20 29 44
Screenshot 2024-04-15 at 20 29 54

**Comment by 0xSacul** [comment]
Marked as ready for review but not ready for merge yet.

**Comment by 0xSacul** [comment]
Now ready for review & merge 👀

**Review by c-py — APPROVED** [review]
Looks great @0xSacul ! I have pushed one update for the relative positioning. Let me know if I missed something on that and I can revert it 😆 .

**Pull request merged**
