### PR TITLE
[Feat] Music Player

### PR DESCRIPTION
**Pull request by rickfurt**
# Description

This PR refer to issue #125 , to implement a music player.
This PR was pair reviewed/tested with @Rofrtd.
Type of change
 
 - [x] New feature (non-breaking change which adds functionality)

# How to test?

 * Click on music note (player will show)
 * Test play/pause buttons. Obs.: "Next track" button wont work as we only have one song currently
 * Test volume slider
 *  Click on chevron-right to hide the player

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

Screen Shot 2022-01-26 at 10 28 41 pm
Screen Shot 2022-01-26 at 10 28 33 pm

### CODE REVIEW

**Review by adamhannigan — COMMENTED** [review]
Screen Shot 2022-01-26 at 11 19 52 am

Great to have this music back!

I still have the same issue with the last PR though 🤔 When I load the game, the music is paused and the pause button is showing.

Expected behaviour - When first playing the game, the music is playing and the pause is showing.

**Comment by Rofrtd** [comment]
> sed and the pause button

Hey @adamhannigan, do you have the browser blocking the music automatically? isn't the music playing but the browser is blocking it?
Which browser are you using? 
Just trying to figure out whats going on, as we were unable to replicate the issue!

**Comment by rickfurt** [comment]
Hey @adamhannigan , I figured out what was the issue.

According to Chrome policy the autoplay is allowed without user interaction but only on mute mode, for this reason you were unable to hear the song without interacting with the player, although the song was playing.

To fix this bug I created a function to check if the browser is Chrome and matched the initial state autoplay state to paused instead.

[google's autoplay policy](https://developer.chrome.com/blog/autoplay/#iframe-delegation)

**Review by adamhannigan — APPROVED** [review]
This is working now. Great job 💪 @rickfurt

**Pull request merged**
