### PR TITLE
Draft UI Improvement: Display account address & player avatar

### PR DESCRIPTION
**Pull request by zinkkrysty**
I also started to refactor some of the UI but I am not finished yet. Maybe you can reuse some of the ideas. 

@spencerdezartsmith I hope this is the right handle :D 

Kapture 2022-01-02 at 14 55 14

### CODE REVIEW

**Comment by chris-calo** [comment]
> I also started to refactor some of the UI but I am not finished yet. Maybe you can reuse some of the ideas.
> 
> @spencerdezartsmith I hope this is the right handle :D
> 
> Kapture 2022-01-02 at 14 55 14

Being able to click the address and quickly copy it to one's pasteboard would be awesome, too! Don't know if it's been considered yet.

**Comment by zinkkrysty** [comment]
> > I also started to refactor some of the UI but I am not finished yet. Maybe you can reuse some of the ideas.
> > @spencerdezartsmith I hope this is the right handle :D
> 
> Being able to click the address and quickly copy it to one's pasteboard would be awesome, too! Don't know if it's been considered yet.

good idea. that could be done rather quickly

**Comment by zinkkrysty** [comment]
> > I also started to refactor some of the UI but I am not finished yet. Maybe you can reuse some of the ideas.
> > @spencerdezartsmith I hope this is the right handle :D
> 
> Being able to click the address and quickly copy it to one's pasteboard would be awesome, too! Don't know if it's been considered yet.

done ✅

**Comment by spencerdezartsmith** [comment]
Thank you so much for this. I have implemented this feature in the new codebase 🚀

**Pull request closed without merging**
