### PR TITLE
[FIX] Change Sold Out span color

### PR DESCRIPTION
**Pull request by tiffanydys**
# Description
- Changed the color of the span `Sold Out`
from `blue` -> `red`
- Makes it evident that the item is `Sold Out`
- Makes it consistent to the whitepaper as well

**WHITEPAPER**
Screen Shot 2022-05-14 at 11 36 03 PM

**BEFORE**
Screen Shot 2022-05-14 at 11 37 58 PM

**AFTER**
Screen Shot 2022-05-14 at 11 38 24 PM

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
`yarn dev` - tested on local dev `Sunflower Tombstone` NFT since it's `Sold Out`

Screen Shot 2022-05-14 at 11 42 39 PM

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by SteveChickenCX** [comment]
Hey Tiff, maybe we can add in there a supply counter like 0/200 .

**Comment by Rofrtd** [comment]
Hi @tiffanydys looks great,

Do you want to add the supply counter suggested by @SteveChickenCX on this PR or on a next one?

**Comment by tiffanydys** [comment]
> Hi @tiffanydys looks great,
> 
> 
> 
> Do you want to add the supply counter suggested by @SteveChickenCX on this PR or on a next one?

Hey @Rofrtd sure, I'll be adding it in gimmie a few hours, still at work. 😅

Thanks 🤗

**Comment by Rofrtd** [comment]
> > Hi @tiffanydys looks great,
> > Do you want to add the supply counter suggested by @SteveChickenCX on this PR or on a next one?
> 
> Hey @Rofrtd sure, I'll be adding it in gimmie a few hours, still at work. 😅
> 
> Thanks 🤗

Perfect, we'll wait to merge it with the supply count then!

**Comment by tiffanydys** [comment]
Hey guys, @SteveChickenCX @Rofrtd @c-py 
found a few problems implementing the supply count:

1. The supply count doesn't show when it has an `infinite` supply (from v1 migrations: `selected.maxSupply` is `0`)

For ex:
Farm Cat should display a max supply of **75**
Screen Shot 2022-05-20 at 1 38 27 PM

**Solution: modify contracts for v1 NFTs to return a `maxSupply`.**

Exemption: Sunflower Tombstone in the contract should also return the total supply as `maxSupply`
Screen Shot 2022-05-20 at 1 38 16 PM

2. When I display the supply count it looks ok on desktop but is displayed on a next line in mobile:
Screen Shot 2022-05-20 at 1 37 48 PM

**Any suggestion how to display the supply count?**

**Comment by tiffanydys** [comment]
Hey guys, an update:

I solved problem # 2 from my previous comment:
- made style changes to adjust the text size when user is using a smaller device.
- this change doesn't affect the current sizing of the text in desktop view/bigger devices

Screen Shot 2022-05-22 at 9 48 56 PM

**Comment by adamhannigan** [comment]
@tiffanydys Great initiative 👏 

I feel showing the total supply makes it too cluttered. I prefer the earlier screenshot you added

**Comment by tiffanydys** [comment]
Hello @adamhannigan, reverted my earlier changes, thanks 😄

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!

**Review by adamhannigan — APPROVED** [review]
LGTM

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!

**Pull request merged**
