### PR TITLE
[FEAT] MoM End Event

### PR DESCRIPTION
**Pull request by ShiningMinions**
# Description

REMAINING TODOs & ACTION ITEMS:
- ~~Telescope still needs video playing functionality added~~
  - Done, but one bug remains: You can click-through to map once video is playing.
- Need final telescope asset chosen.
- Need telescope Recipe + ID on testnet for full end-to-end test ~~+ placeholder code removed~~.

This PR marks the end of the MoM event and final interaction with Melon Dusk. This PR also introduces a new "telescope" NFT. Please see this Issue for pre-approved requirements: https://github.com/sunflower-land/sunflower-land/issues/1098

melon-dusk-gift-telescope-dialog

melon-dusk-mint-telescope-dialog

https://user-images.githubusercontent.com/103600068/174691658-a9da13e5-cec5-4f04-a7a8-ce47dfbe909e.mp4

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I tested chunks of the feature by fake-adding items into my game.inventory's gamestate. 

Pleas Note: I can't do full end-to-end test without Telescope recipe on testnet.

mom-end-yarn-test

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Credits:
- Feature Proposer: @Z1kou 
- Requirements Writer, Coder: @ShiningMinions 
- Critics: Polysemouse (nezumijeep#3310 - Discord) and Noisy#0666 (Discord)
- Melon Dusk in Space (video asset): Vergelsxtn#8727 (Discord), astronaut avatar by @Z1kou 
- New Rocket Launch Sound Effect: RadishPies#4163 (Discord)

### CODE REVIEW

**Comment by SteveChickenCX** [comment]
well done shining minion, I love it!

**Comment by dimlaitman** [comment]
> @adamhannigan Can I get some communication on this? Is this going to get reviewed?

I'm surprised it took 3 months...

**Comment by adamhannigan** [comment]
@ShiningMinions My mistake, I missed this Github notification.

Where it stands right now we are a bit blocked on the art. There is a lot of working happening with guidelines + consistency at the moment. We had some awesome submissions, but nothing that yet met the new benchmark we are after in the game.

**Comment by adamhannigan** [comment]
As we are at a bit of a standstill with the art, I will close this PR for inactivity.

**Pull request closed without merging**
