### PR TITLE
[FEAT] banner with new token launch date

### PR DESCRIPTION
**Pull request by rickfurt**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

With the changes made to the token launch this PR will add a banner to show the new launch date on splash screen 

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manual tested

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

image

image

### CODE REVIEW

**Comment by ahh1539** [comment]
Might look better with a little bit of padding between the title and the disclaimer on the desktop version.

**Comment by adamhannigan** [comment]
Screen Shot 2022-04-14 at 9 19 19

@rickfurt I would suggest making the banner stretch the width of the screen and be pinned to the very top of the screen. This is usually the standard for banners on websites

**Comment by rickfurt** [comment]
Yeap, no worries I'll do that.

**Comment by rickfurt** [comment]
Made the requested changes.


Desktop:
Screen Shot 2022-04-14 at 1 42 12 pm
Mobile:
Screen Shot 2022-04-14 at 1 39 05 pm

**Comment by Pranav-yadav** [comment]
Great @rickfurt 🚀 

Just one suggestion, try to change the color as well as bg color of the banner such that it should more look like an announcement or warning or info.

Some std bg colors are as follows;
- Info. : `#17a2b8`
- Warning: `#f2c010`
- Danger: `#dc3545`
- Success: `#28a745`

I know it should resemble game theme but, banners outside game can use std colors/bg colors.

**Review by adamhannigan — APPROVED** [review]
Nice work mate 💪 

@Pranav-yadav Good feedback. I feel we can make these improvements but need a consistent colour palette to match the game aesthetic. The red background for instance is a bit jarring compared to our in game colour palette

**Pull request merged**
