### PR TITLE
[FEAT] Add Homeless Cart and Merch Lady 

### LINKED ISSUE #774: [ART] Merch Store Art
Wanted to make an Merch Store because i want people to buy clothes and stuff that has sunflower logo/assets on in. So by clicking that store, we can be directed to the site where we can buy these.
image
image
image

### PR DESCRIPTION
**Pull request by alvinphoebeartemis**
# Description

- Future merch store NPC for people to buy clothes and stuff of Sunflower Land
- Additional decorations for Homeless Shopping Cart

Fixes #774

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

image

**Screenshot Proof for Desktop**
image
image

**Screenshot Proof for Mobile**

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tiffanydys** [comment]
Hello there, with regards to the homeless shopping cart - have you tried how it would look with the homeless tent nft also activated? Cause it has a good chance that it'll crash on top of each other with them having the same spot. (Refer to the image below)

image

Also for the merch store art, maybe we can wait for the official link for the merch so when we have to link it there if the user clicks on it.

**Comment by alvinphoebeartemis** [comment]
Hi @tiffanydys 🤗, goodday, I will check on this. If overlaps, I will make sime adjustments on the cart's position. With regards to the Merch Lady, yeah we can wait for the official link, I agree to that. 😉. Thanks for the inputs. ❤

**Comment by alvinphoebeartemis** [comment]
HI @tiffanydys, I already adjusted the position of the cart. Here is the screenshot for your reference also. Thank you :)
image

**Comment by adamhannigan** [comment]
Some great ideas but we will need to hold off on adding these into the code base until the actual merchandise feature is ready 😅 The time will come!

**Pull request closed without merging**
