### PR TITLE
[FEAT] hover effect for ressources

### PR DESCRIPTION
**Pull request by Z1kou**
# Description

To help new player's start with the ressource farming, I added the name of the ressources when you hover over them on the blacksmith for tools, because it's confusing to know which is which when you just start playing

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
yarn dev:
Hover function
Hover function 2

yarn format :
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\Z1kou\Documents\GitHub\sunflower-land> yarn test
yarn run v1.22.18
warning package.json: No license field
$ jest
setup
 PASS  src/features/game/events/plant.test.ts (34.269 s)
 PASS  src/features/game/events/harvest.test.ts (34.383 s)
 PASS  src/features/game/events/sell.test.ts (34.777 s)
 PASS  src/features/game/events/stoneMine.test.ts      
 PASS  src/features/game/events/goldMine.test.ts       
 PASS  src/lib/utils/hooks/__tests__/useStepper.test.ts (5.78 s)
 PASS  src/features/game/events/chop.test.ts
 PASS  src/features/game/events/ironMine.test.ts
 PASS  src/features/game/events/craft.test.ts

Test Suites: 9 passed, 9 total
Tests:       71 passed, 71 total
Snapshots:   0 total
Time:        50.589 s
Ran all test suites.
Done in 54.29s.

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by adamhannigan** [comment]
@Z1kou Do you think it is clear enough to players that hovering over these items would show the tooltip?

I'm considering if we just show these values inline. 

For example:

```
3 Wood
3 Stone
2 SFL
```

I feel like we have enough space to display the names of the resources. What do you think?

**Comment by Z1kou** [comment]
@adamhannigan  Yes i totally agree, I will do this take but since my purpose was to help new players anyways i will try to add on the hover information on how to get the ressources then !

**Comment by adamhannigan** [comment]
@Z1kou Let's remember, every bit of functionality we add is something that could break and needs time in the future to maintain.

In this case, is it absolutely necessary that we add hover functionality?

If the problem is helping new comers understand how to get wood, we can approach this problem a bit differently. I.e. Add a new modal to the game tutorial showing how to collect resources ;)

**Comment by Z1kou** [comment]
@adamhannigan  I get what you meant so i have done some research about the best working format in different inventories of different franchises and i found that this format is the best, What do you think
Inventory format
?

**Comment by adamhannigan** [comment]
@Z1kou The user experience is improving. From a UI point of view I think we still need to do a few touch ups.

A few things stand out:

- The "Wood" and "Stone" text is inconsistent with the rest of the game. It is quite large and all upper case
- The icons for the resources are not aligned with the SFL icon
- The count/badge is very small. For some people it may be too difficult to read how much of an ingredient is required. I would suggest taking it out of the badge container and making it bigger.

**Comment by adamhannigan** [comment]
@Z1kou Let's close this for now. My gut feeling is we need someone to design some UI around this first so it feels more consistent

**Comment by Z1kou** [comment]
@adamhannigan  I did not have the time the past week since i had exams, will dive into perfecting it when  i can and share with you the results !

**Pull request closed without merging**
