### PR TITLE
[FEAT] Water Boat #666

### LINKED ISSUE #666: [PROPOSAL] Boat in the pond ⛵
For improvement, can we also have a boat in the lake for fishing.

### PR DESCRIPTION
**Pull request by alvinphoebeartemis**
# Description

Add boat in the pond.

Fixes #666 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

`yarn test` result
image

# Checklist:

**Desktop:** Screenshot of applied feature.
image

**Mobile:** Screenshot of applied feature.

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tiffanydys** [comment]
Nice addition! Only a few notes regarding the description:
1. add a short description of what you added to the code (for ex `added water boat to pond`)
2. check `New feature` currently it is unchecked
3. (optional) add mobile-view and `yarn test` screenshots to `How has this been tested?`

**Comment by alvinphoebeartemis** [comment]
Hi @tiffanydys , here you go. Already updated the ticket. Thank you. 😎🌻

**Comment by MarketParticipant** [comment]
Maybe I'm too late, but it would be nice if this were an NFT that burnt some wood and SFL to boost your luck at fishing.

**Comment by adamhannigan** [comment]
Screen Shot 2022-04-28 at 9 23 14 am

Great initiative! I'm always for adding decorations and more life to the game.

Very picky bit of feedback, but it looks like the pixel size does not match the same pixel size of the background.

For instance, the pixels used on the bridge appear wider than the pixels used on the boat. For consistency we need to ensure that the same pixel size is used throughout the game (we have a few places where this is not the case that we need to clean up) 🤗

**Comment by alvinphoebeartemis** [comment]
Hi @adamhannigan ,

Thank you for the heads-up! 🤗 I already pushed some updates regarding the pixel issues. Here are my samples.

**Desktop Version**
image
image

**Mobile Version**

**Review by adamhannigan — APPROVED** [review]
Looks good to me! 🚀 Thanks for the contribution 🤗

**Comment by alvinphoebeartemis** [comment]
Thank you @adamhannigan 🤗 More power to us.
Credits to @SrCouve for the sprites.

**Pull request merged**
