### PR TITLE
[FIX] Fix/remove discord on visit

### LINKED ISSUE #1424: [BUG] Town Hall is broken when visiting
## Summary of Bug

as the title says, when you are visiting someone and click the Town Hall, the game crashes.

## Steps to Reproduce

1 - Visit a random farm example: https://sunflower-land.com/play/#/visit/101
2 - click at the Town Hall 
image
3- Game crashes!
image
image

## Expected Behavior

Show contributors 
image

## Actual Behavior

Game crashes 

## Screenshots
.

**Device Information (please complete the following information):**

- Device: 
- OS: Windows 10
- Browser: Opera GX
- Version 90.0.4480.100

### PR DESCRIPTION
**Pull request by j923sneaks**
# Description

This PR removes Discord tab when visiting a farm. It makes sense too since Discord tab is not within context of visiting a farm. ~~I also opted to put flags instead creating a separate component for the meantime.~~

Fixes #1424 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Manual test - testnet

sfl-play-has-discord
sfl-visit-no-discord

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AzaroQL** [comment]
As another approach its possible to read current state inside component. Migth be a bit cleaner without passing params.

`authState.matches("visiting")`

**Comment by j923sneaks** [comment]
> As another approach its possible to read current state inside component. Migth be a bit cleaner without passing params.
> 
> `authState.matches("visiting")`

this was used on 1st iteration of visit feature when components are used for both playing and visiting. To be consistent I now created a separate `TownHall` for visiting which excludes Discord tab and component

**Review by mGranTY — APPROVED** [review]

**Comment by mGranTY** [comment]
> > As another approach its possible to read current state inside component. Migth be a bit cleaner without passing params.
> > `authState.matches("visiting")`
> 
> this was used on 1st iteration of visit feature when components are used for both playing and visiting. To be consistent I now created a separate `TownHall` for visiting which excludes Discord tab and component

i was going to do the way @AzaroQL said, but after looking how it was done previously, i had my doubts, so i just opened a issue and waited until someone more experienced would sort it.

Nice work!💯

**Review by adamhannigan — APPROVED** [review]
Good find 😄 Always fixing the visiting bugs! You must visit a lot of farms 😆

**Pull request merged**
