### PR TITLE
[CHORE] Display important May dates

### PR DESCRIPTION
**Pull request by j923sneaks**
# Description

This PR adds dates for May 2022 according to Discord announcements. One limitation is lack of support for colors in `react-markdown` (which is expected imo). I used emoji as alternative but another limitation is the alignment with text. I think this is evident not only on `Markdown` but across all components.

Fixes #issue N/A

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manual testing - testnet

Desktop view
`UTC+8`
image

`UTC-8`
image

Mobile view
image

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ahh1539** [comment]
Great initiative here! Maybe it would be nice for you to coordinate with @ShiningMinions to integrate this change into their in-game announcements and release notes PR on issue #747 I think it's a more natural fit to go into the announcements section there.

**Comment by ShiningMinions** [comment]
@j923sneaks I will leave it up to you if you are interested in a collaboration - I think your feature adds a tremendous amount of value as it is.

**Comment by j923sneaks** [comment]
hi @ahh1539 @ShiningMinions the idea was to push a small commit to be included in the next patch/release. Looking at PR #747 , @adamhannigan will likely take time to review as it is a new feature w/ new components and logic. 

Tbh i made the bald man as a simplified announcements feature itself 😅 (#184). But @ShiningMinions 's feature is more fleshed out and gives more substantial info so i definitely agree that announcements should be displayed there moving forward. Will gladly repurpose the bald man for other uses e.g. display resource supplies etc.

**Comment by j923sneaks** [comment]
To do: use UTC and convert to local date (and time?)

**Review by adamhannigan — APPROVED** [review]
Great initiative! LGTM 🚀 🤗

**Pull request merged**
