### PR TITLE
[CHORE] Deposit modal

### PR DESCRIPTION
**Pull request by spencerdezartsmith**
# Description
This PR is a rework of the deposit modal. The aim here is to provide clear steps on how the user can deposit to their farm. I have updated the design to align with the rest of the game. For the warning about transferring non SFL items I have added a background colour to highlight the importance of the message. Happy to hear feedback on this. Keeping the background brown just felt like it blended in too much.

Other bug fixes:
- Prevent input zoom when visiting a farm on mobile
- Fix sizing of the right panel in the rare items modal screen. Fix button from being full width when text in this panel is long. ie. Singaporean Flag
- Fix info panel on inventory modal. When a user first starts a farm they have inventory but nothing is in the quick selection so an empty panel was showing. I have added a fallback to the first item in inventory if there are items on nothing is in quick select.

https://user-images.githubusercontent.com/17863697/160240120-04c08bdb-ac68-4841-9ebb-9ecf57ac3137.mov

Screen Shot 2022-03-26 at 11 37 40 pm

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #issue

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by adamhannigan** [comment]
Screen Shot 2022-03-26 at 10 34 56 am

@spencerdezartsmith The UI looks much better but the content is a little misleading. Currently the ERC1155 tokens are not transferrable through Metamask. Players need to go to Open Sea and send it to this address.

Consider having 2 separate guides or tabs. 1 for depositing the SFL and 1 for sending items.

Depositing SFL:

- You have 1202.56 tokens in your personal wallet.
- Metamask Instructions 

Depositing Items:

- You have 4 different Sunflower Land items
- Open Sea instructions

Also, I'm having issues selecting and copying the farm address when it is visible. When I try to highlight it, it flips the modal over.  For me, I never use clipboard buttons. I like to highlight, copy and paste the address and then double check it. Copying partially hidden data to your clipboard feels a bit dodgy to send tokens. I think we should support those who want to highlight and copy the text.

**Comment by spencerdezartsmith** [comment]
https://user-images.githubusercontent.com/17863697/160302807-ced3615a-7f2b-4519-bb46-a484aafdc935.mov

New flow and instructions.

**Comment by spencerdezartsmith** [comment]
https://user-images.githubusercontent.com/17863697/160303865-eea6a306-4be7-481d-8d56-14a2d0f4fa09.mov

**Comment by spencerdezartsmith** [comment]
https://user-images.githubusercontent.com/17863697/160388717-59f83e15-a960-4227-9fb1-2bd647753f19.mov

**Review by adamhannigan — APPROVED** [review]
LGTM. Nice work 🚀

**Comment by jcads** [comment]
What do you think about making the warning red? @adamhannigan @spencerdezartsmith 

image

**prev**
image

**Pull request merged**
