### PR TITLE
[CHORE] Remove Buy MATIC and Buy SFL Buttons

### PR DESCRIPTION
**Pull request by elias7905**
# Description

Previously there was a commit to [disable Poko for buying Block Bucks](https://github.com/sunflower-land/sunflower-land/commit/59049d8ceee1caed0d3517ce341114ce858832c0), but the options for buying MATIC and SFL via Poko is still up. This PR Removes both buttons.
Before
image
After
image

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by c-py** [comment]
@elias7905 Thank you for this! Would it be possible to hide these buttons instead of showing the label?

Right now we don't have a replacement lined up for the MATIC/SFL on-ramp. We are looking into the alternatives for the direct checkout (block bucks).

**Comment by elias7905** [comment]
> @elias7905 Thank you for this! Would it be possible to hide these buttons instead of showing the label?
> 
> Right now we don't have a replacement lined up for the MATIC/SFL on-ramp. We are looking into the alternatives for the direct checkout (block bucks).

Alright I can do that.

**Comment by elias7905** [comment]
@c-py I have pushed the commit to remove the Buy buttons for MATIC and SFL

**Review by c-py — APPROVED** [review]
Awesome! Thank you @elias7905 !

**Pull request merged**
