### PR TITLE
[CHORE] Added metadata for new war items.

### PR DESCRIPTION
**Pull request by AzaroQL**
# Description

Added metadata for new war items.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

n/a

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [n/a] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AzaroQL** [comment]
Waiting for PR https://github.com/sunflower-land/sunflower-land/pull/1509 to be merged before proceeding with actual metadata files.

**Comment by adamhannigan** [comment]
@AzaroQL Thanks for raising this. #1509 is now merged in

**Comment by AzaroQL** [comment]
Rebased and generated json files.

**Review by adamhannigan — APPROVED** [review]
LGTM 🚀

**Pull request merged**
