### PR TITLE
[CHORE/FIX] Improved farm transfer

### PR DESCRIPTION
**Pull request by mGranTY**
# Description

ADDED CLOSE BUTTON AND TITLE TO SETTINGS SCREEN
image

image

ADDED CLOSE BUTTON TO TRANSFER MODAL
image

NEW TRANSFER FLOW

https://user-images.githubusercontent.com/94913189/196015868-ea72c977-dab2-4284-b65f-005a48fce8f6.mp4

TRANSFERRING THE FARM
image

SUCCESS
image

FIXED PERSISTENT TRANSFER MODAL BUG

https://user-images.githubusercontent.com/94913189/196015842-8962a977-f313-4eae-a059-46c1dc71f3fc.mp4

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

# Checklist:

- [X] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [X] Screenshot if it includes any UI changes
- [X] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AzaroQL** [comment]
Maybe its better to close modal completely instead of going back to prev modal?

**Comment by adamhannigan** [comment]
@mGranTY Some awesome improvements 👏 

One suggestion is that we should reword 'Farm' -> 'Account'.

We are moving towards calling these NFTs 'Accounts' to help reinforce the idea of 1 account per 1 person 😄

**Comment by mGranTY** [comment]
> Maybe its better to close modal completely instead of going back to prev modal?

@AzaroQL Sure, i will do that.



> @mGranTY Some awesome improvements 👏
> 
> One suggestion is that we should reword 'Farm' -> 'Account'.
> 
> We are moving towards calling these NFTs 'Accounts' to help reinforce the idea of 1 account per 1 person 😄

@adamhannigan No problem, should i change the farm image to the ticket one?

**Review by adamhannigan — APPROVED** [review]
LGTM. Awesome work 👏 

@mGranTY For now we can keep the farm image as it is more inline with the game's styles.

**Pull request merged**
