### PR TITLE
[FEAT] Adding Radish Statue - Complement to issue [PROPOSAL] Iron Radish Statue #736

### PR DESCRIPTION
**Pull request by TeissierYannis**
# Description

Adding Iron Radish Statue that would give a 10% chance to the owner of having another radish when harvesting (subject to change to not be too OP).

This is a complement to issue Complement to issue " [PROPOSAL] Iron Radish Statue #736 "

# How Has This Been Tested?

I have added a Radish Statue to my Inventory.
-  I check if, the image of the statue was at the good place on the map.
- I Look at the description in the inventory and the render
- I tried to plant radish and to harvest it, to check if the % of drops worked

# Checklist:

- [X] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [X] Screenshot if it includes any UI changes
- [X] I have read the contributing guidelines and agree to the T&Cs
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### Objective 

This pretty exclusive NFT, with the intention of being not just a decoration, but a NFT Buff to reward all the radish farmers. 
This statue would give a 10% chance to the owner of having another radish when harvesting (subject to change to not be too OP).

### Description 

A lucky radish covered by Iron. For some reason, when having this trophy on your farm, you will have a chance to double the reward when harvesting Radish.

You can craft the Iron Radish Statue in the blacksmith.

## NFT

miniIMG (1:1 - 100%)

bigIMG (6:1 - 600%)

preview

### Supply

1000

### Crafting costs

- **250** Radish
- **35** Iron
- **80** SFL

Designed by [@TeissierYannis] &[@jpeyrol]

### CODE REVIEW

**Comment by ahh1539** [comment]
Whew, this one is a bit pricey!! 👀 80 SFL is quite a lot IMO

**Comment by TeissierYannis** [comment]
> Whew, this one is a bit pricey!! 👀 80 SFL & 250 Radish is quite a lot for what you get out of it IMO

It's open to change, that just à proposal but if it's too much or not enough it can be changed

**Comment by jpeyrol** [comment]
> Whew, this one is a bit pricey!! 👀 80 SFL & 250 Radish is quite a lot for what you get out of it IMO

At first we wanted to put 25% as the drop chance to get 2 radish. But after testing, we saw that when harvesting 40 radish you get 70 with the boost. So we decided to lower the chance drop without dropping the price.
I think that if we decided to go with the 10% drop chance, we would go with this cost:

- **150** Radish
- **20** Iron
- **50** SFL

Tell me what you think about it :)

**Comment by ahh1539** [comment]
> * **150** Radish
> * **20** Iron
> * **50** SFL

I think this is much more reasonable, but it's just my opinion. You want it to be challenging to get but not entirely cost-prohibitive. Let me do a quick breakdown. 

- An average farmer right now makes `~8` SFL per day
- Each stone pickaxe costs `~4.3 SFL` to make which gives you about `~3` iron per pickaxe meaning that each iron costs about `~1.43 SFL` total of 20 iron = `28.6 SFL`
- Each radish currently costs `.35 SFL` and 24 hours bringing the seed cost to `~50 SFL` and with 22 plots growing constantly it's still a minimum `7 days` grow time

All of this added up is `128.6 SFL` cost + a minimum 7 days grow time (in a perfect scenario). Going off the current rates of 8 SFL per day for the average farmer means it's about `17 days` of work for the statue. All of this assumes that a halving won't occur during those 17 days, which is very possible one could happen.

**Comment by jpeyrol** [comment]
> I think this is much more reasonable, but it's just my opinion. You want it to be challenging to get but not entirely cost-prohibitive. Let me do a quick breakdown.

I totally agree with you on the price with explanation now. But do you think if we were to up the boost chance it could result in higher price tag ? Would love to get your point of view on this.

**Comment by ahh1539** [comment]
> > I think this is much more reasonable, but it's just my opinion. You want it to be challenging to get but not entirely cost-prohibitive. Let me do a quick breakdown.
> 
> I totally agree with you on the price with explanation now. But do you think if we were to up the boost chance it could result in higher price tag ? I am just wondering if the 10% boost chance is reasonable. Would love to get your point of view on this.

In regards to the boost %, I think that 15% is in line with the current numbers. Nothing game-breaking but the return on investment is still there for the player after a few weeks' time. It's great artwork that we'd all be lucky to have on our farm regardless of utility. Great work!

**Comment by adamhannigan** [comment]
@TeissierYannis Great suggestion!

Right now we can only take in NFT suggestions through community competitions + voting. These competitions ensure the project focusses on the right NFTs to get in the game, ensures the art is consistent and the community helps with plagiarism + other extra checks that need to be done.

The process is a bit slow at the moment while the team is small, but the resource + NFT design needs to go through a few more steps as it impacts the economy of the game.

For now we will need to park this PR until the NFT is accepted by the community + core team

**Pull request closed without merging**
