### PR TITLE
[FEAT] In-game announcements and release notes

### PR DESCRIPTION
**Pull request by ShiningMinions**
# Description

Provide an announcement modal system in-game for players. This announcement modal will communicate both "general" announcements (like the ones communicated in discord's #announcements channel), and "whats-new" announcements (AKA patch-notes of latest release). This announcement modal also sets-up a framework to provide new "types" of announcements in the future.

The goal of this feature is to help support the team by reducing the amount of repeat questions and tickets. I am hoping that this feature helps scale the game tremendously.

Fixes https://github.com/sunflower-land/sunflower-land/issues/677
Partially Fixes https://github.com/sunflower-land/sunflower-land/issues/702

## User Stories

As a player, it would be really nice if I could passively see announcements in game, so that I don't have to actively scavenge Discord to find hard to locate information. This is also true for patch notes regarding the newest release info + github.

As a SFL project maintainer, I want a way to easily prompt my players to see new announcements/release-notes in game, in an attempt to dramatically reduce the amount of time spent on repeat tickets and questions in Discord.

## How it works
- When a player logs in, and they just pulled a new client version, the modal will automatically appear with the "What's New" patch notes. This only happens once per new version released.
- Player can also explicitly see latest patch notes by going to Menu > News
- (When announcement source is coded-in) When a player logs in, and there is some new announcement since the last time they played, it will automatically open the modal at the "Announcements" tab.
- (When announcement source is coded-in) Players can also explicitly see latest announcements by going to Menu > News.

### What's New Announcement:

whats-new-with-announcements

### General Announcements (just an example, announcements source still needed):

general-announcements

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## ❗ IMPORTANT NOTES FOR SFL TEAM ❗

- I have laid the code foundation for "general" announcements under the "Announcements" tab, but the SFL team needs to provide the data stream. I have conveniently provided a block of code that will support this in `src/features/game/announcements/lib/announcements.ts`, the SFL team just needs to un-comment and provide their data stream. (Discord #announcements channel maybe)?
- Both the "What's New?" and "Announcements" tabs render markdown to HTML. Therefore, the better habits you get at making good markdown content, the better it will look in game.
- There are simply too many markdown elements for one person to test through, so I did not test things like markdown images, videos, etc. Just be wary if you provide markdown content with these assets as I didn't support these in this PR.

## Dev Notes
- For code consistency, I followed very similar pattern to the ToastProvider code.
- There may be a few small UI bugs, any help with this would be much appreciated as I'm not the greatest at tailwind.

# How Has This Been Tested?

test

### See video for "What's New?" flow:

https://user-images.githubusercontent.com/103600068/166084049-5b5abe8e-482f-4582-a0c3-725ec3d37de9.mp4

### Other Photos:

mobile-news-menu

news-menu

announcements-mobile

whats-new-mobile

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ahh1539** [comment]
Excellent implementation and clean code.

**Comment by adamhannigan** [comment]
@ShiningMinions This is an amazing initiative, well done 👏 

The core team has a few key items with the upcoming launch around smart contracts + security updates. We will give you some proper feedback on this over the next 2-3 days. Apologies for the delay ❤️

**Comment by adamhannigan** [comment]
Closing for the time being until an appropriate data stream can be sourced 😄

**Comment by ShiningMinions** [comment]
@adamhannigan Would you possibly be interested in the just merging the "What's New?" portion? There are two features here: "What's New?" tab and "Announcements" tab. The "What's New" tab is 100% ready to go. The only one that requires a dataStream is the "Announcements" tab. I can remove the "Announcements" portion, allowing us to merge-in the "What's New" portion. If you agree, I will create a new [CHORE] Issue to implement dataStream at future date with the "Announcements" tab.

**Comment by baron** [comment]
I would love to have this in the game. Honestly a lot of people are barely going to have time to follow Discord during the day and this will give us a great way to keep up with the news.

**Pull request closed without merging**
