### PR TITLE
[FEAT] Move Bumpkin Metadata into the repo

### PR DESCRIPTION
**Pull request by adamhannigan**
# Description

We had inconsistencies between our game and Open Sea wearable images.

This change brings in the Open Sea images for Bumpkins into the game. We can sunset `bumpkins.io` repo following that.

**Note**

`yarn metadata` is currently broken (separate issue). You need to comment out code in `i18n/index.ts` to run.

**Next steps**

Point Bumpkin Wearables URI to point to `sunflower-land.com/wearables/...`

### CODE REVIEW

**Comment by eliasSFL** [comment]
Was waiting for this migration, great that everything is together in 1 repo now 👍🏼

**Comment by eliasSFL** [comment]
@adamhannigan 
Was waiting for this migration, great that everything is together in 1 repo now 👍🏼 

Although is there anything that I need to take note of in future metadata updates other than those you mentioned in the description of this PR?

**Review by spencerdezartsmith — APPROVED** [review]
🎉

**Comment by adamhannigan** [comment]
@eliasSFL Nothing stands out right now.

Over the coming weeks we will likely refactor these metadata objects to make it easier to use as well.

The goal is to make adding collectibles + wearables much easier. Currently there are too many repos + files that need to change just for 1 item 😄

**Pull request merged**
