### PR TITLE
[FEAT] Salesman: add a time left to trade on intro modal

### PR DESCRIPTION
**Pull request by veenhdek**
# Description

Per community feedback I have added a time remaining detail to the Salesman Intro Modal to help clear up any confusion on when the trade ends.

https://discord.com/channels/880987707214544966/880987707692687381/994092755867414548

Proposed look (manually adding a date)
Screen Shot 2022-07-06 at 9 51 38 AM

How it looks currently with no offer (but he is also disabled) included for context
Screen Shot 2022-07-06 at 10 07 00 AM

Fixes confusion on Salesman end time

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Ran repo locally (enabling salesman by commenting out line 39) and tested visual look.
Passed unit tests as well.

# Checklist:

- [X] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [X] Screenshot if it includes any UI changes
- [X] I have read the contributing guidelines and agree to the T&Cs
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by veenhdek** [comment]
This is independent of changes proposed in [PR 1191](https://github.com/sunflower-land/sunflower-land/pull/1191). Can be combined but didn't want them to be dependent on each other

**Comment by veenhdek** [comment]
reconciled conflicts created by merge of my other PR

**Review by 0xsunflowerstudios — APPROVED** [review]
Awesome work! Some great improvements 🏆

**Review by adamhannigan — APPROVED** [review]
LGTM! ❤️

**Pull request merged**
