### PR TITLE
[FIX] More Opensea Metadata Fixes

### PR DESCRIPTION
**Pull request by elias7905**
# Description
- Fertiliser has been discontinued since it got added to the trash collector. Changed the metadata of Rapid Growth from 'Fertiliser' to 'Legacy'
- Remove 'Not for Sale' Banner for Witches' Eve Deco (all have withdrawal dates) and Mutant Crops
- Added Boost Icons for Mutant Crops and AOE Scarecrows
- Fixed Boost icon size for Foliant
- Add missing 'not for sale' banners

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by c-py — APPROVED** [review]
LGTM! Thanks @elias7905 ! Btw this item can be sold at the garbage collector.

**Review by c-py — DISMISSED** [review]

**Comment by elias7905** [comment]
> LGTM! Thanks @elias7905 !
> 
> Will wait for PR to be in `Ready` state before merging 😁

Hey Craig, I will open the PR once I edit the images to remove the not for sale banners for the Mutant crops, as well as the Witches' Eve Seasonal Decorations. As mentioned in the Dev chat this afternoon, the mutant crops will be withdrawable in the near future, so I need to remove the Not for Sale tags on them.

**Comment by elias7905** [comment]
@c-py I'm done with this PR. You can review it

**Comment by elias7905** [comment]
@c-py Most of my image edits are done. you can have a look at it

**Review by c-py — APPROVED** [review]
Fantastic!

Thanks @elias7905 !!!

**Pull request merged**
