### PR TITLE
[FIX] metadata and scroll bugs

### PR DESCRIPTION
**Pull request by AzaroQL**
# Description

1. New metadata had few wrong attributes.
2. The was a bug with scroll, sometimes browser default scroll was used instead our custom one.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Manual test

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [n/a] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AzaroQL** [comment]
Regarding scroll fix. I removed useShowScrollbar hook in announcements and war messenger modals. 

I tried to find why it was used in the first place, but couldnt figure it out, is it part of some legacy?
If so I can clean up all remaining places where it is used as part of this PR.

**Comment by AzaroQL** [comment]
Rebased and added metadate for beetroot and green amulets.

**Review by mGranTY — COMMENTED** [review]
I tested it and it really fixed the scrollbar problem. is there any way to standardize the scrollbar style?

like set all scrollbars to this style
image


instead of this

image

**Comment by AzaroQL** [comment]
> I tested it and it really fixed the scrollbar problem. is there any way to standardize the scrollbar style?
> 
> like set all scrollbars to this style image
> 
> instead of this
> 
> image

Fixed. Thanks for catching that bug!

**Review by mGranTY — APPROVED** [review]

**Review by adamhannigan — APPROVED** [review]
Tested and working well. Great update 🏆 Thanks!

**Pull request merged**
