### PR TITLE
[Fix] Adding Scarecrow Effect

### PR DESCRIPTION
**Pull request by Z1kou**
# Description

Adding the effect of the scarecrow listed in the whitelist to the Game, I am not sure if this is on the plans yet but since it was suggested in discord i did it !

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

yarn dev
yarn test
Yarn test Scarecrow

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by j923sneaks** [comment]
hi @Z1kou i think the 20% boost of Scarecrow is for harvest time reduction, not the sell price 🙈

**Comment by jcads** [comment]
> hi @Z1kou i think the 20% boost of Scarecrow is for harvest time reduction, not the sell price 🙈

I think it is, based on this.

https://github.com/sunflower-land/sunflower-land/blob/97273dec10bdca1c8727f64bd057cf4c27774fda/src/features/game/events/plant.ts#L70-L72

And the harvest time boost has also been reduced to 15%

https://github.com/sunflower-land/sunflower-land/blob/97273dec10bdca1c8727f64bd057cf4c27774fda/src/features/game/events/plant.ts#L48-L51

**Comment by Z1kou** [comment]
@j923sneaks  yeah I read wrong my bad
 @jcads  I checked the docs and they are not up to date it still says that it doubles the wheat value , imma update the value of the scarecrow to 20% ,

Waiting to get confirmation from @adamhannigan  if there is a set value for the scarecrow buff , and updating the docs

**Comment by Z1kou** [comment]
I will put this on hold for now till the docs of the game get updated .

**Pull request closed without merging**
