### PR TITLE
[FEAT] Inventory Modal

### LINKED ISSUE #334: [FEAT] Improve Inventory
A lot of feedback has been given throughout Beta around the inventory being difficulty and buggy to navigate.

The aim of this ticket is to make the inventory more usable. The main suggestion includes just having 2 tabs:

1. A tab for items (seeds, tools, crops all shown together)
2. A tab for collectibles (Food, NFTs etc.)

Also, when displaying on mobile we need to show more items horizontally so split the panes as shown below.

**Includes**

- Increase modal width on Desktop
- Increase modal height on mobile
- 2 tabs in inventory - Basket & Collectibles
- Fix warping of some inventory images

Screen Shot 2022-03-06 at 7 00 00 am

### PR DESCRIPTION
**Pull request by spencerdezartsmith**
# Description
This PR aims to introduce an improved inventory modal. The previous modal was confusing for users. This new one has broken inventory into two categories with each category consisting on sections with an overall scrollable body. This surfaces the inventory on the one page making it easier or get to what you need.

Screen Shot 2022-03-12 at 10 46 52 pm

Screen Shot 2022-03-12 at 10 47 08 pm

**NOTE: I am seeing the following warning generated when selecting items from the modal. I am not too sure what is causing this. It has to do with the `shortcutItem` fn inside the `GameProvider`. Please let me know if you have any ideas on what the problem is**

Screen Shot 2022-03-12 at 10 52 16 pm

Fixes #334 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- Run app and open inventory modal 

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by adamhannigan — COMMENTED** [review]
Looks incredible, I love what you have done with the scroll bar. From a UX point of view this feels 10x better.

Screen Shot 2022-03-12 at 9 03 08 am
Screen Shot 2022-03-12 at 9 04 36 am
Screen Shot 2022-03-12 at 9 03 10 am


I'm wondering whether we need 2 tabs. Could we put the NFTs + Food on the same tab at the bottom? Right now there is a bit of overflow with the tabs.

Also appears a small bit of warping on some images (see attached)

I

**Comment by spencerdezartsmith** [comment]
> Looks incredible, I love what you have done with the scroll bar. From a UX point of view this feels 10x better.
> 
> Screen Shot 2022-03-12 at 9 03 08 am
> 
> Screen Shot 2022-03-12 at 9 04 36 am
> 
> Screen Shot 2022-03-12 at 9 03 10 am
> 
> I'm wondering whether we need 2 tabs. Could we put the NFTs + Food on the same tab at the bottom? Right now there is a bit of overflow with the tabs on mobile view.
> 
> Also appears a small bit of warping on some images (see attached)

Will get this fixed. Did you have any ideas re. The warning I am seeing?

**Comment by spencerdezartsmith** [comment]
@adamhannigan The image weirdness you see looks to be a rendering issue. If you zoom in and out it fixes. I don't know that I have control over that. 🤷🏼‍♂️

**Comment by Z1kou** [comment]
Hey Spencer i have just started learning coding mostly java and i did a formation this week about it so idont know if what i say will be any useful! i have checked every single file of the errors shown, and did an online research, 

**Description:**

Currently useMachine accepts only the first machine instance passed to it and logs a warning if a new instance is passed to it between renders. This prevents the use of a dynamically created machine derived from props. One such example is the createrCounterMachine factory function from the [context docs](https://xstate.js.org/docs/guides/context.html#initial-context). If the initial count is a prop and you intend to create a new machine and interpret whenever the count prop changes, this is not supported.

**Workaround**
One way around this is to leverage the useService hook as it supports resubscribing to a new service when the instance changes between renders. This is essentially how I am currently handling this. Note that useFirstMountState comes from react-use and is used to prevent overwriting the service created on the first render without stopping it.


**I Also found this:**
the common problems of people that faced this did the following:( Hot-patching the library and replacing useConstant with useState seems to have solved the problem.This one i saw that you already used it in your code, Fixing there Xtate declaration values )

**Comment by spencerdezartsmith** [comment]
> Hey Spencer i have just started learning coding mostly java and i did a formation this week about it so idont know if what i say will be any useful! i have checked every single file of the errors shown, and did an online research, This is what i found :
> 
> **Description:**
> 
> Currently useMachine accepts only the first machine instance passed to it and logs a warning if a new instance is passed to it between renders. This prevents the use of a dynamically created machine derived from props. One such example is the createrCounterMachine factory function from the [context docs](https://xstate.js.org/docs/guides/context.html#initial-context). If the initial count is a prop and you intend to create a new machine and interpret whenever the count prop changes, this is not supported.
> 
> **Workaround** One way around this is to leverage the useService hook as it supports resubscribing to a new service when the instance changes between renders. This is essentially how I am currently handling this. Note that useFirstMountState comes from react-use and is used to prevent overwriting the service created on the first render without stopping it.
> 
> **I Also found this:** the common problems of people that faced this did the following:( Hot-patching the library and replacing useConstant with useState seems to have solved the problem.This one i saw that you already used it in your code, Fixing there Xtate declaration values )

That actually was helpful. The `startGame` function which is generating the machine using dynamic values was being called multiple times hence the generation of a new instance of the machine. I have moved the call into a state value and calling `startGame` as the default value of the state var. This has removed the warning. Thank you!

**Comment by spencerdezartsmith** [comment]
@adamhannigan I have fixed the issues. I think the two tabs is nice and give us double the space to grow rather than blowing out the one tab content. I will leave it for now.

**Comment by Z1kou** [comment]
> > Hey Spencer i have just started learning coding mostly java and i did a formation this week about it so idont know if what i say will be any useful! i have checked every single file of the errors shown, and did an online research, This is what i found :
> > **Description:**
> > Currently useMachine accepts only the first machine instance passed to it and logs a warning if a new instance is passed to it between renders. This prevents the use of a dynamically created machine derived from props. One such example is the createrCounterMachine factory function from the [context docs](https://xstate.js.org/docs/guides/context.html#initial-context). If the initial count is a prop and you intend to create a new machine and interpret whenever the count prop changes, this is not supported.
> > **Workaround** One way around this is to leverage the useService hook as it supports resubscribing to a new service when the instance changes between renders. This is essentially how I am currently handling this. Note that useFirstMountState comes from react-use and is used to prevent overwriting the service created on the first render without stopping it.
> > **I Also found this:** the common problems of people that faced this did the following:( Hot-patching the library and replacing useConstant with useState seems to have solved the problem.This one i saw that you already used it in your code, Fixing there Xtate declaration values )
> 
> That actually was helpful. The `startGame` function which is generating the machine using dynamic values was being called multiple times hence the generation of a new instance of the machine. I have moved the call into a state value and calling `startGame` as the default value of the state var. This has removed the warning. Thank you!

I am Glad to hear that, It feels amazing to be of help ! I really love the changes, its looking cleaner, and more tidy, Can't wait to try it Ingame Amazing work !

**Review by adamhannigan — APPROVED** [review]
@spencerdezartsmith Amazing work mate! This will do wonders for new users playing the game.

I have rebased onto main to address a conflict as I am doing a release at the moment and want to get this in 🚀 

Good find @Z1kou It is great to have your help in the code now!

**Pull request merged**
