### PR TITLE
[FIX] [QOL] Quantity Input not being able to delete completely / Show price per unit in trade listing screen

### PR DESCRIPTION
**Pull request by eliasSFL**
# Description

**Bug Fix**
- Fixed an issue that prevents user from deleting quantity field all the way to 0

**QOL**
- When Quantity = 0, turns the text red
- When Quantity = 0, List button is disabled
- When Quantity = 0, Price Per Unit = 0.0000 SFL
- When user enters this screen, both input fields are set to 0 by default
- Added Floor Price info in list screen
- If price/unit < floor price, label is red (signifying they're below the floor)
- if Price/unit > floor price, label is green (signifying that they're above the floor)

default
image

Price/unit<Floor Price
image

Price/unit>Floor Price
image

Mobile:
image

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

1. Going into input tab and delete all the way

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by eliasSFL** [comment]
@Rofrtd For your review tomorrow

**Comment by JCtapuk** [comment]
@eliasSFL It wasn’t bad to add the cheapest prices item, otherwise it’s not convenient to view what prices are currently on the market

**Comment by eliasSFL** [comment]
> @eliasSFL It wasn’t bad to add the cheapest prices item, otherwise it’s not convenient to view what prices are currently on the market

@JCtapuk Does think look okay?
image

**Comment by JCtapuk** [comment]
> > @eliasSFL It wasn’t bad to add the cheapest prices item, otherwise it’s not convenient to view what prices are currently on the market


And so it will go. Then we’ll change it if it’s convenient for people to see it =)

**Comment by eliasSFL** [comment]
> And so it will go. Then we’ll change it if it’s convenient for people to see it =)
@JCtapuk I updated the UI again
image

**Comment by eliasSFL** [comment]
@Rofrtd For your review. Added a few QOL features requested by community regarding the trade listing page

**Review by spencerdezartsmith — APPROVED** [review]
Excellent job @eliasSFL

**Pull request merged**
