### PR TITLE
[CHORE] Chinese Translations - New & Refine - 24/06/02

### PR DESCRIPTION
**Pull request by ShinKan42**
# Description

- Swapping English_Term Redirections
- Refining for localization and word-ly style
- Adding simple tips in response to community requests(Line 976-977)
- Minor Bug Fixes: Replacing fixed number to proper parameters (Line 4231)

For text conflicts, please prioritize the refined versions.

Fixes #issue

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ShinKan42** [comment]
There were merging issues which caused multiple repeating lines and dealt with.
No remaining found but for the record.

**Comment by ShinKan42** [comment]
This is my first PR so please point out and guide me through any mistake I've stepped on.

**Review by Rofrtd — APPROVED** [review]
Nice first PR my friend! 
Thanks for contributing.

**Comment by ShinKan42** [comment]
> Nice first PR my friend! 
> Thanks for contributing. 

Thank you! Glad it went well!

**Pull request merged**
