### PR TITLE
[FIX] Visit farm button fix

### PR DESCRIPTION
**Pull request by j923sneaks**
# Description

This PR covers the ff:
- `Enter` key now loads the visiting farm
- ~~Counter now excludes locked crops~~
- ~~Counter now ignores `readonly/visit` mode~~
- Fixed inventory check for zone four in `visitUtils`

Fixes #issue N/A

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Manual testing
~~INITIAL_FARM with Pumpkin Soup~~
Steps:
1. Load your farm -- counter should be correct and excludes locked crops~~

Visit Farm
Steps
1. Sign in metamask
2. Explore a friend's farm
3. input farm ID
4. press `Enter` key -- should load the visiting farm

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by adamhannigan** [comment]
@j923sneaks Some great improvements! 👏 

One area that is flaky at the moment and keeps breaking is the favicon counter. Adding more business logic into the components `canHarvest` and handling logic in the `Soil.tsx` is a quick fix, but it won't make the code stable and will likely break again when one of these components is changed.

I would suggest committing only the Visit farm fix in this PR and actually removing the favicon from the code.

We need to reconsider how we can fix the root problem of the FavIcon counter instead of bandaiding it at the component level. Otherwise this issue will likely resurface. The most sustainable approach would be stripped out all of the logic from the components and handling the fav icon count based on events that are fired in the system. This would require significant work at the moment.

**Comment by j923sneaks** [comment]
Hey @adamhannigan i understand. Reverted some code and retained what's not related. apologies for the many commits 😅 

I too was reluctant to have the same code for each zone only differing in the inventory item to be check. you're right that event based system from `Soil` to `AppIconProvider` is the best way. I will see how it's done in React, but is it possible or ideal to emit events in vanilla way?

**Comment by adamhannigan** [comment]
@j923sneaks Luckily we have got xstate in our stack. It supports a range of different APIs that let us listen to events. Here is one for example `gameService.onSend(event => ...)`

**Review by adamhannigan — APPROVED** [review]
LGTM 👏

**Pull request merged**
