### PR TITLE
[FIX] Update ClockIssue Modal

### PR DESCRIPTION
**Pull request by 0xSacul**
# Description

Simple addition of an extra text and a button that redirects to our guide to sync the clock of his computer on Freshdesk.

The redirection is done in the same window, editable in `target="_blank"` if needed. Same for the text :) 

image

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Locally & `yarn test`
image

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Polysemouse** [comment]
Should the button open a new tab instead of navigating away from the game?  If yes, you can refer to how the implementation can be done in https://github.com/sunflower-land/sunflower-land/blob/f911ffd3906a48b63f77ebce7ad49fa8353c0031/src/features/retreat/components/resale/Resale.tsx#L36

**Comment by 0xSacul** [comment]
@Polysemouse 

I thought about it as you can see in my PR description.

But I also thought that whatever happens the person will have to refresh the page so to avoid confusion for some new player I didn't include `window.open`, a bit like it is done with the Proof of Humanity the Jigger error you can see below.

https://github.com/sunflower-land/sunflower-land/blob/c9b8dc15a9a6aac61567881c2ec6f2686d800e58/src/features/game/components/Jigger.tsx#L34

But as said, if needed we can use `window.open`

**Comment by Polysemouse** [comment]
@0xSacul That's true.  In that case we can keep your original implementation (` window.location.href = ...`)

**Comment by c-py** [comment]
@0xSacul @Polysemouse Do you think a button or a link (with underline) is more informative for the player?

I think a link indicates the player will be going to a new page and a button indicates something in game.

What do you think?

**Comment by Polysemouse** [comment]
@c-py @0xSacul I am kind of split for this one.  Underline text works better for links, however we have several underline texts in the game that are not links.  Perhaps we need to standardize underline text to reserve for links only so players have an expectation that underline texts are clickable (especially for mobile players)

**Comment by 0xSacul** [comment]
@c-py 

I think indeed that an underlined text is a better approach but it already happened that players don't understand that it's a link and don't try to click on it, however a button with the right text is always clicked even if it shouldn't 😅

I think the problem with the underlined text is that it is the same color as the text above it and so players think the underlining is something like a warning.

Waiting for your thoughts on that 👀

**Comment by c-py** [comment]
> @c-py
> 
> I think indeed that an underlined text is a better approach but it already happened that players don't understand that it's a link and don't try to click on it, however a button with the right text is always clicked even if it shouldn't 😅
> 
> I think the problem with the underlined text is that it is the same color as the text above it and so players think the underlining is something like a warning.
> 
> Waiting for your thoughts on that 👀

I agree with this 😆 . Players might not click the underline text.

Let's roll with button then!

**Review by c-py — APPROVED** [review]
LGTM!

**Pull request merged**
