### PR TITLE
[FEAT] Rock Golem

### PR DESCRIPTION
**Pull request by c-py**
# Description

This PR implements the Rock Golem rare item. The Rock Golem allows players to critically hit on their rock drops, giving a 5x bonus to the yield.

The rock golem is sad if stone 2 is mined, and will curl up into a block.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [X] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [X] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Yerid** [comment]
The original idea was better "**it stays up for 3 days, after it closes it can only be opened after 4 days**",
too much supply to call "RARE".

The idea of ​​the NFT was to make the game more interactive, but you have only taken the pixel art and not the original idea. 🤦‍♂️

**Comment by adamhannigan** [comment]
@Yerid Thanks for your feedback. Every item goes through a design phase where supply and functionality are tweaked. This is to ensure it contributes to the games economic and tokenomic model. In this case here, the rarity did not align with the accessibility and ROI it would provide to the overall game's economy. We need to balance these items so it doesn't just benefit the immediate holders, does not detriment the game economy and is still beneficial in 3-4 years.

The opening and closing animations were implemented as is to keep the scope focussed and ensure it can be released on time. Staying open for 3 days and closed after 4 days was going to add too much development effort and architecture complexity which would delay the feature for the launch dates that we are aiming for.

**Review by adamhannigan — APPROVED** [review]
LGTM. Nice work 👏

**Review by Rofrtd — APPROVED** [review]
👍🏼

**Comment by Yougottabekiddingme123** [comment]
I really like the idea of Sunflower land with its crop farming and animal rearing. I am a bit dissapointed with the direction that we are heading to with Golems. Every second game has Golems, Witches and Wizards. Lets keep this Game Original and stick to farming and mining concepts. My suggestion is to stick to Real world names or unique nicknames for real world items

For example, for mining:
Hammer drill -> Hammenova
DHT (Down the hole) ---> Downy
Rotary Drill 
Raiseboring drill
Power carbide
Grinder


For crops
Drapers
Auger

You  can come up with your own unique name or ask the community for suggestions. However, I urge you not to follow the crowd with these mythical themed items. It pops up in second game and devalues the originality of the content.

**Pull request merged**
