### PR TITLE
[FEAT] Onboarding & Gold Pass

### PR DESCRIPTION
**Pull request by adamhannigan**
# Description

Over the past month, we have been experimenting with a range of different pricing options for new users including reduced price + POKO Direct Checkout.

So far we have seen great results! 

Next week we are going to trial the idea of "Free Mints" 🔥 During this initiative, players only need to pay the gas price associated with the Land/Bumpkin NFT mint. However, to access withdrawing, trading and minting rare items the player must mint a "Gold Pass" valued at $4.99. Essentially we are offsetting the sign up fee to later in the game.

**All Current players will be given the Gold Pass for free** - _this initiative will not affect them_ 🎁 

## Why free mints?

There is a powerful narrative around letting players mint a 'free' NFT and start playing immediately. A user gets the feeling of ownership and a sense of sunk cost since they have gone through the effort to mint the item.

From a marketing POV, this will also help with engaging advertisements and collaborations with other projects - we can onboard their users much quicker with the idea of a 'free mint'.

## TODO

We are currently gathering more data on POKO direct check out so will wait until Monday to launch this initiative.

Screenshot 2023-07-13 at 8 05 43 am
Screenshot 2023-07-13 at 8 05 49 am
Screenshot 2023-07-13 at 8 05 55 am
Screenshot 2023-07-13 at 8 06 16 am

Screenshot 2023-07-11 at 3 03 04 pm
Screenshot 2023-07-11 at 3 02 48 pm
Screenshot 2023-07-12 at 6 27 56 am

### CODE REVIEW

**Review by spencerdezartsmith — CHANGES_REQUESTED** [review]
Tested and working well.

The current 2.99 offer is still showing when starting the game. That will need to be removed. I have also chatted with you re. some UX changes. 

Let me know when this has happened and I will test the flow again 🤗

**Comment by brian-man** [comment]
Art and naming feedback:
- bucks (block bucks)
- pass (gold pass)
- banner (SF, DB, WE banners)

Across the items and the PRs the naming and iconography should be consistent.

Current issues:
- gold pass icon looks like block buck icon
- Spencer's PR is titled "Season Pass" but the implementation is using a banner:
<https://github.com/sunflower-land/sunflower-land/pull/2693>

@adamhannigan @spencerdezartsmith

**Comment by adamhannigan** [comment]
@brian-man Thanks for the feedback.

I agree on the naming conventions:

Banners = Seasonal Content
Passes = Access to 'Pro' features

We will readjust the artwork for the Gold Pass - it isn't actually something that will show very often in the game (especially once bought)

Do you have any suggestions?

**Comment by brian-man** [comment]
> We will readjust the artwork for the Gold Pass - it isn't actually something that will show very often in the game (especially once bought)
> 
> Do you have any suggestions?

image

Good question.  In the image above:
- War Bond
- Jack-o-lantern
- Beta Pass
- Red Envelope
- Love Letter
- Block Buck
- Solar Flare Ticket
- Dawn Breaker Ticket

Maybe shape or proportions are the easy way to express the categories:
- ticket [SF, DB, WE] -- 3x1 landscape orientation with the semicircle cuts on the left and right sides
- pass [beta] -- 2x3 portrait orientation with the lanyard hole at the top (think backstage/press pass at concert)
- currency consumable [War Bond, Block Buck] - 4x1 landscape orientation, no cutouts
- other [JoL, Red Envelope, Love Letter] -- custom art

**Review by spencerdezartsmith — APPROVED** [review]
Working well mate. Like we spoke about.... I would love to see the logo remain during the flow. Massive improvement already.

**Comment by adamhannigan** [comment]
@brian-man I agree with your suggestions. With the new season we are moving away from the concept of tickets, and tokenising the resource (Crow Feather).

I am open to adding these suggestions in but will omit for the scope of this PR.

**Pull request merged**
