### PR TITLE
[FIX] Fix Logo

### PR DESCRIPTION
**Pull request by adamhannigan**
# Description

This PR fixes a few pixels in our brand. Great find 👏 

**TODO**

Waiting for minified version so it does not increase the size of the art

Screen Shot 2022-06-22 at 8 34 20 am

### CODE REVIEW

**Review by digital-farms — APPROVED** [review]

**Comment by hujikol** [comment]
better to put in third parties storage first, then share the link here 👍🏼

**Comment by Kiulg** [comment]
Sunflower

I did my best, there are so many lines out of grid so i tried to force it to fit

**Comment by digital-farms** [comment]
> Sunflower
> 
> I did my best, there are so many lines out of grid so i tried to force it to fit

Yeah, I don't know who drew that logo, but he sure doesn't like the grid))

> @digital-farms Something may of gone wrong with the upload. It looks like 1 pixel square in that image is actual 4-5px wide

Try downloading it from here: https://mega.nz/file/9DAX1RzS#SDztUP6SlBUE59vRWf1B-4MpalWX4EABd7c1b9eXct8

**Comment by digital-farms** [comment]
> @digital-farms Something may of gone wrong with the upload. It looks like 1 pixel square in that image is actual 4-5px wide

I didn't change anything at all, just repainted the extra pixels. The grid and resolution stayed the same

**Comment by sfwhat** [comment]
These are some reworks with less noise I made a while back

V (5)
V (6)
V (1)
V (2)
V (3)
V (4)

**Comment by adamhannigan** [comment]
@sfwhat Looks great. Thanks!

**Comment by sfwhat** [comment]
My pleasure, glad to help

**Pull request merged**
