### PR TITLE
[FEAT] Sound notifications

### PR DESCRIPTION
**Pull request by jcads**
# Description

Audio notification fires when all plants are ready to be harvested. 

I just added a placeholder audio for now. If you have a specific audio in mind just let me know.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

1. Plant a sunflower seed then minimize the browser. Notif should ifre
2. When all plants are ready to harvest. Harvest one, then plant a new one. Once that's ready, notif should fire.

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by adamhannigan** [comment]
Nice innovation @jcads 👏 

What does the licence look like for this music file? @Rofrtd Might be able to help us find something/collab with the musicians for a file that is free to use

**Comment by jcads** [comment]
Thanks @adamhannigan!

> What does the licence look like for this music file?

I honestly don't know the license of it, I just grabbed this mp3 file from my downloads directory. 

<br />

>@Rofrtd Might be able to help us find something/collab with the musicians for a file that is free to use

Maybe we can have a farm vibe sound effect (like a tractor horn).

**Comment by adamhannigan** [comment]
@jcads Putting this PR on hold at the moment as there is a bit of discussion around sound effects and also the App Icon (it has been quite buggy lately, we are planning what to do)

**Comment by adamhannigan** [comment]
Closing as Romy has been working on this in https://github.com/sunflower-land/sunflower-land/pull/329

**Pull request closed without merging**
