### PR TITLE
[FEAT] Profile pic v2

### PR DESCRIPTION
**Pull request by AzaroQL**
# Description

A bit updated profile pic:
- new progress bar
- smaller size + size for mobile
- bumpkin background as profile background
- moved toasts to the right

Desktop:
image

Mobile:
image

Other bumpkin variations:
image
image
image

Toasts:
image

PS: Animations will come in v3 :/

# Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by spencerdezartsmith** [comment]
Hey @AzaroQL... size is looking much better on desktop. I actually think the new desktop size is also ok on mobile. The smaller version on mobile looks a little too small I think.

Also there are a couple of things to mention:

- When Adam and I spoke about this last he was concerned about moving the level number to the centre because it no longer implied that you were "working towards another level". After looking at this version I agree with him. I think its better to keep the level indicator to the end of the progress bar. 
- There is a strange clump of grey pixels on the left side of the bumpkin
Screen Shot 2022-11-28 at 1 28 24 pm

- The background circle is perfectly round which looks out of place next to the pixelated circle effect. Can we have the backgrounds edge be pixelated as well?

**Comment by AzaroQL** [comment]
- removed mobile size
- hidden secondary tool(grey pixels on the left side of bumpkin)
- added pixelized border to bg

TODO:
Waiting for Oniel to move lvl badge to its old position

**Comment by spencerdezartsmith** [comment]
> * removed mobile size
> * hidden secondary tool(grey pixels on the left side of bumpkin)
> * added pixelized border to bg
> 
> TODO: Waiting for Oniel to move lvl badge to its old position

Can you message me when you're ready for this to be re reviewed?

**Review by spencerdezartsmith — APPROVED** [review]
This is excellent. I am so happy with this improvement! 👏🏼 🎉

**Pull request merged**
