### PR TITLE
[FIX] Autosave Before Travel

### PR DESCRIPTION
**Pull request by ShiningMinions**
# Description

- Will now fire an autosave event the moment you open the IslandTravel modal.
- Will now show "Loading..." text if player is autosaving + has travel modal opened.
- Waits for autosave event to complete before presenting player any navigation options.
- In attempt to keep codebase cleaner, I also refactored-away the "IslandTravelWrapper" components by hoisting context to a parent wrapper instead. 
  - (I was originally planning a different solution where I was going to write a third `IslandTravelWrapper.tsx` component, so I refactored to not violate WET principle. However, I ended up scrapping this but kept the refactor).

https://user-images.githubusercontent.com/103600068/199262517-f4bf24ec-e8b9-41e1-a75e-05a46a3b6e2c.mp4

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

visual, see video above

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Polysemouse** [comment]
https://github.com/sunflower-land/sunflower-land/pull/1580/files
There are quite some conflicts you might have to resolve with the recent changes of the merged PR 😆

**Comment by ShiningMinions** [comment]
> https://github.com/sunflower-land/sunflower-land/pull/1580/files There are quite some conflicts you might have to resolve with the recent changes of the merged PR laughing

It's all your fault :stuck_out_tongue_winking_eye:

**Comment by ShiningMinions** [comment]
I'm resolving these conflicts again now.

**Comment by ShiningMinions** [comment]
I honestly might  close this PR and open a new one. This PR became a mess with all of the conflicts.

**Pull request closed without merging**
