### PR TITLE
[FEAT] Remove buildings and collectibles

### PR DESCRIPTION
**Pull request by spencerdezartsmith**
# Description

This PR adds the ability for a player to be able to remove buildings and collectibles after they have been placed. We have repurposed the Rusty Shovel for this actions. 

If a player has a Rusty Shovel AND has the Rusty Shovel selected, they can click on a building/collectible and see a modal explaining the removal. If the item has no dependencies then it will be removed and put back into either your buildings list or your chest.

There are a couple of cases where there are dependencies on the placed item:

Hen House: This gives you capacity to be able to place chickens. If you remove this building, the placed chickens that rely on that building will also be removed. They will go back into your inventory.
Chicken Coop: This increases your chicken capacity. Again, it will remove the placed chickens that depend on it. 
Water Well: Any plots that are dependant on the water well will have their crops removed when you remove the well. 

The Rusty Shovel will be no longer given by default any more. It will no longer be a required ingredient for the Shovel. 

The Power Shovel is a sneak peak of whats to come 😄 

I have taken some changes from @Polysemouse (thank you) which aligned with this feature. You can see the unplaced buildings in this list.
Screen Shot 2022-11-16 at 4 35 01 pm
Screen Shot 2022-11-16 at 3 09 45 pm
Screen Shot 2022-11-16 at 4 07 44 pm
Screen Shot 2022-11-16 at 4 09 19 pm
Screen Shot 2022-11-16 at 3 11 01 pm

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

This has been tested against the api changes (You need api changes to test full flow)

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ShiningMinions** [comment]
This is awesome. Just a few points from me:

1. Unless I'm missing it, also consider the case when food is being prepped and the kitchen is removed.
2. IMO a "hammer" would make more sense as a tool to pick-up buildings/collectibles.
3. IMO a "shovel" would make more sense as the tool allowing you to move resource nodes (i.e. trees, rocks, etc).
4. Also a reminder that a "rusty shovel" is a core ingredient to craft a "shovel". Unsure if that would impact this crafting.

Cheers!

**Comment by stevew00dy** [comment]
I agree that it makes more sense here to have a hammer than a shovel. We have it in the inventory already. Would make sense to use it for this.

**Comment by spencerdezartsmith** [comment]
> This is awesome. Just a few points from me:
> 
> 1. Unless I'm missing it, also consider the case when food is being prepped and the kitchen is removed.
> 2. IMO a "hammer" would make more sense as a tool to pick-up buildings/collectibles.
> 3. IMO a "rusty shovel" would make more sense as the tool allowing you to move resource nodes (i.e. trees, rocks, etc).
> 4. Also a reminder that a "rusty shovel" is a core ingredient to craft a "shovel". Unsure if that would impact this crafting.
> 
> Cheers!

Thanks for the feedback!

Yep, food is handled by default when a kitchen is removed. 
Yep, the rusty shovel has been removed from the ingredient requirements of the shovel. 

Will chat will all about the Hammer.

**Comment by adamhannigan** [comment]
Amazing work @Rofrtd @spencerdezartsmith I can finally fix up my farm 💪 

Just a couple of suggestions:

1. Can we remove a building/collectible that is in the progress of being built?
2. Analytics on `Collectible removed` & `Building removed` - We can hopefully tie in some achievements to this in the future 😄

**Pull request merged**
