### PR TITLE
[FEAT] Desert Rose

### PR DESCRIPTION
**Pull request by c-py**
# Description

Adds the Mutant Flower `Desert Rose`. This is an extra random reward you can get from planting flowers during Pharaoh's Treasure season

It gives 10% crit chance for +1 flower.

## Screen Shots

**Finding a Mutant Flower**

**Finding a new species and Mutant Flower in one hit**

**Flower placed**

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

localhost

# Checklist:

- [X] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [X] Screenshot if it includes any UI changes

### CODE REVIEW

**Comment by Dionis404** [comment]
Will Carrot Sword increase the chance of a rose falling out?

**Comment by eliasSFL** [comment]
> Will Carrot Sword increase the chance of a rose falling out?

@Dionis404 Carrot Sword only affects Mutant Crops, not Mutant Flowers

**Comment by Dionis404** [comment]
> > Will Carrot Sword increase the chance of a rose falling out?
> 
> @Dionis404 Carrot Sword only affects Mutant Crops, not Mutant Flowers

That's what I thought, but wanted to clarify that point.

**Review by eliasSFL — APPROVED** [review]
LGTM!

**Comment by heatedlime** [comment]
Does this stack with hummingbird or is it a separate chance, so with hummingbird and this, you could get 3?

**Pull request merged**
