### PR TITLE
[FEAT] Arcade Machine Donation

### PR DESCRIPTION
**Pull request by j923sneaks**
# Description

This PR implements a simple donation message should the community want to reward contributors. The donation flow is a bit different as there is no in game input interface; instead it will be like a simple MATIC transfer to an address. Major reason is I dont have the time to integrate donation modal plus config creations lol. Also, Arcade Machine exist inside main Land which does not have Community Context.

I'm also trying a new approach which involves smart contracts to automatically distribute MATIC rewards. Reason for having different address per game is that each contributor list is different.

If the devs have spare time I would also appreciate smart contract reviews :)

### Donation Addresses
Greedy Goblin
https://polygonscan.com/address/0xa85c0e9495ba7860c231b529258132b5c9075b8a

Chicken Fight
https://polygonscan.com/address/0x74c0c166c919bbe0b160fc27fc58eeee361bdfd4

Fixes #issue

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manual test - testnet

image

Deposit Regression test
image

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Polysemouse** [comment]
We have another component (or similar) in game which players can donate directly in the in game UI.
Screenshot_20230105-215927
@j923sneaks Would you think it's better to use that instead?  Sunflower Land gears towards players who are not familiar with the blockchain technology, and I believe that having the UI in game might be easier for users to make donations

**Comment by j923sneaks** [comment]
@Polysemouse sorry for the late reply. Yep I'll do it! Just found out that `donationMachine` can exist without `CommunittyProvider` :) moving this to Draft

**Comment by j923sneaks** [comment]
Updated to include input field for MATIC donations. Based the layout from PD's `BottleDonation.tsx`

image

**Review by adamhannigan — APPROVED** [review]
LGTM 🚀 🤑

**Pull request merged**
