### PR TITLE
[CHORE] Calculate SFF in Liquidity Pools At Snapshot

### PR DESCRIPTION
**Pull request by AncientHorse**
# Description

This script will calculate the number of SFF for each wallet participating in a Liquidity Pool at Quickswap.  Most important, I don't have a snapshot of the blockchain so the total number of SFF at block 23451693 for each LP contract is currently a variable.  I'm using estimates but it would be better if someone who has access could enter the correct values in SFF-LP_Calc.sh.

Fixes # 110

## Type of change

Please delete options that are not relevant.

- [X ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested on CentOS and Ubuntu per README.  Dependencies required for functionality also in README.

### CODE REVIEW

**Comment by adamhannigan** [comment]
@AncientHorse Awesome work! I will spend some time tomorrow setting this up with our snapshot and keep you posted. 💪

**Comment by adamhannigan** [comment]
@AncientHorse I've got the scripts up and running.

Is the variable that must be inserted the total amount of pool tokens (i.e. the LP token that gets minted) or the amount of SFF in the pool at that point in time?

**Comment by AncientHorse** [comment]
> Is the variable that must be inserted the total amount of pool tokens (i.e. the LP token that gets minted) or the amount of SFF in the pool at that point in time?

The variable is the number of SFF owned by the LP contract at block 23451693.  The LP contracts are listed in the .sh script.  For example, the DAI/SFF pool is 0xe5b2c4d8bcbe27115b34c9a8400fff984fe480e8.  This is the only value I wasn't able to pull.

I probably should have added a key so people know what the different fields in the CSV are.  

Type of Contract, Contract, Contract Address, Player Wallet Address, LP Tokens in Wallet, LP Tokens as % of Total, Total LP Tokens in Contract, Block Height, **SFF Tokens in LP Owned by Player**

The important resulting value is the final field of the CSV.

**Comment by adamhannigan** [comment]
I find it easier to use the Web3 API than using the actual snapshotted block. Here is some code using the `balanceOf` and `blockNumber` argument that lets us retrieve the balance at a certain point.

This assumes you have initialised Web3  and this.token is the Token.sol contract representing SFF.

```
 // Addresses of the LP pairs (which hold the SFF token)
    const LP = [
      [
        "SFF/DAI - QuickSwap",
        "0xe5b2c4d8bcbe27115b34c9a8400fff984fe480e8",
      ],
      [
        "SFF/ETH - QuickSwap",
        "0x90c2bcab97204b1f06baea3ccdf5258f599dfa29",
      ],
      [
        "SFF/WMATIC - QuickSwap",
        "0xcea1571d21de966aa5bcc23cec9bf16b7fec40d7",
      ],
      [
        "SFF/USDC - QuickSwap",
        "0xcea1571d21de966aa5bcc23cec9bf16b7fec40d7",
      ],
      [
        "SFF/USDT - QuickSwap",
        "0xc5b4f981831a055849d628a06cc5bbc4ad9448fd",
      ],
      [
        "SFF/QUICK - QuickSwap",
        "0x4eb58cc0d969daa476b131432f51590cfdb5f7fa",
      ],
    ];

    // Announced Block number to pause the game
    const BLOCK_NUMBER = 23451693;

    // For each pair, fetch the SFF balance at the block number
    const values = await LP.reduce(async (amounts, [name, address]) => {
      const previous = await amounts;

      const amount = await this.token.methods
        .balanceOf(address)
        .call(
          { from: this.account, blockNumber: BLOCK_NUMBER },
          BLOCK_NUMBER
        );

      return [...previous, [name, amount, fromWei(amount)]];
    }, Promise.resolve([]));
```

This produces these values. Wei and Eth are the 2 numeric values in the tuples.

```
[
    [
        "SFF/DAI - QuickSwap",
        "2626818011215020697910",
        "2626.81801121502069791"
    ],
    [
        "SFF/ETH - QuickSwap",
        "21479571815287322932462",
        "21479.571815287322932462"
    ],
    [
        "SFF/WMATIC - QuickSwap",
        "121440424801610909895950",
        "121440.42480161090989595"
    ],
    [
        "SFF/USDC - QuickSwap",
        "121440424801610909895950",
        "121440.42480161090989595"
    ],
    [
        "SFF/USDT - QuickSwap",
        "201549277087792448983",
        "201.549277087792448983"
    ],
    [
        "SFF/QUICK - QuickSwap",
        "560385641976149236312",
        "560.385641976149236312"
    ]
]
```

**Comment by adamhannigan** [comment]
@AncientHorse The scripts are running well, but it looks like all of the holders are not in there. I had 2 separate addresses providing LP, but only one appeared in the results

Is there some sort of pagination being applied to the covalent API calls?

**Comment by AncientHorse** [comment]
@adamhannigan Checking with support, but I believe it will either respond with the correct comprehensive results or timeout and give error (for example, trying to get all SFF holders gives the database timeout error).  I'll keep you updated...

**Comment by AncientHorse** [comment]
@adamhannigan Yikes!  You are right.  I'll fix this.

**Comment by AncientHorse** [comment]
@adamhannigan 

* Made new variable for pagesize
* Changed block height to a variable
* Entered actual values instead of estimates for SFF LP pool balances

As a result, an additional 50 wallets from the SFF/WMATIC pool were added.

**Comment by AncientHorse** [comment]
Another update to fix bad copy/paste on addresses.

**Comment by adamhannigan** [comment]
@AncientHorse Works well for me 👍 

There was a small copy paste in the `WMATICBALANCE` value, it was using the same `ETHBALANCE` value.

Ran the scripts and all looks good to me 👏 Nice work

**Comment by AncientHorse** [comment]
Fixed copy paste issue for WMATIC balance.

**Comment by adamhannigan** [comment]
@AncientHorse Nice work. We will use these values in the migration 💪

**Comment by Pranav-yadav** [comment]
@AncientHorse & @adamhannigan why the main file (script) is in PHP ?

I mean, 
If u r going to perform only calculations, isn't it efficient to use low level prog. language like C or even C++. (with, compile time strict type checks)

PS: I'm a beginner, here for soleley learning purposes. I've worked with PHP :)

**Comment by adamhannigan** [comment]
@AncientHorse I will close this as we can consider it done ✅ Nice job :)

**Pull request closed without merging**
