### PR TITLE
[Fix] No Pick No Mine 

### PR DESCRIPTION
**Pull request by Z1kou**
# Description

The mining animation won't be triggered if you have a pickaxe selected in the inventory and have 0 pickaxes

Fixes #issue
If you have no pickaxes then no animations for mining would be triggered
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Yarn dev 

Yarn test
Yarn test mine

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by adamhannigan — CHANGES_REQUESTED** [review]
Good improvement! I noticed this bug recently.

Awesome to have you back in the code base. I have left a few small suggestions and I found a bug when mining the Gold ;)

**Comment by Z1kou** [comment]
@adamhannigan  I have updated everything using all your tips and remarks Thanks for the lessons🤗!

**Comment by adamhannigan** [comment]
@Z1kou It still appears that there are some changes in the `Tree.tsx` file 🤔

**Comment by Z1kou** [comment]
@adamhannigan  it was related to the the other PR getting merged first I fixed it now what do you think 🦾

**Review by adamhannigan — APPROVED** [review]
LGTM. Awesome work 🚀

**Pull request merged**
